---
output:
  pdf_document: default
  html_document: default
---

# Deep Dive: Sampling Distributions [DRAFT]

## A tale of two methods

In this chapter, we focus on describing the sampling distribution of the mean. Our goal is to understand the logic behind two different methods for estimating the variance of the sampling distribution of the mean. A thorough understanding of both of these two estimation methods lays the foundation for understanding Analysis of Variance (ANOVA).


## A student population

Consider a scenario where there is a large university with 50,000 students and we have the heights of all 50,000 students. The mean height of all 50,000 students is 172.50 cm and the variance is 156.3236 cm$^2$. The heights of all the university students are illustrated in Figure 1A. This figure is shaded with stick figures wearing trousers that remind us this distribution represents people.

The mean of the population people's heights (in cm) is calculated as below (where N = 50,000).

$$
\begin{aligned} 
\mu_{people} &= \frac{\sum_{i=1}^{N=50000}{X_i}}{N}\\
&= 172.50\\
\end{aligned} 
$$

The variance of the population people's heights (in cm$^2$) is calculated as below (where N = 50,000).

$$
\begin{aligned} 
\sigma_{people}^2 &= \frac{\sum_{i=1}^{N=50000}{(X_i - \bar{X})^2}}{N}\\
&= 156.3236\\
\end{aligned} 
$$




## Random sampling process

Now imagine that we are interested in studying the random sampling process. Specifically we are interested in examining the variability in sample means that occurs when taking random samples of students from the university. Indeed, imagine that we obtained a sample of $n$ = 25 students and calculated a sample mean ($\bar{x}$). Then we repeated this sampling process an infinite number of times such that we have an infinite number of sample means. This set of an **infinite number of sample means** is conceptually illustrated in Figure 1B and we refer to it as the *sampling distribution of the mean*. Moreover, **because we sampled from a single population** the variability in sample means is due only to the **random sampling error** that occurs when the sample size is 25 ($n = 25$) and the population variance is 156.3236 (i.e., $\sigma_{people}^2 =156.3236$).

[Figure 1A and 1B goes here]

## Population: What's in a name

Typically, in psychology, when we use the word "population" we are referring to a population of people - such as those illustrated in Figure 1A. However, in statistics, a population is simply set of elements (often people) about which we wish to draw conclusions. In this chapter, we shift our focus from thinking of the distribution of people in Figure 1A as a population to **also** thinking of the distribution of sample mean in Figure 1B as a population. Doing so may seem counter intuitive but it the logical foundation for Analysis of Variance (ANOVA).

### Sample means in context

Thinking of the distribution of sample mean as a population can be a bit tricky - since there are two populations that we could be referring to when we use the word "population". Notation helps to keep things straight. In this book, when we are talking about a distribution of people (see Figure 1A), we use $N$ to indicate the number people in the population and $n$ to refer to the number of people in a subset of the population (what we typically refer to as a sample). Likewise, when we are talking about a distribution of sample means (see Figure 1B), we use $A$ to indicate the number sample means in the population and $a$ to refer to the number of sample means in a subset of the population.

Consider a concrete example. When we obtain a sample of people ($n$ = 25) we can think those people as being subset of the population of people ($N$=50,000), see Figure 1A. If we calculate a sample mean ($\bar{x}$) based on those 25 people we can think of that single sample mean ($a$ = 1) a being subset of a population of sample means ($A = \infty$), see Figure 1B. Alternatively, imagine we obtained three samples from the population of people, Figure 1A, each composed of 25 people ($n$ = 25 for each sample). Then we calculated the sample mean ($\bar{x}$) for each of the three samples. We could think of those three sample means ($a$ = 3) as being a subset of a population of sample means ($A = \infty$), see Figure 1B.

### Distribution of sample means as a population

Because we are thinking of the distribution of sample means as a population we can calculate a mean and variance for the distribution of sample means. The mean of the population of sample means is calculated as below. Notice that we used the symbol, $\mu_{\bar{x}}$, to represented this value. Further notice, the little $\bar{x}$ beside the $\mu$ in $\mu_{\bar{x}}$ which indicates it is sample means that are being averaged. As noted previously, we use $A$ instead of $N$ to represent the number of sample means (where $A$ = infinity, because there are an infinite number of sample means in the distribution)[^deep_sampling-1]

[^deep_sampling-1]: I know it doesn't make sense the divide by infinity; however, in formal mathematics we would write this up in a different way describing the resulted value as an *expected value*. I use dividing by infinity simply as a way to show consistency with other formulas with the aim of increasing conceptual clarity at the expense of correct notation.

$$
\begin{aligned} 
\mu_{\bar{x}} &= \frac{\sum_{i=1}^{A=\infty}{\bar{x}_i}}{A}\\
&= 172.50\\
\end{aligned} 
$$

The mean of the sample means, $\mu_{\bar{x}}$, will always be the same as that of the people's heights, $\mu_{people}$. Consequently, any conclusions we make about *population means* based on Figure 1B (i.e., $\mu_{\bar{x}}$) will also apply to Figure 1A (i.e., $\mu_{people}$). This is a crucial point to keep in mind as we proceed through this chapter. Although we are ultimately interested in making conclusion about the mean of the people (i.e., $\mu_{people}$) - all our work in this chapter (and in ANOVA) is based on the mean of distribution of sample mean in Figure 1B (i.e., $\mu_{\bar{x}}$).


##  Sample mean distribution variance

When there is *one* **population of people** (see Figure 1A) there is a single distribution of sample means that corresponds to that population (see Figure 1B). There are two methods for calculating the variance of this distribution of sample means.

### Method 1: Calculate the variance of infinite sample means

In this first method, we use an infinite number of sample means and simply calculate the variance. Obviously, this is an impractical solution because we could never obtain an infinite number of samples and then calculate the variance for each sample. Conceptually, however, it's good to keep this calculation method in mind - since it reminds us of principles we've already learned about the variance of populations [^deep_sampling-2]

[^deep_sampling-2]: As noted previously, the notation is incorrect and I should really have expressed this as an expected value to be correct. But for conceptual clarity I divide by infinity to make the linkages to other equations clear.

$$
\begin{aligned} 
\sigma_{\bar{x}}^2 &= \frac{\sum_{i=1}^{A=\infty}{(\bar{x}_i - \bar{\bar{x}})^2}}{A}\\
&= 6.252944\\
\end{aligned} 
$$

Notice how this is similar to population formula when we are dealing with people. This formula differs for the typical formula because we are using on sample means ($\bar{x}$) instead of attributes of people ($X$). As well, we just use $A$ to indicate the number of elements used (i.e., an infinite number of sample means) in the calculation rather than $N$.

**When there is only one population of people** this formula will reflect variability in sample means due to random sampling. When there is more than one population of people - it becomes more complicated. We'll discuss that situation in a future chapter.

### Method 2: CLT shortcut: *Calculation* of variance of infinite sample means

Fortunately we don't need to obtain an infinite number of sample means to determine the variance of the distribution of an infinite number of sample means. There is a "shortcut formula" we can used based on the Central Limit Theorem (CLT). More specifically, the variance of the distribution of sample means depends on both the number of people in each sample ($n$) and the variability in the people's heights in the population ($\sigma_{people}^2$). 

$$
\begin{aligned} 
\sigma_{\bar{x}}^2 &= \frac{\sigma_{people}^2}{n}\\
&= \frac{156.3236}{25}\\
&= 6.252944\\
\end{aligned} 
$$

The reason this formula works should not be obvious - at all. If you are looking at this formula trying to figure out why it works - I suggest you stop and just accept that it does work. If you want to understand why it works, I suggest you [consult](https://archive.org/details/statisticsfifthe00will) [@hays1994statistics] who provides a statistical proof for the Central Limit Theorem.

It's helpful, moving forward to, think of this formula ($\frac{\sigma_{people}^2}{n}$) as representing the *variability in means due to random sampling*. No matter the situation - this formula will always reflects the variability in sample means due ONLY to random sampling.

### Ratio comparison of two methods

Thus, far we have calculated the variance of the distribution of sample means using two different methods.

-   Method 1: Variance of sample means calculated using sample means

-   Method 2: Variance of sample means calculated using CLT shortcut formula

Although we can just look at the numbers resulting from these two methods and compare them, that's not how statisticians typically handle such comparisons. The approach used by statisticians to compare two numbers is to create a ratio. That is, take one number and divide it by the other number. If the two numbers are the same the ratio will be 1.00. If the ratio is larger than 1.00 it means the number on the top was bigger than the number on the bottom.

You can see the ratio comparing these two methods below is 1.00 - so we conclude two methods produced the same result.

$$
\begin{aligned} 
\text{ratio comparing methods} &= \frac{\text{variance of sample means calculated using sample means}}{\text{variance of sample means calculated using CLT shortcut formula}}\\
&=\frac{\frac{\sum_{i=1}^{A=\infty}{(\bar{x}_i - \bar{\bar{x}})^2}}{A}}{\frac{\sigma_{people}^2}{n}}\\
&=\frac{6.252944}{6.252944}\\
&= 1.00\\
\end{aligned} 
$$

In this section, we focused on actually **calculating** the variance of the distribution of sample means using two methods. But to actually calculate this variance we needed an infinite number of sample means (method 1) or knowledge of the population variance (method 2). Both are unrealistic methods to determining this value.

In the next section, below, we recognize that we can likely never know or calculate the variance of the distribution of sample means. Instead, we focus on **estimating** the variance of the distribution of sample means. An estimated value is an approximation of the actual value that will differ due to the effects of random sampling.




```{r, include=FALSE}
# Set up sample information for rest of chapter
set.seed(20210901)
pop_sd = sqrt(156.3236)
pop_mean = 172.50

n_sample <- 5 #don't use n it's a reserved variable name for this package

sample_data <- round(rnorm(n_sample)*pop_sd+pop_mean)
sample_mean <- round(mean(sample_data),1)
sample_var <- var(sample_data)*(n_sample-1)/(n_sample)
est_pop_var <- round(var(sample_data),1)
df <-  n_sample-1
barx <- sample_mean
x1 <- sample_data[1]
x2 <- sample_data[2]
x3 <- sample_data[3]
x4 <- sample_data[4]
x5 <- sample_data[5]
sumx2 <- sum((sample_data-mean(sample_mean))^2)



sample_data2 <- round(rnorm(n_sample)*pop_sd+pop_mean)
sample_mean2 <- round(mean(sample_data2),1)
sample_var2 <- var(sample_data2)*(n_sample-1)/(n_sample)
est_pop_var2 <- round(var(sample_data2),1)
df2 <-  n_sample-1
barxb <- sample_mean2
x1b <- sample_data2[1]
x2b <- sample_data2[2]
x3b <- sample_data2[3]
x4b <- sample_data2[4]
x5b <- sample_data2[5]
sumx2b <- sum((sample_data2-mean(sample_mean2))^2)




sample_data3 <- round(rnorm(n_sample)*pop_sd+pop_mean)
sample_mean3 <- round(mean(sample_data3),1)
sample_var3 <- var(sample_data3)*(n_sample-1)/(n_sample)
est_pop_var3 <- round(var(sample_data3),1)
df3 <-  n_sample-1
barxc <- sample_mean3
x1c <- sample_data3[1]
x2c <- sample_data3[2]
x3c <- sample_data3[3]
x4c <- sample_data3[4]
x5c <- sample_data3[5]
sumx2c <- sum((sample_data3-mean(sample_mean3))^2)

dfpooled <- df+df2 + df3
est_pop_var_pooled <- (est_pop_var+est_pop_var2+est_pop_var3)/3

a <- 3
xbarbar <- round((barx+barxb+barxc), 3)
xbar_vector <- c(barx, barxb, barxc)
method1_var <- round(var(xbar_vector),3)

```

## Estimating sample mean distribution variance

In this section we focus on estimating the variance of the distribution of sample means using sample data. Imagine that we obtained three samples (each $n$ = 25) from the population of people illustrated in Figure 1A. The statistics for those three sample are presented below.

| Sample Number | Sample size ($n$) | Mean ($\bar{x} = \frac{\Sigma x_i}{n}$) | Variance ($s^2=\frac{\Sigma (x_i - \bar{x})^2}{n-1}$) |
|:-------------:|:-----:|:-----------------------------:|:------------------------------------------------:|
| 1             |  25 | `r sample_mean`      | `r est_pop_var`                         |
| 1             |  25 | `r sample_mean2`     | `r est_pop_var2`                        |
| 1             |  25 | `r sample_mean3`     | `r est_pop_var3`                        |


### Method 1: Estimate the variance of infinite sample means using 3 sample means

We can use the sample means presented in the table above to estimate the variance of the distribution of sample mean as illustrated in the formula below. Recall, we use the lower case "$a$" to represent the number of sample means (in the case because we have 3 sample means $a = 3$).

$$
\begin{aligned} 
s_{\bar{x}}^2 &= \frac{\sum_{i=1}^{a=3}{(\bar{x}_i - \bar{\bar{x}})^2}}{a-1}\\
\end{aligned} 
$$

In this example (see table above), we have 3 sample means (each based on n = 25) so $a = 3$. Let's estimate the variance of the distribution of sample means (Figure 1B) using these three sample means.

First, we calculate the mean of the three sample means ($\bar{\bar{x}}$) because we will need that in the variance formula.

$$
\begin{aligned} 
\bar{\bar{x}} &= \frac{\sum_{i=1}^{a=3}{\bar{x}_i}}{a}\\
&= \frac{\bar{x}_1+\bar{x}_2+\bar{x}_3}{a}\\
&= \frac{`r barx` + `r barxb`  + `r barxc` }{`r a`}\\
&= `r xbarbar`
\end{aligned} 
$$


Second, we estimate the variance of the population of sample means ($s_{\bar{x}}^2$, see Figure 1B) using the set of sample means. Notice the use of "-1" in the denominator - [which we discussed previously in the sample accuracy chapter](https://dstanley4.github.io/psyc6060bookdown/sampling-accuracy.html#estimating-sigma2). The use of the "-1" in the denominator means we are not calculating the variance of these three sample means. Rather, when we use "-1" in the denominator we are **estimating** the variance of the population of sample means from which they were obtained (i.e., the distribution of sample means depicted in Figure 1B).


$$
\begin{aligned} 
s_{\bar{x}}^2 &= \frac{\sum_{i=1}^{a=3}{(\bar{x}_i - \bar{\bar{x}})^2}}{a-1}\\
&= \frac{(\bar{x_1}- \bar{\bar{x}})^2+(\bar{x_2}- \bar{\bar{x}})^2+(\bar{x_3}- \bar{\bar{x}})^2}{a-1}\\
&= \frac{(`r (barx)` - `r (xbarbar)`)^2+(`r (barxb)`  - `r (xbarbar)`)^2+(`r (barxc)` - `r (xbarbar)`)^2}{3-1}\\
&= `r method1_var`
\end{aligned} 
$$

Thus, the "population" variance of the distribution of sample means ($\sigma_{\bar{x}}^2$, see Figure 1B) is estimated, using Method 1, to be  $s_{\bar{x}}^2 = `r method1_var`$. Remember though `r method1_var` is just an *estimate* of the population value ($\sigma_{\bar{x}}^2$) based on three sample means.

### Method 2: CLT shortcut: *Estimation* of variance of infinite sample means

We can use the information presented in the table above in another way to estimate the variance of the distribution of sample means. Indeed, recall than another approach to calculating the variance of the distribution of sample means is to use the shortcut formula based on the Central Limit Theorem (CLT).

$$
\begin{aligned} 
\sigma_{\bar{x}}^2 &= \frac{\sigma_{people}^2}{n}\\
\end{aligned} 
$$

#### Estimating $\sigma_{people}^2$ with $s_{people}^2$

The problem with the formula above is that you need to know the variance of the all the people in the population ($\sigma_{people}^2$) - and we don't know the variance of all the people in the population. But, we do have three samples from that population of people. Because the three samples are from the same population of people - we know each sample provides an estimate of the same (single) variance of people in the population. Therefore, we can combine those variance estimates into a better (or average) estimate of the variance of the people ($s_{people}^2$) in the population using the formula below.

$$
\begin{aligned}
s_{people}^2 &= MSE_{people}\\
&= \frac{\sum_{i=1}^{a=3}(n_i-1)s_i^2}{\sum_{i=1}^{a}(n_i-1)} \\
&= \frac{(n_1-1)s_1^2 + (n_2-1)s_2^2 + (n_3-1)s_3^2}{(n_1-1)+(n_2-1)+(n_3-1)} \\
&= \frac{(25-1)s_1^2 + (25-1)s_2^2 + (25-1)s_3^2}{(25-1)+(25-1)+(25-1)} \\
&= \frac{(25-1)`r est_pop_var` + (25-1)`r est_pop_var2` +(25-1)`r est_pop_var3`}{(25-1) + (25-1) + (25-1)} \\
&= \frac{`r 24*est_pop_var` + `r 24*est_pop_var2` + `r 24*est_pop_var3`}{75 -3} \\
&= \frac{`r as.character((24*est_pop_var + 24*est_pop_var2 +  24*est_pop_var3))`}{72} \\
&= `r est_pop_var_pooled` \\
\end{aligned}
$$

When the three sample sizes are the same the above formula just boils down to an average:

$$
\begin{aligned}
s_{people}^2 &= MSE_{people}\\
&= \frac{s_1^2 + s_2^2 + s_3^2}{3} \\
&= \frac{`r est_pop_var` + `r est_pop_var2` + `r est_pop_var3` }{3} \\
&= \frac{660.7}{3} \\
&= `r est_pop_var_pooled` \\
\end{aligned}
$$

We use different names to refer to the resulting variance number - we could just call it a better estimate of the population variance ($s_{people}^2$). But statisticians also use the term pooled variance ($s_{pooled}^2$) to refer it. Other times statistician use the term Mean Square Error ($MSE$) to refer to it. You should realize that these are all just synonyms for variance: $s_{people}^2 = s_{pooled}^2 = MSE_{people} = MSE$.


Armed with the estimate of the variance of the people in the population ($s_{people}^2$) we can use the CLT shortcut formula to obtain an estimate of the variance of the distribution of sample means.

$$
\begin{aligned} 
s_{\bar{x}}^2 &= \frac{s_{people}^2}{n}\\
\end{aligned} 
$$

Thus, using Method 2: CLT shortcut, our estimate of the variance of the distribution of sample means is XXX. 

### Ratio comparison of two methods

We revisit the ratio comparison methods and see that we are using estimates that the

But on average it will be one.

See this simulation with 6 cols (m/var est), 2 col (both calcs), 1 col ratio.

When everything comes from 1 population on average.....

Show ratio with formulas and numbers

## Walk away points

-   Sometimes we need to shift our thinking and conceptualize the distribution of sample means as the population to which we are trying to generalize
-   think of var/n as representing the variability in sample means due to random sampling
-   the findings we illustrate here only hold when there is only one population the sample means come from that one population.
