<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.32">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>multiple_regression</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="19-multiple_regression_files/libs/clipboard/clipboard.min.js"></script>
<script src="19-multiple_regression_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="19-multiple_regression_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="19-multiple_regression_files/libs/quarto-html/popper.min.js"></script>
<script src="19-multiple_regression_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="19-multiple_regression_files/libs/quarto-html/anchor.min.js"></script>
<link href="19-multiple_regression_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="19-multiple_regression_files/libs/quarto-html/quarto-syntax-highlighting-37eea08aefeeee20ff55810ff984fec1.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="19-multiple_regression_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="19-multiple_regression_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="19-multiple_regression_files/libs/bootstrap/bootstrap-81267100e462c21b3d6c0d5bf76a3417.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<link href="19-multiple_regression_files/libs/htmltools-fill-0.5.8.1/fill.css" rel="stylesheet">
<script src="19-multiple_regression_files/libs/htmlwidgets-1.6.4/htmlwidgets.js"></script>
<script src="19-multiple_regression_files/libs/plotly-binding-4.11.0/plotly.js"></script>
<script src="19-multiple_regression_files/libs/typedarray-0.1/typedarray.min.js"></script>
<script src="19-multiple_regression_files/libs/jquery-3.5.1/jquery.min.js"></script>
<link href="19-multiple_regression_files/libs/crosstalk-1.2.2/css/crosstalk.min.css" rel="stylesheet">
<script src="19-multiple_regression_files/libs/crosstalk-1.2.2/js/crosstalk.min.js"></script>
<link href="19-multiple_regression_files/libs/plotly-htmlwidgets-css-2.11.1/plotly-htmlwidgets.css" rel="stylesheet">
<script src="19-multiple_regression_files/libs/plotly-main-2.11.1/plotly-latest.min.js"></script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="fullcontent quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">




<section id="multiple-regression" class="level1">
<h1>Multiple regression</h1>
<p>The following CRAN packages must be installed:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Required CRAN Packages</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>tidyverse</td>
</tr>
<tr class="even">
<td>apaTables</td>
</tr>
<tr class="odd">
<td>janitor</td>
</tr>
<tr class="even">
<td>remotes</td>
</tr>
<tr class="odd">
<td>skimr</td>
</tr>
</tbody>
</table>
<p>The following GitHub packages must be installed:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Required GitHub Packages</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>dstanley4/fastInteraction</td>
</tr>
</tbody>
</table>
<p>After the remotes package is installed, it can be used to install a package from GitHub:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>remotes<span class="sc">::</span><span class="fu">install_github</span>(<span class="st">"dstanley4/fastInteraction"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Required Data</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><a href="data_mr_ex.csv">data_mr_ex.csv</a></td>
</tr>
</tbody>
</table>
<section id="overview" class="level2">
<h2 class="anchored" data-anchor-id="overview">Overview</h2>
<p>Multiple regression is a means relating multiple predictor variables to a single criterion variable. We can determine the amount of variance in the criterion accounted for by the set of predictors (<span class="math inline">\(R^2\)</span>), a single predictor on it’s own (<span class="math inline">\(r^2\)</span>), or the extent to which a single predictor accounts for unique variance account for in the criterion that is not accounted for by any of the other predictors (<span class="math inline">\(sr^2\)</span>).</p>
</section>
<section id="example" class="level2">
<h2 class="anchored" data-anchor-id="example">Example</h2>
<p>In this chapter, we examine the extent to video game scores are predicted by age and IQ for people who live in the City of Guelph. As before, we treat citizens of Guelph as our population – though in this chapter we move straight to the sample data (without showing the population-level data).</p>
<p>We are interested in using both IQ and age to predict video game scores so we refer to these variables as <strong>predictor</strong> variables. The value being predicted is video game score and we refer to that variable as the <strong>criterion</strong> (i.e., the dependent variable).</p>
<p>You can think of the multiple regression problem using a venn diagram:</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="ch_multiple_regression/images/mr_venn.png" class="img-fluid figure-img" width="968"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="load-the-data" class="level2">
<h2 class="anchored" data-anchor-id="load-the-data">Load the data</h2>
<p>We use a data set called “data_mr_ex.csv” in this example. The data can be loaded with the command:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(janitor)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>my_data <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"data_mr_ex.csv"</span>)</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a><span class="co"># ensure column names match desired naming convention</span></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>my_data <span class="ot">&lt;-</span> my_data <span class="sc">%&gt;%</span></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">clean_names</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We see the structure of the data with the glimpse() command:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(my_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 200
Columns: 3
$ video_game &lt;dbl&gt; 122.02, 108.67, 130.44, 123.38, 121.49, 125.67, 122.88, 109…
$ iq         &lt;dbl&gt; 107.6, 100.9, 89.0, 90.3, 97.1, 108.1, 120.4, 90.5, 118.9, …
$ age        &lt;dbl&gt; 41.1, 55.1, 43.9, 46.7, 42.1, 41.2, 41.7, 48.3, 48.2, 48.1,…</code></pre>
</div>
</div>
</section>
<section id="bivariate-relations" class="level2">
<h2 class="anchored" data-anchor-id="bivariate-relations">Bivariate relations</h2>
<p>When you conduct multiple regression analyses you should always report a correlation matrix with your predictors and criterion.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(apaTables)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="fu">apa.cor.table</span>(my_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>

Table 0 

Descriptive Statistics and Correlations
 

  Variable      N   M      SD    1            2           
  1. video_game 200 119.03 10.75                          
                                                          
                                                          
                                                          
  2. iq         200 102.00 15.00 .50**                    
                                 [.39, .60]               
                                 p &lt; .001                 
                                                          
  3. age        200 45.00  6.00  -.30**       -.20**      
                                 [-.42, -.17] [-.33, -.07]
                                 p &lt; .001     p = .004    
                                                          

Note. N = number of cases. M = mean. SD = standard deviation.
Values in square brackets indicate the 95% confidence interval.
 * indicates p &lt; .05. ** indicates p &lt; .01.
 </code></pre>
</div>
</div>
<p>You should always check for curvilinear relations when reporting correlations via a graph. We quickly create a graph for doing so with the code below. In this case we don’t see any curvilinear relations.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(GGally)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggpairs</span>(my_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="19-multiple_regression_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>You can think of each bivariate correlation as the shaded areas on the figure below. In this type of figure the degree of overlap between two circles is determined by the correlation squared (i.r., <span class="math inline">\(r^2\)</span>). The value you obtain for <span class="math inline">\(r^2\)</span> indicates the proportion of the criterion that is covered by the predictor. For example, if <span class="math inline">\(r\)</span> = .50 then <span class="math inline">\(r^2\)</span> = .25 which indicates 25% of the criterion should be covered by the circle representing that predictor.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="ch_multiple_regression/images/mr_venn_r.png" class="img-fluid figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="single-best-predictor" class="level2">
<h2 class="anchored" data-anchor-id="single-best-predictor">Single best predictor</h2>
<p>What is the best predictor of video_game? Many researchers incorrectly believe you need multiple regression to answer this question - you do not. To determine the single best predictor in a set of predictors just look at the correlation matrix above - no need for regression (or beta-weights). The strongest correlation is the best predictor. In our current example, video_game_score is predicted by iq (<em>r</em> = .50) and age (<em>r</em> = -.30). The best predictor of video_game_score is iq because it has the strongest correlation (using absolute values .50 is larger than .30).</p>
</section>
<section id="multiple-regression-1" class="level2">
<h2 class="anchored" data-anchor-id="multiple-regression-1">Multiple regression</h2>
<p>Multiple regression is frequently used to ask two questions:</p>
<ul>
<li><p>How well we can predict the criterion using a set of predictors (see <span class="math inline">\(R^2\)</span>)?</p></li>
<li><p>What is the unique contribution of a single variable in a set or predictors? In other words, how much does one variable predict the criterion above and beyond another variable? For example, does study time predict exam grades above and beyond iq? Or phrased differently: Does study time predict unique variance in exam grades that is not accounted for by iq? (see <span class="math inline">\(sr^2\)</span>).</p></li>
</ul>
<p>We want to use age and IQ to predict video game score (<span class="math inline">\(Y\)</span>). More specifically, we want to combine age and IQ to create a new variable (<span class="math inline">\(\widehat{Y}\)</span>) that correlates as highly as possible with video game score. We do with the code below:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>lm_object <span class="ot">&lt;-</span> <span class="fu">lm</span>(video_game <span class="sc">~</span> age <span class="sc">+</span> iq,</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>                    <span class="at">data =</span> my_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Now look at the brief output:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(lm_object)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = video_game ~ age + iq, data = my_data)

Coefficients:
(Intercept)          age           iq  
   102.2333      -0.3712       0.3285  </code></pre>
</div>
</div>
<p>This output shows you how we can combine age, IQ, and a constant to create (<span class="math inline">\(\widehat{Y}\)</span>).</p>
<p>More specifically: <span class="math inline">\(\widehat{Y} = 102.233 - 0.0371(age) + 0.328(iq)\)</span></p>
<p>The slopes for age and iq are -0.0371 and 0.328, respectively. These are also referred to as the <em>b</em>-weights or unstandardized regression coefficients. The computer picks these weight so that predicted video game scores (<span class="math inline">\(\widehat{Y}\)</span>) will corresponds as closely as possible to actual video game scores.</p>
<p>A quick way to get more comprehensive regression output is to use the <em>apa.reg.table</em> function in the apaTables package.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(apaTables)</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a><span class="fu">apa.reg.table</span>(lm_object,</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>              <span class="at">filename =</span> <span class="st">"table_regression.doc"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="ch_multiple_regression/images/mr_table.png" class="img-fluid figure-img" style="width:90.0%"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="b-weights" class="level2">
<h2 class="anchored" data-anchor-id="b-weights"><em>b</em>-weights</h2>
<p>An inspection of the <em>b</em> column in the above table reveals the <em>b</em>-weights we previously discussed. The <em>b</em>-weights are also known as the slopes or the unstandardized regression weights. The <em>b</em>-weights are used to create predicted/estimated video game score via the regression equation:</p>
<p><span class="math display">\[
\begin{aligned}
\widehat{Y} &amp;= 102.233 + 0.3285(Z) - 0.3712(X) \\
\widehat{\text{video game}} &amp;= 102.233 + 0.3285(iq) - 0.3712(age) \\
\end{aligned}
\]</span></p>
<p>You can think of the regression equation as a receipe for making <span class="math inline">\(\hat{Y}\)</span>. The variables in the regression (e.g., age and iq) are the ingredients. The <em>b</em>-weights (e.g., 0.3285 and 00.3712) are the amount of each ingredient you need to make <span class="math inline">\(\hat{Y}\)</span>.</p>
<p>As previously noted, the computer picks the <em>b</em>-weights using a process that ensures the predicted video game scores (<span class="math inline">\(\hat{Y}\)</span>) corresponds as closely as possible to actual video game scores (<span class="math inline">\(Y\)</span>). Consider the regression calculation for Person 1, below, who is 41.7 years old and has an IQ of 107.6.</p>
<p><span class="math display">\[
\begin{aligned}
\widehat{Y} &amp;= 102.233 + 0.3285(Z) - 0.3712(X) \\
\widehat{\text{video game}} &amp;= 102.233 + 0.3285(iq) - 0.3712(age) \\
&amp;= 102.233 + 0.3285(107.6) - 0.3712(41.1) \\
&amp;= 122.3
\end{aligned}
\]</span></p>
<p>The above calculation reveals an estimated video game score for Person 1 of 122.3 (i.e., <span class="math inline">\(\hat{Y} = 122.3\)</span>) – which differs only slightly from their actual video game score of 122 (i.e.. <span class="math inline">\(Y = 122\)</span>). You can see the similarity between actual video game scores (<span class="math inline">\(Y\)</span>) and predicted video game scores (<span class="math inline">\(\hat{Y}\)</span>) for the first several participants in the table below.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="ch_multiple_regression/images/mr_reg_data_figure.png" class="img-fluid figure-img" style="width:50.0%"></p>
</figure>
</div>
</div>
</div>
<p>You can interpret the <em>b</em>-weights as indicating how much the criterion changes when a predictor changes – <strong>holding the other predictors constant</strong>. In this context, a 0.3285 <em>b</em>-weight for IQ indicates that for each one-unit increase in IQ video game score will increase 0.3285 points – holding the effect of age constant. Don’t forget the <em>b</em>-weight can only be interpreting in context of that specific regression equation. If you replaced the age predictor with, say, height as a predictor, then the <em>b</em>-weight for IQ would change. Context matters when interpreting <em>b</em>-weights.</p>
</section>
<section id="r2" class="level2">
<h2 class="anchored" data-anchor-id="r2"><span class="math inline">\(R^2\)</span></h2>
<p>How effective is the set of predictors? We can calculate <span class="math inline">\(R^2\)</span> to determine the proportion of variance the criterion that is accounted for by the set of predictors. This value is illustrated graphically below:</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="ch_multiple_regression/images/mr_venn_R2.png" class="img-fluid figure-img" style="width:26.0%"></p>
</figure>
</div>
</div>
</div>
<p>You will simply obtain <span class="math inline">\(R^2\)</span> from computer output. But how is <span class="math inline">\(R^2\)</span> calculated? Understanding how <span class="math inline">\(R^2\)</span> is calculated can help you to understand how to interpret it. There are two methods for doing so - that produce the same number:</p>
<section id="method-1-ratio-approach" class="level3">
<h3 class="anchored" data-anchor-id="method-1-ratio-approach">Method 1: Ratio Approach</h3>
<p>What does the <span class="math inline">\(R^2\)</span> mean? It is the proportion variability in criterion scores (<span class="math inline">\(Y\)</span>) accounted for by (<span class="math inline">\(\widehat{Y}\)</span>). In other words, it is the proportion of the variability in criterion scores that can be accounted for by (a linear combination of) iq and age.</p>
<p>We begin by obtaining predicted video game scores (<span class="math inline">\(\widehat{Y}\)</span>) using the regression:</p>
<p><span class="math inline">\(\widehat{Y} = 102.233 + 0.3285(iq) - 0.3712(age)\)</span></p>
<p>predicted_video_game_scores <span class="math inline">\(= 102.233 + 0.3285(iq) - 0.3712(age)\)</span></p>
<p>The code below uses the above equation to calculate predicted video game score for each person:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>predicted_video_game_scores  <span class="ot">&lt;-</span> <span class="fu">predict</span>(lm_object)</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>actual_video_game_scores <span class="ot">&lt;-</span> my_data<span class="sc">$</span>video_game</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Recall the formula for <span class="math inline">\(R^2\)</span>:</p>
<p><span class="math display">\[
\begin{aligned}
R^2 = \frac{\text{Variance of predicted scores}}{\text{Variance of actual scores}}
\end{aligned}
\]</span></p>
<p>We implement this formula using the code below:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>var_predicted_video_game_scores <span class="ot">&lt;-</span> <span class="fu">var</span>(predicted_video_game_scores ) </span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>var_actual_video_game_scores   <span class="ot">&lt;-</span>  <span class="fu">var</span>(actual_video_game_scores)</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>R2 <span class="ot">&lt;-</span> var_predicted_video_game_scores <span class="sc">/</span> var_actual_video_game_scores</span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(R2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.2911182</code></pre>
</div>
</div>
<p>Thus, 29% of the variability in video game scores is predicted by the combination of age and IQ.</p>
</section>
<section id="method-2-correlation-approach" class="level3">
<h3 class="anchored" data-anchor-id="method-2-correlation-approach">Method 2: Correlation Approach</h3>
<p>An alternative way of thinking about <span class="math inline">\(R^2\)</span> is as the squared correlation between predicted criterion scores and actual criterion scores:</p>
<p><span class="math display">\[
\begin{aligned}
R^2 &amp;= r^2_{\hat{Y}, Y}\\
&amp;= r^2_{(predicted_video_game_scores, actual_video_game_scores)}\\
\end{aligned}
\]</span></p>
<p>We implement this formula with the code below and obtain the same value:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>R <span class="ot">&lt;-</span> <span class="fu">cor</span>(predicted_video_game_scores, actual_video_game_scores)</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>R2 <span class="ot">&lt;-</span> R <span class="sc">*</span> R</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(R2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.2911182</code></pre>
</div>
</div>
</section>
<section id="r2-in-practice" class="level3">
<h3 class="anchored" data-anchor-id="r2-in-practice"><span class="math inline">\(R^2\)</span> in practice</h3>
<p>In practice we simply look at the apa.reg.table() output and obtain the <span class="math inline">\(R^2\)</span> value and 95% CI from this output:</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="ch_multiple_regression/images/mr_table.png" class="img-fluid figure-img" style="width:90.0%"></p>
</figure>
</div>
</div>
</div>
<p>From this table we determine: <span class="math inline">\(R^2\)</span> = .29, 95% CI [.19, .38]. to obtain the required <em>p</em>-value we use the summary() command on the previously calculated lm_object:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lm_object)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = video_game ~ age + iq, data = my_data)

Residuals:
     Min       1Q   Median       3Q      Max 
-26.6583  -5.4797   0.6023   6.3278  20.5394 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 102.23331    7.33860  13.931  &lt; 2e-16 ***
age          -0.37115    0.10983  -3.379 0.000876 ***
iq            0.32846    0.04391   7.480  2.4e-12 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 9.101 on 197 degrees of freedom
Multiple R-squared:  0.2911,    Adjusted R-squared:  0.2839 
F-statistic: 40.45 on 2 and 197 DF,  p-value: 1.912e-15</code></pre>
</div>
</div>
<p>At the bottom of this output we see that the <em>p</em>-value is 1.912e-15 or 0.000000000000001912. Consequently, we report the <span class="math inline">\(R^2\)</span> value as: <span class="math inline">\(R^2\)</span> = .29, 95% CI [.19, .38], <span class="math inline">\(p\)</span> &lt; .001. Thus, 29% of the variability in video game scores is predicted by the combination of age and IQ.</p>
</section>
</section>
<section id="semi-partial-sr" class="level2">
<h2 class="anchored" data-anchor-id="semi-partial-sr">Semi-partial (<span class="math inline">\(sr\)</span>)</h2>
<p>A semi-partial correlation is represented by the symbol <span class="math inline">\(sr\)</span> and correspondingly a squared semi-partial correlation is represented by the symbol <span class="math inline">\(sr^2\)</span>. What is a squared semi-partial correlation and why is it useful?</p>
<p>Semi-partial correlations are a way of determining the unique contribution of a variable to predicting the criterion (in the context of the other predictors). The semi-partial correlation is the correlation of one predictor (with all the other predictors removed) with the criterion. The semi-partial correlation squared is the amount <span class="math inline">\(R^2\)</span> would drop by if that variable was removed from the regression. It is the percentage of variability in criterion scores that is uniquely accounted for by a predictor. This is illustrated in the venn diagram below:</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="ch_multiple_regression/images/mr_venn_sr.png" class="img-fluid figure-img" style="width:63.0%"></p>
</figure>
</div>
</div>
</div>
<section id="sr2-in-theory" class="level3">
<h3 class="anchored" data-anchor-id="sr2-in-theory"><span class="math inline">\(sr^2\)</span> in theory</h3>
<p>In the text below we go “inside the black box” to show you how semi-partial correlations are computed. In practice, they are just displayed in R output - but understanding the text below where we calculate them “old school” will help with you interpret <span class="math inline">\(sr^2\)</span>.</p>
<p>Overall, squared semi-partial correlations provide an index of how much that predictor contributes to the overall <span class="math inline">\(R^2\)</span> (with the effect of the other predictors removed). We calculate <span class="math inline">\(sr^2\)</span> for IQ (removing the effect of age) to demonstrate this fact. We do this with a regression equation in which <strong>we make IQ the criterion (<span class="math inline">\(Y\)</span>)</strong>. Then we predict IQ with age. This produces my_iq_regression which has inside of it a predictor version of IQ, <span class="math inline">\(\widehat{Y_{iq}}\)</span>, which in this case represents a best guess of IQ based on age.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>my_iq_regression <span class="ot">&lt;-</span> <span class="fu">lm</span>(iq <span class="sc">~</span> age, <span class="at">data =</span> my_data)</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(my_iq_regression)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = iq ~ age, data = my_data)

Coefficients:
(Intercept)          age  
   124.7626      -0.5059  </code></pre>
</div>
</div>
<p>. Thus, we find: <span class="math inline">\(\widehat{Y_{iq}} = 124.763 - 0.506(age)\)</span></p>
<p>Consequently, when you see <span class="math inline">\(\widehat{Y_{iq}}\)</span> recognize that it is really just an estimate of IQ <strong>created entirely from age</strong>. In contrast, <span class="math inline">\(Y_{iq}\)</span> is the actual IQ score we obtained from participants.</p>
<p>We want IQ with the effect of age removed. Therefore, we want IQ (i.e., <span class="math inline">\(Y_{iq}\)</span>) with the effect of age (i.e.,<span class="math inline">\(\widehat{Y_{iq}}\)</span> ) removed.</p>
<p>Thus we want: residual = <span class="math inline">\(Y_{iq}\)</span> - <span class="math inline">\(\widehat{Y_{iq}}\)</span></p>
<p>or another way of thinking of it is:</p>
<p>iq_without_age = <span class="math inline">\(Y_{iq}\)</span> - <span class="math inline">\(\widehat{Y_{iq}}\)</span></p>
<p>iq_without_age = iq - (124.763 - 0.506(age) )</p>
<p>We do this below:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>iq_without_age <span class="ot">&lt;-</span> <span class="fu">resid</span>(my_iq_regression) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Then we correlate IQ without age (i.e., iq_without_age) with video game scores (i.e., video_game). This tells us how IQ correlates with video game scores when the effects of age have been removed from IQ; that is, the semi-partial correlation (i.e., <span class="math inline">\(sr\)</span>). Once again refer to the venn diagram above illustrating <span class="math inline">\(sr^2\)</span>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co"># apa.reg.table does this for you - this is for learning/illustration only.</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>sr  <span class="ot">&lt;-</span> <span class="fu">cor</span>(iq_without_age, my_data<span class="sc">$</span>video_game)</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>sr2 <span class="ot">&lt;-</span> sr <span class="sc">*</span> sr</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="sr2-in-practice" class="level3">
<h3 class="anchored" data-anchor-id="sr2-in-practice"><span class="math inline">\(sr^2\)</span> in practice</h3>
<p>The <span class="math inline">\(sr^2\)</span> values with confidence intervals are reported in apa.reg.table() output:</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="ch_multiple_regression/images/mr_table.png" class="img-fluid figure-img" style="width:90.0%"></p>
</figure>
</div>
</div>
</div>
<p>From this table we determine:</p>
<ul>
<li><p>age: <span class="math inline">\(sr^2\)</span> = .04 , 95% CI [-.01, .09]</p></li>
<li><p>iq: <span class="math inline">\(sr^2\)</span> = .20, 95% CI [.11, .30]</p></li>
</ul>
<p>However, to obtain the <em>p</em>-value for each <span class="math inline">\(sr^2\)</span> value we need to use the summary() command:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lm_object)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = video_game ~ age + iq, data = my_data)

Residuals:
     Min       1Q   Median       3Q      Max 
-26.6583  -5.4797   0.6023   6.3278  20.5394 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 102.23331    7.33860  13.931  &lt; 2e-16 ***
age          -0.37115    0.10983  -3.379 0.000876 ***
iq            0.32846    0.04391   7.480  2.4e-12 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 9.101 on 197 degrees of freedom
Multiple R-squared:  0.2911,    Adjusted R-squared:  0.2839 
F-statistic: 40.45 on 2 and 197 DF,  p-value: 1.912e-15</code></pre>
</div>
</div>
<p>The <em>p</em>-value for the <em>b</em>-weight (i.e.&nbsp;Estimate) is the <em>p</em>-value for <span class="math inline">\(sr^2\)</span>, Therefore, we simply look in the Pr(&gt;|t|) column to obtain the required <em>p</em>-value. Adding this value to our reporting, we find:</p>
<ul>
<li><p>age: <span class="math inline">\(sr^2\)</span> = .04 , 95% CI [-.01, .09], <em>p</em> &lt; .001</p></li>
<li><p>iq: <span class="math inline">\(sr^2\)</span> = .20, 95% CI [.11, .30], <em>p</em> &lt; .001</p></li>
</ul>
<p>If a predictor is significant, this indicates that the predictor contributes unique variance to <span class="math inline">\(\widehat{Y_{video game}}\)</span> that can not be contributed by any of the other predictors. The amount of unique variance contributed by a predictor is indicated by <span class="math inline">\(sr^2\)</span> (semi-partial correlation squared).</p>
</section>
<section id="blocks-regression" class="level3">
<h3 class="anchored" data-anchor-id="blocks-regression">Blocks regression</h3>
<p>Some researchers are unfamiliar with semi-partial correlations and prefer to think in term of how the <span class="math inline">\(R^2\)</span> value changes over two different regression. This approach is just an indirect way of calculating <span class="math inline">\(sr^2\)</span>.</p>
<p>Consider the example below where the researcher conducts the first regression, block 1, in which age is the predictor. Then he conducts a second regression, block 2, in which both age and iq are the predictors.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co"># apa.reg.table does this for you - this is for learning/illustration only.</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>block1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(video_game <span class="sc">~</span> age,</span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>             <span class="at">data =</span> my_data)</span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a>block2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(video_game <span class="sc">~</span> age <span class="sc">+</span> iq,</span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a>             <span class="at">data =</span> my_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The goal is to examine the <span class="math inline">\(R^2\)</span> when only age is the predictor and see how much it increases when you have both age and iq as predictors. The resulting difference, <span class="math inline">\(\Delta R^2\)</span> tells you how much iq predicted video game score beyond age alone. Examine the output below.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">apa.reg.table</span>(block1, block2,</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>              <span class="at">filename =</span> <span class="st">"table_mr_blocks.doc"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="ch_multiple_regression/images/mr_table_blocks.png" class="img-fluid figure-img" style="width:90.0%"></p>
</figure>
</div>
</div>
</div>
<p>This table illustrates that for the first regression when just age was a predictor that <span class="math inline">\(R^2\)</span> = .09. When both age and iq were predictors <span class="math inline">\(R^2\)</span> = .29. That indicates that <span class="math inline">\(R^2\)</span> increased by .20 when we added iq as a predictor. Thus, <span class="math inline">\(\Delta R^2\)</span> = .20. This is the amount <span class="math inline">\(R^2\)</span> increased by due to adding iq as predictor. Conceptually, and mathematically, this is identical to the <span class="math inline">\(sr^2\)</span> value for iq. Indeed, if you look at this output in detail you see that for iq <span class="math inline">\(sr^2\)</span> = .20.</p>
</section>
</section>
<section id="beta-weights" class="level2">
<h2 class="anchored" data-anchor-id="beta-weights">Beta-weights</h2>
<p><em>Beta-weights</em> are often referred to as <em>standardized regression weights</em>. This is a poor description that makes beta weights hard to understand. A better description of <em>beta-weights</em> is the regression weights for standardized variables; that is variables with a mean of 0 and a standard deviation of 1.0.</p>
<section id="in-practice" class="level3">
<h3 class="anchored" data-anchor-id="in-practice">In practice</h3>
<p>Recall we ran a regression with the command below. This command used the original/raw form of the variables.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>lm_object <span class="ot">&lt;-</span> <span class="fu">lm</span>(video_game <span class="sc">~</span> age <span class="sc">+</span> iq,</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>                    <span class="at">data =</span> my_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>From lm_object created we used apa.reg.table() to obtain this output:</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="ch_multiple_regression/images/mr_table.png" class="img-fluid figure-img" style="width:90.0%"></p>
</figure>
</div>
</div>
</div>
<p>Notice the beta column in this output. It reports beta weights of -.21 and .46 for age and iq, respectively. Where did these values come from?</p>
<p>To answer this question, we need to start with the lm_object. The apa.reg.table() command just formats the information contained in the lm_object. We can see an unformatted version of this information with the summary() command:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lm_object)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = video_game ~ age + iq, data = my_data)

Residuals:
     Min       1Q   Median       3Q      Max 
-26.6583  -5.4797   0.6023   6.3278  20.5394 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 102.23331    7.33860  13.931  &lt; 2e-16 ***
age          -0.37115    0.10983  -3.379 0.000876 ***
iq            0.32846    0.04391   7.480  2.4e-12 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 9.101 on 197 degrees of freedom
Multiple R-squared:  0.2911,    Adjusted R-squared:  0.2839 
F-statistic: 40.45 on 2 and 197 DF,  p-value: 1.912e-15</code></pre>
</div>
</div>
<p>Notice that the values in the Estimates column correspond to the b-weights column in the apa.reg.table() output. We will use this fact to create beta-weights.</p>
</section>
<section id="old-school" class="level3">
<h3 class="anchored" data-anchor-id="old-school">Old school</h3>
<p>To obtain beta-weights there are two steps. First, we create standardized score versions of each column. Second, we run a normal regression using those columns.</p>
<p>A set of standardized scores have a mean of 0 and a standard deviation of 1.0. To create the standardized score versions of each column in the regression we use the z-score formula:</p>
<p><span class="math display">\[
\begin{aligned}
\text{standardized scores}=z_{X} = \frac{X-\bar{X}}{\sigma_X}
\end{aligned}
\]</span></p>
<p>Consider the age column. We can calculate the mean for this column, mean(age), and the standard deviation for this column, sd(age). Then for every value in the age column we subtract the column mean and then divide by the column standard deviation. We do so with the calculation: (age-mean(age))/sd(age). The code below creates standardized score versions of the iq, age, and video_game columns called z_iq, z_age, and z_video_game, respectively.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>my_data <span class="ot">&lt;-</span> my_data <span class="sc">%&gt;%</span> </span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">z_iq =</span> (iq<span class="sc">-</span><span class="fu">mean</span>(iq))<span class="sc">/</span><span class="fu">sd</span>(iq),</span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">z_age =</span> (age<span class="sc">-</span><span class="fu">mean</span>(age))<span class="sc">/</span><span class="fu">sd</span>(age),</span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">z_video_game =</span> (video_game<span class="sc">-</span><span class="fu">mean</span>(video_game))<span class="sc">/</span><span class="fu">sd</span>(video_game))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We can confirm a mean of 0 and a standard deviation of 1.0 for these new columns with the skim command:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(skimr)</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a><span class="fu">skim</span>(my_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Now we conduct the regression again with standardized variables (i.e., z-score versions).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>lm_object_zscores <span class="ot">&lt;-</span> <span class="fu">lm</span>(z_video_game <span class="sc">~</span> z_iq <span class="sc">+</span> z_age,</span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>                        <span class="at">data =</span> my_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We can obtain the regression weights for analysis using these standardized scores with the summary() command:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lm_object_zscores) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = z_video_game ~ z_iq + z_age, data = my_data)

Residuals:
    Min      1Q  Median      3Q     Max 
-2.4788 -0.5095  0.0560  0.5884  1.9098 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  3.732e-16  5.984e-02   0.000 1.000000    
z_iq         4.582e-01  6.125e-02   7.480  2.4e-12 ***
z_age       -2.070e-01  6.125e-02  -3.379 0.000876 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.8462 on 197 degrees of freedom
Multiple R-squared:  0.2911,    Adjusted R-squared:  0.2839 
F-statistic: 40.45 on 2 and 197 DF,  p-value: 1.912e-15</code></pre>
</div>
</div>
<p>Notice that the estimates above are 4.582e-01 -2.070e-01 which are, in decimal form, .46 and -.21, respectively. These are the beta-weights from the apa.reg.table on the previous page. Thus, when you conduct a normal regression <strong>but used standardized variables in it</strong> you obtain beta-weights.</p>
<p><em>Interpretation</em>. The typically reported <strong>b-weights</strong> describe how a 1 unit change in IQ influences video_game points. Similarly, <strong>beta-weights</strong>, describe how a 1 unit change in z_iq influences z_video_game. Keep in mind, however, that 1 unit of z_iq (and z_video_game) is 1 standard deviation. As a result, a beta-weight indicates how much the criterion scores will change in SD units when a predictor increases by 1 SD – holding the effect of the other predictors constant. Similar to b-weights, beta-weights can only be interpreted in the context of the other variables in the equation.</p>
<p>Hopefully, this description has made it clear that although beta-weights are often referred to as <em>standardized regression weights</em>; it would be more accurate to describe them as the <strong>weights for standardized variables</strong>.</p>
</section>
</section>
<section id="graphing" class="level2">
<h2 class="anchored" data-anchor-id="graphing">Graphing</h2>
<p>Let’s take a minute to consider the nature of the data we have so far - examine the first few rows of the data below (that includes the predicted value for each person).</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="ch_multiple_regression/images/mr_reg_data_figure.png" class="img-fluid figure-img" style="width:50.0%"></p>
</figure>
</div>
</div>
</div>
<p>You can see that each person has three measured variables associated with them: video_game_score, iq, and age. These columns are in blue to indicate the fact they are measured variables. Because we have three measured variables we can’t create a typical 2D scatter plot. That type of plot only work when there is one predictor and one criterion. Now we have two predictors and one criterion. Consequently, we need make a 3D scatter plot.</p>
<p>Correspondingly, because we have two predictors, we can’t obtain a regression line (i.e., best-fit line). A regression line is only possible when there is one predictor. Now we have two predictors. Consequently, a regression surface is required to show the predicted values for combinations of age and iq. In this case, when there are two predictor variables, the regression surface is a plane.</p>
<p>Let’s create the 3D scatter plot with a regression surface. You recall we previously created the lm_object when we ran our regression:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>lm_object <span class="ot">&lt;-</span> <span class="fu">lm</span>(video_game <span class="sc">~</span> age <span class="sc">+</span> iq,</span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>                    <span class="at">data =</span> my_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The lm_object has the three data point for each person (age, iq, video_game) embedded inside it. So we can use the lm_object to create the scatter plot with regression plane. We do so using the fastInteraction package. More specifically, we use the fast.plot command as illustrated below.Note: The fast.plot command uses the argument “moderator” which is not appropriate in our context. When you see moderator in the command below just think of it as another predictor.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(fastInteraction)</span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>surface_plot <span class="ot">&lt;-</span> <span class="fu">fast.plot</span>(lm_object,</span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a>                          <span class="at">criterion =</span> video_game,</span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a>                          <span class="at">predictor =</span> iq,</span>
<span id="cb36-6"><a href="#cb36-6" aria-hidden="true" tabindex="-1"></a>                          <span class="at">moderator =</span> age)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Then just type:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>surface_plot</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>You can see the graph below:</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="ch_multiple_regression/images/mr_3d_snapshot.png" class="img-fluid figure-img" style="width:90.0%"></p>
</figure>
</div>
</div>
</div>
<p>All of the predicted scores fall on the regression surface. You can think of the regression surface as a best-fit plane. In some sense you can think of the plane as a collection of best-fit lines. Indeed, two illustrative best-fit lines are place on this surface. For all the best-fit lines on the plane the slopes are the same - just the intercepts differ. You can see the people relative to the predicted surface/plane by looking at the dots. Each dot represents a person.</p>
<p>Try the interactive version of the graph below. Caveat, sometimes it doesn’t appear correctly on the web. If the graph appears incorrectly (e.g., no data points or no surface) try using the Chrome browser. Safari sometimes has problems with this web object. You can rotate the graph to see a better view of the surface. The graph illustrates that predicted video game scores (i.e., the surface) change as a function of both age and iq.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>surface_plot</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="plotly html-widget html-fill-item" id="htmlwidget-6c132fc6ebf2cf386882" style="width:100%;height:464px;"></div>
<script type="application/json" data-for="htmlwidget-6c132fc6ebf2cf386882">{"x":{"visdat":{"5c9b4c7b548":["function () ","plotlyVisDat"]},"cur_data":"5c9b4c7b548","attrs":{"5c9b4c7b548":{"alpha_stroke":1,"sizes":[10,100],"spans":[1,20],"z":[[113.63189268073864,118.55924860220368,123.48660452366872,128.41396044513377,133.34131636659879],[111.40588791890427,116.33324384036931,121.26059976183434,126.18795568329939,131.11531160476443],[109.17988315706991,114.10723907853495,119.03459499999998,123.96195092146503,128.88930684293007],[106.95387839523553,111.88123431670057,116.80859023816561,121.73594615963066,126.66330208109569],[104.72787363340117,109.65522955486621,114.58258547633125,119.5099413977963,124.43729731926133]],"type":"surface","x":[72,87,102,117,132],"y":[33,39,45,51,57],"opacity":0.90000000000000002,"colors":["#d1d1d1","#555555"],"inherit":true},"5c9b4c7b548.1":{"alpha_stroke":1,"sizes":[10,100],"spans":[1,20],"x":[107.59999999999999,100.90000000000001,89,90.299999999999997,97.099999999999994,108.09999999999999,120.40000000000001,90.5,118.90000000000001,107.90000000000001,114.59999999999999,117.8,85.799999999999997,77.299999999999997,98.700000000000003,104.40000000000001,96.599999999999994,92.400000000000006,110.40000000000001,84.700000000000003,86.599999999999994,112.8,113,99.5,98.700000000000003,100.2,126.8,109,125.8,95.599999999999994,113,88.400000000000006,103.09999999999999,104.7,67.099999999999994,80.799999999999997,81.900000000000006,83.299999999999997,119.40000000000001,107.8,105.09999999999999,117.59999999999999,90.200000000000003,107.7,93.099999999999994,111.09999999999999,101.09999999999999,138.59999999999999,97.099999999999994,111,95.400000000000006,73.299999999999997,90.200000000000003,114.5,98.5,84.5,109.90000000000001,87.400000000000006,106.40000000000001,118.90000000000001,101.3,114.40000000000001,82.200000000000003,102.90000000000001,84.099999999999994,78.400000000000006,97.700000000000003,98.099999999999994,116.2,111.90000000000001,99.700000000000003,122.7,121.8,98.700000000000003,112.5,100.5,77.5,120.59999999999999,93,93.299999999999997,112.2,102.8,103.3,120.90000000000001,124.7,101.40000000000001,101.3,93.599999999999994,115.3,95.400000000000006,93.299999999999997,90.299999999999997,119.09999999999999,110.59999999999999,126.90000000000001,93.099999999999994,71.599999999999994,82.200000000000003,97.400000000000006,95.700000000000003,101.8,107.3,108.3,111.90000000000001,110.90000000000001,102.90000000000001,107.40000000000001,142.69999999999999,92.5,80.299999999999997,93.400000000000006,85.700000000000003,94.900000000000006,108.09999999999999,81.900000000000006,105.90000000000001,97.5,109.8,132.80000000000001,126.40000000000001,75.799999999999997,65.400000000000006,116.2,73.900000000000006,105.7,106.09999999999999,126.3,99.900000000000006,77.700000000000003,115,100.7,93.5,91.599999999999994,73.299999999999997,106.59999999999999,78.700000000000003,105.40000000000001,130.5,76,103.90000000000001,103.7,96,118.2,103.5,114.40000000000001,124.09999999999999,95.400000000000006,92.700000000000003,92.900000000000006,99.200000000000003,103.3,99.099999999999994,109.90000000000001,83.400000000000006,133.69999999999999,89.799999999999997,116.90000000000001,99.5,105.7,108.7,92.599999999999994,95.099999999999994,142.80000000000001,108.8,102.59999999999999,114,95.299999999999997,103.7,120.09999999999999,78.799999999999997,104.90000000000001,124.59999999999999,96.299999999999997,126.3,107.2,77.400000000000006,68.799999999999997,100.40000000000001,97.5,115.2,127.90000000000001,101.90000000000001,101.8,82.5,83.099999999999994,106,117.3,108.5,78.799999999999997,104.8,88,90.299999999999997,109.90000000000001,95.599999999999994,100.5,113.09999999999999,91,115.09999999999999,111,124.59999999999999],"y":[41.100000000000001,55.100000000000001,43.899999999999999,46.700000000000003,42.100000000000001,41.200000000000003,41.700000000000003,48.299999999999997,48.200000000000003,48.100000000000001,40.600000000000001,51.899999999999999,47.299999999999997,43.799999999999997,49.5,43.899999999999999,45.200000000000003,50.299999999999997,40.700000000000003,46.5,48.799999999999997,45.600000000000001,41.799999999999997,55.399999999999999,49.5,48.399999999999999,49.899999999999999,40.299999999999997,49.100000000000001,40.600000000000001,38.200000000000003,47.700000000000003,44.700000000000003,42.200000000000003,45.899999999999999,42,51.600000000000001,43.799999999999997,50.899999999999999,52.600000000000001,38.600000000000001,43.100000000000001,41.299999999999997,46.600000000000001,49.899999999999999,64.799999999999997,41.100000000000001,43.100000000000001,45.399999999999999,42.100000000000001,53.899999999999999,48.700000000000003,37.5,40.299999999999997,52.399999999999999,57.399999999999999,44,47.399999999999999,35,43.299999999999997,49,45.799999999999997,52.200000000000003,50.399999999999999,47.399999999999999,54.5,45.100000000000001,51.799999999999997,46,45.899999999999999,46.200000000000003,45.299999999999997,35.600000000000001,42.200000000000003,43.700000000000003,54.600000000000001,56.200000000000003,53.899999999999999,29.699999999999999,39.100000000000001,41.299999999999997,48.899999999999999,50.299999999999997,39.100000000000001,33.899999999999999,53.600000000000001,48.299999999999997,46.200000000000003,53.600000000000001,42.700000000000003,46.899999999999999,37.200000000000003,44.799999999999997,40.600000000000001,51,48.200000000000003,55.700000000000003,41.200000000000003,41.100000000000001,52.100000000000001,41.899999999999999,49.100000000000001,43.100000000000001,36.399999999999999,42.200000000000003,51.600000000000001,48.5,45.299999999999997,44,48.399999999999999,41.799999999999997,37.5,46.200000000000003,43.799999999999997,60.899999999999999,49.799999999999997,54.700000000000003,47.399999999999999,40.299999999999997,34.299999999999997,36.100000000000001,46,46,40.399999999999999,41.100000000000001,39.399999999999999,41.799999999999997,53.200000000000003,45.399999999999999,42.899999999999999,50,50.600000000000001,37.700000000000003,51.700000000000003,51.5,44.299999999999997,29,42.200000000000003,47.299999999999997,49,37.600000000000001,44.200000000000003,41.200000000000003,48.5,40.100000000000001,39.399999999999999,51.899999999999999,43.600000000000001,45.799999999999997,43.700000000000003,44.299999999999997,45,51.799999999999997,49.700000000000003,36.700000000000003,35.700000000000003,50.899999999999999,29.899999999999999,35.600000000000001,45.200000000000003,47.100000000000001,48.700000000000003,37,50,45.700000000000003,38.899999999999999,42.399999999999999,41.299999999999997,42.100000000000001,46.899999999999999,50.100000000000001,39.600000000000001,49.799999999999997,37.899999999999999,39.399999999999999,44.5,45,41.799999999999997,27.800000000000001,43.200000000000003,48.799999999999997,31.800000000000001,41.600000000000001,47.399999999999999,31.5,37.899999999999999,41.100000000000001,47.399999999999999,52.100000000000001,53.899999999999999,47.899999999999999,51,41.899999999999999,48.200000000000003,36.100000000000001,36.299999999999997,46.700000000000003,45,38.200000000000003,49.700000000000003],"z":[122.02,108.67,130.44,123.38,121.48999999999999,125.67,122.88,109.64,118.20999999999999,118.39,114.15000000000001,138.5,110.37,114.68000000000001,112.17,107.08,117.89,116.98999999999999,136.83000000000001,117.26000000000001,108.29000000000001,137.63999999999999,133.58000000000001,117.47,103.43000000000001,115.11,118.28,123.04000000000001,117.13,124.88,124.31,106.23999999999999,109.56999999999999,111.84999999999999,114.41,116.47,120.14,86.679000000000002,114.97,133.66999999999999,108.27,130.27000000000001,123.84999999999999,119.68000000000001,122.01000000000001,102.78,119.06999999999999,137.63999999999999,121.08,120.45999999999999,111.92,119.66,122.56,124.69,115.90000000000001,117.40000000000001,142.25999999999999,95.158000000000001,144.52000000000001,123.70999999999999,131,101.69,113.51000000000001,116.94,124.65000000000001,101.63,125.19,106.66,120.73,127.18000000000001,123.59999999999999,131.91,131.06999999999999,112.84,122.83,109.61,105.45999999999999,130.16999999999999,120,119.40000000000001,130.02000000000001,126.54000000000001,123.84999999999999,133.75,130.22999999999999,122.64,112.41,112.83,133.11000000000001,102.27,119.73,98.563000000000002,131.22999999999999,129.47999999999999,120.01000000000001,119.22,92.650999999999996,126.39,95.882999999999996,94.488,120.88,109.56999999999999,124.53,127.45,129.44,112.40000000000001,124.94,121.11,129.09,125.90000000000001,129.88,118.55,118.38,131.09,96.640000000000001,114.45,106.02,115.79000000000001,127.14,129.08000000000001,108.84,114.81999999999999,121.51000000000001,116.79000000000001,123.31999999999999,124.40000000000001,109.77,118.05,96.546999999999997,132.59999999999999,113.08,106.76000000000001,117.20999999999999,104.28,119.77,113.83,143.96000000000001,132.52000000000001,92.534000000000006,124.84999999999999,104.62,117.19,121.81,128.22999999999999,117,137.34,114.70999999999999,123.59999999999999,127.31,120.94,129.69,123.56,111.37,100.14,140.44,113.34999999999999,121.14,126.19,121.25,110.05,114.86,118.63,136.27000000000001,110.53,128.63,123.39,117.43000000000001,108.37,116.87,119.05,103.84,122.11,110.95,118.95999999999999,123.7,110.05,116.83,123.84999999999999,99.805999999999997,131.40000000000001,146.66999999999999,130.55000000000001,116.53,124.70999999999999,108.59999999999999,140.66,130.34999999999999,128.66,110.37,123.52,113.86,116.56999999999999,113.73,108.72,110,117.69,101.31,126.68000000000001,118.7,127.69],"type":"scatter3d","mode":"markers","color":"black","size":5,"name":"Data points","inherit":true},"5c9b4c7b548.2":{"alpha_stroke":1,"sizes":[10,100],"spans":[1,20],"x":[71.996327655166724,86.997913827583361,101.9995,117.00108617241665,132.00267234483329],"y":[39.000421259060545,39.000421259060545,39.000421259060545,39.000421259060545,39.000421259060545],"z":[111.40588791890427,116.33324384036931,121.26059976183434,126.18795568329939,131.11531160476443],"type":"scatter3d","mode":"lines","line":{"color":"black","width":10,"dash":"dash"},"name":"-1 SD line","inherit":true},"5c9b4c7b548.3":{"alpha_stroke":1,"sizes":[10,100],"spans":[1,20],"x":[71.996327655166724,86.997913827583361,101.9995,117.00108617241665,132.00267234483329],"y":[50.99557874093945,50.99557874093945,50.99557874093945,50.99557874093945,50.99557874093945],"z":[106.95387839523553,111.88123431670057,116.80859023816561,121.73594615963066,126.66330208109569],"type":"scatter3d","mode":"lines","line":{"color":"black","width":10,"dash":"dash"},"name":"+1 SD line","inherit":true}},"layout":{"margin":{"b":40,"l":60,"t":25,"r":10},"scene":{"xaxis":{"title":"iq","range":[72,132],"ticktype":"array","tickvals":[72,87,102,117,132]},"yaxis":{"title":"age","range":[33,57],"ticktype":"array","tickvals":[33,39,45,51,57]},"zaxis":{"title":"video_game"},"aspectmode":"cube","aspectratio":{"x":1,"y":1,"z":0.94999999999999996},"showlegend":true},"hovermode":"closest","showlegend":true,"legend":{"yanchor":"top","y":0.5}},"source":"A","config":{"modeBarButtonsToAdd":["hoverclosest","hovercompare"],"showSendToCloud":false},"data":[{"colorbar":{"title":"","ticklen":2,"len":0.5,"lenmode":"fraction","y":1,"yanchor":"top"},"colorscale":[["0","rgba(209,209,209,1)"],["0.0416666666666667","rgba(203,203,203,1)"],["0.0833333333333334","rgba(198,198,198,1)"],["0.125","rgba(192,192,192,1)"],["0.166666666666667","rgba(187,187,187,1)"],["0.208333333333334","rgba(182,182,182,1)"],["0.25","rgba(176,176,176,1)"],["0.291666666666667","rgba(171,171,171,1)"],["0.333333333333333","rgba(166,166,166,1)"],["0.375","rgba(160,160,160,1)"],["0.416666666666667","rgba(155,155,155,1)"],["0.458333333333333","rgba(150,150,150,1)"],["0.5","rgba(145,145,145,1)"],["0.541666666666667","rgba(139,139,139,1)"],["0.583333333333333","rgba(134,134,134,1)"],["0.625","rgba(129,129,129,1)"],["0.666666666666667","rgba(124,124,124,1)"],["0.708333333333334","rgba(119,119,119,1)"],["0.75","rgba(114,114,114,1)"],["0.791666666666666","rgba(109,109,109,1)"],["0.833333333333333","rgba(104,104,104,1)"],["0.875","rgba(99,99,99,1)"],["0.916666666666667","rgba(95,95,95,1)"],["0.958333333333333","rgba(90,90,90,1)"],["1","rgba(85,85,85,1)"]],"showscale":true,"z":[[113.63189268073864,118.55924860220368,123.48660452366872,128.41396044513377,133.34131636659879],[111.40588791890427,116.33324384036931,121.26059976183434,126.18795568329939,131.11531160476443],[109.17988315706991,114.10723907853495,119.03459499999998,123.96195092146503,128.88930684293007],[106.95387839523553,111.88123431670057,116.80859023816561,121.73594615963066,126.66330208109569],[104.72787363340117,109.65522955486621,114.58258547633125,119.5099413977963,124.43729731926133]],"type":"surface","x":[72,87,102,117,132],"y":[33,39,45,51,57],"opacity":0.90000000000000002,"frame":null},{"x":[107.59999999999999,100.90000000000001,89,90.299999999999997,97.099999999999994,108.09999999999999,120.40000000000001,90.5,118.90000000000001,107.90000000000001,114.59999999999999,117.8,85.799999999999997,77.299999999999997,98.700000000000003,104.40000000000001,96.599999999999994,92.400000000000006,110.40000000000001,84.700000000000003,86.599999999999994,112.8,113,99.5,98.700000000000003,100.2,126.8,109,125.8,95.599999999999994,113,88.400000000000006,103.09999999999999,104.7,67.099999999999994,80.799999999999997,81.900000000000006,83.299999999999997,119.40000000000001,107.8,105.09999999999999,117.59999999999999,90.200000000000003,107.7,93.099999999999994,111.09999999999999,101.09999999999999,138.59999999999999,97.099999999999994,111,95.400000000000006,73.299999999999997,90.200000000000003,114.5,98.5,84.5,109.90000000000001,87.400000000000006,106.40000000000001,118.90000000000001,101.3,114.40000000000001,82.200000000000003,102.90000000000001,84.099999999999994,78.400000000000006,97.700000000000003,98.099999999999994,116.2,111.90000000000001,99.700000000000003,122.7,121.8,98.700000000000003,112.5,100.5,77.5,120.59999999999999,93,93.299999999999997,112.2,102.8,103.3,120.90000000000001,124.7,101.40000000000001,101.3,93.599999999999994,115.3,95.400000000000006,93.299999999999997,90.299999999999997,119.09999999999999,110.59999999999999,126.90000000000001,93.099999999999994,71.599999999999994,82.200000000000003,97.400000000000006,95.700000000000003,101.8,107.3,108.3,111.90000000000001,110.90000000000001,102.90000000000001,107.40000000000001,142.69999999999999,92.5,80.299999999999997,93.400000000000006,85.700000000000003,94.900000000000006,108.09999999999999,81.900000000000006,105.90000000000001,97.5,109.8,132.80000000000001,126.40000000000001,75.799999999999997,65.400000000000006,116.2,73.900000000000006,105.7,106.09999999999999,126.3,99.900000000000006,77.700000000000003,115,100.7,93.5,91.599999999999994,73.299999999999997,106.59999999999999,78.700000000000003,105.40000000000001,130.5,76,103.90000000000001,103.7,96,118.2,103.5,114.40000000000001,124.09999999999999,95.400000000000006,92.700000000000003,92.900000000000006,99.200000000000003,103.3,99.099999999999994,109.90000000000001,83.400000000000006,133.69999999999999,89.799999999999997,116.90000000000001,99.5,105.7,108.7,92.599999999999994,95.099999999999994,142.80000000000001,108.8,102.59999999999999,114,95.299999999999997,103.7,120.09999999999999,78.799999999999997,104.90000000000001,124.59999999999999,96.299999999999997,126.3,107.2,77.400000000000006,68.799999999999997,100.40000000000001,97.5,115.2,127.90000000000001,101.90000000000001,101.8,82.5,83.099999999999994,106,117.3,108.5,78.799999999999997,104.8,88,90.299999999999997,109.90000000000001,95.599999999999994,100.5,113.09999999999999,91,115.09999999999999,111,124.59999999999999],"y":[41.100000000000001,55.100000000000001,43.899999999999999,46.700000000000003,42.100000000000001,41.200000000000003,41.700000000000003,48.299999999999997,48.200000000000003,48.100000000000001,40.600000000000001,51.899999999999999,47.299999999999997,43.799999999999997,49.5,43.899999999999999,45.200000000000003,50.299999999999997,40.700000000000003,46.5,48.799999999999997,45.600000000000001,41.799999999999997,55.399999999999999,49.5,48.399999999999999,49.899999999999999,40.299999999999997,49.100000000000001,40.600000000000001,38.200000000000003,47.700000000000003,44.700000000000003,42.200000000000003,45.899999999999999,42,51.600000000000001,43.799999999999997,50.899999999999999,52.600000000000001,38.600000000000001,43.100000000000001,41.299999999999997,46.600000000000001,49.899999999999999,64.799999999999997,41.100000000000001,43.100000000000001,45.399999999999999,42.100000000000001,53.899999999999999,48.700000000000003,37.5,40.299999999999997,52.399999999999999,57.399999999999999,44,47.399999999999999,35,43.299999999999997,49,45.799999999999997,52.200000000000003,50.399999999999999,47.399999999999999,54.5,45.100000000000001,51.799999999999997,46,45.899999999999999,46.200000000000003,45.299999999999997,35.600000000000001,42.200000000000003,43.700000000000003,54.600000000000001,56.200000000000003,53.899999999999999,29.699999999999999,39.100000000000001,41.299999999999997,48.899999999999999,50.299999999999997,39.100000000000001,33.899999999999999,53.600000000000001,48.299999999999997,46.200000000000003,53.600000000000001,42.700000000000003,46.899999999999999,37.200000000000003,44.799999999999997,40.600000000000001,51,48.200000000000003,55.700000000000003,41.200000000000003,41.100000000000001,52.100000000000001,41.899999999999999,49.100000000000001,43.100000000000001,36.399999999999999,42.200000000000003,51.600000000000001,48.5,45.299999999999997,44,48.399999999999999,41.799999999999997,37.5,46.200000000000003,43.799999999999997,60.899999999999999,49.799999999999997,54.700000000000003,47.399999999999999,40.299999999999997,34.299999999999997,36.100000000000001,46,46,40.399999999999999,41.100000000000001,39.399999999999999,41.799999999999997,53.200000000000003,45.399999999999999,42.899999999999999,50,50.600000000000001,37.700000000000003,51.700000000000003,51.5,44.299999999999997,29,42.200000000000003,47.299999999999997,49,37.600000000000001,44.200000000000003,41.200000000000003,48.5,40.100000000000001,39.399999999999999,51.899999999999999,43.600000000000001,45.799999999999997,43.700000000000003,44.299999999999997,45,51.799999999999997,49.700000000000003,36.700000000000003,35.700000000000003,50.899999999999999,29.899999999999999,35.600000000000001,45.200000000000003,47.100000000000001,48.700000000000003,37,50,45.700000000000003,38.899999999999999,42.399999999999999,41.299999999999997,42.100000000000001,46.899999999999999,50.100000000000001,39.600000000000001,49.799999999999997,37.899999999999999,39.399999999999999,44.5,45,41.799999999999997,27.800000000000001,43.200000000000003,48.799999999999997,31.800000000000001,41.600000000000001,47.399999999999999,31.5,37.899999999999999,41.100000000000001,47.399999999999999,52.100000000000001,53.899999999999999,47.899999999999999,51,41.899999999999999,48.200000000000003,36.100000000000001,36.299999999999997,46.700000000000003,45,38.200000000000003,49.700000000000003],"z":[122.02,108.67,130.44,123.38,121.48999999999999,125.67,122.88,109.64,118.20999999999999,118.39,114.15000000000001,138.5,110.37,114.68000000000001,112.17,107.08,117.89,116.98999999999999,136.83000000000001,117.26000000000001,108.29000000000001,137.63999999999999,133.58000000000001,117.47,103.43000000000001,115.11,118.28,123.04000000000001,117.13,124.88,124.31,106.23999999999999,109.56999999999999,111.84999999999999,114.41,116.47,120.14,86.679000000000002,114.97,133.66999999999999,108.27,130.27000000000001,123.84999999999999,119.68000000000001,122.01000000000001,102.78,119.06999999999999,137.63999999999999,121.08,120.45999999999999,111.92,119.66,122.56,124.69,115.90000000000001,117.40000000000001,142.25999999999999,95.158000000000001,144.52000000000001,123.70999999999999,131,101.69,113.51000000000001,116.94,124.65000000000001,101.63,125.19,106.66,120.73,127.18000000000001,123.59999999999999,131.91,131.06999999999999,112.84,122.83,109.61,105.45999999999999,130.16999999999999,120,119.40000000000001,130.02000000000001,126.54000000000001,123.84999999999999,133.75,130.22999999999999,122.64,112.41,112.83,133.11000000000001,102.27,119.73,98.563000000000002,131.22999999999999,129.47999999999999,120.01000000000001,119.22,92.650999999999996,126.39,95.882999999999996,94.488,120.88,109.56999999999999,124.53,127.45,129.44,112.40000000000001,124.94,121.11,129.09,125.90000000000001,129.88,118.55,118.38,131.09,96.640000000000001,114.45,106.02,115.79000000000001,127.14,129.08000000000001,108.84,114.81999999999999,121.51000000000001,116.79000000000001,123.31999999999999,124.40000000000001,109.77,118.05,96.546999999999997,132.59999999999999,113.08,106.76000000000001,117.20999999999999,104.28,119.77,113.83,143.96000000000001,132.52000000000001,92.534000000000006,124.84999999999999,104.62,117.19,121.81,128.22999999999999,117,137.34,114.70999999999999,123.59999999999999,127.31,120.94,129.69,123.56,111.37,100.14,140.44,113.34999999999999,121.14,126.19,121.25,110.05,114.86,118.63,136.27000000000001,110.53,128.63,123.39,117.43000000000001,108.37,116.87,119.05,103.84,122.11,110.95,118.95999999999999,123.7,110.05,116.83,123.84999999999999,99.805999999999997,131.40000000000001,146.66999999999999,130.55000000000001,116.53,124.70999999999999,108.59999999999999,140.66,130.34999999999999,128.66,110.37,123.52,113.86,116.56999999999999,113.73,108.72,110,117.69,101.31,126.68000000000001,118.7,127.69],"type":"scatter3d","mode":"markers","name":"Data points","marker":{"color":"rgba(145,145,145,1)","size":[55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55],"sizemode":"area","line":{"color":"rgba(145,145,145,1)"}},"textfont":{"color":"rgba(145,145,145,1)","size":55},"error_y":{"color":"rgba(145,145,145,1)","width":55},"error_x":{"color":"rgba(145,145,145,1)","width":55},"line":{"color":"rgba(145,145,145,1)","width":55},"frame":null},{"x":[71.996327655166724,86.997913827583361,101.9995,117.00108617241665,132.00267234483329],"y":[39.000421259060545,39.000421259060545,39.000421259060545,39.000421259060545,39.000421259060545],"z":[111.40588791890427,116.33324384036931,121.26059976183434,126.18795568329939,131.11531160476443],"type":"scatter3d","mode":"lines","line":{"color":"black","width":10,"dash":"dash"},"name":"-1 SD line","marker":{"color":"rgba(44,160,44,1)","line":{"color":"rgba(44,160,44,1)"}},"error_y":{"color":"rgba(44,160,44,1)"},"error_x":{"color":"rgba(44,160,44,1)"},"frame":null},{"x":[71.996327655166724,86.997913827583361,101.9995,117.00108617241665,132.00267234483329],"y":[50.99557874093945,50.99557874093945,50.99557874093945,50.99557874093945,50.99557874093945],"z":[106.95387839523553,111.88123431670057,116.80859023816561,121.73594615963066,126.66330208109569],"type":"scatter3d","mode":"lines","line":{"color":"black","width":10,"dash":"dash"},"name":"+1 SD line","marker":{"color":"rgba(214,39,40,1)","line":{"color":"rgba(214,39,40,1)"}},"error_y":{"color":"rgba(214,39,40,1)"},"error_x":{"color":"rgba(214,39,40,1)"},"frame":null}],"highlight":{"on":"plotly_click","persistent":false,"dynamic":false,"selectize":false,"opacityDim":0.20000000000000001,"selected":{"opacity":1},"debounce":0},"shinyEvents":["plotly_hover","plotly_click","plotly_selected","plotly_relayout","plotly_brushed","plotly_brushing","plotly_clickannotation","plotly_doubleclick","plotly_deselect","plotly_afterplot","plotly_sunburstclick"],"base_url":"https://plot.ly"},"evals":[],"jsHooks":[]}</script>
</div>
</div>
</section>
<section id="control-variables" class="level2">
<h2 class="anchored" data-anchor-id="control-variables">Control variables</h2>
<p>Many people use “control” variables in their multiple regression. Before using this type of analysis I urge you to read:</p>
<p><a href="https://doi.org/10.1177%2F25152459221095823">Wysocki, A. C., Lawson, K. M., &amp; Rhemtulla, M. (2022). Statistical control requires causal justification. Advances in Methods and Practices in Psychological Science, 5(2), 25152459221095823.</a></p>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>