<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 16 All the data: Several correlations | Welcome!</title>
  <meta name="description" content="Course notes for PSYC 6060" />
  <meta name="generator" content="bookdown 0.20 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 16 All the data: Several correlations | Welcome!" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="Course notes for PSYC 6060" />
  <meta name="github-repo" content="dstanley4/psyc6060bookdown" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 16 All the data: Several correlations | Welcome!" />
  
  <meta name="twitter:description" content="Course notes for PSYC 6060" />
  

<meta name="author" content="David J. Stanley" />


<meta name="date" content="2020-11-19" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="correlations.html"/>
<link rel="next" href="references.html"/>
<script src="libs/jquery/jquery.min.js"></script>
<link href="libs/gitbook/css/style.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-clipboard.css" rel="stylesheet" />









<script src="libs/accessible-code-block/empty-anchor.js"></script>


<style type="text/css">
code.sourceCode > span { display: inline-block; line-height: 1.25; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="css/style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Course Notes</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Course:</a></li>
<li class="chapter" data-level="" data-path="about-the-author.html"><a href="about-the-author.html"><i class="fa fa-check"></i>About the Author</a></li>
<li class="chapter" data-level="1" data-path="introduction.html"><a href="introduction.html"><i class="fa fa-check"></i><b>1</b> Introduction</a><ul>
<li class="chapter" data-level="1.1" data-path="introduction.html"><a href="introduction.html#a-focus-on-workflow"><i class="fa fa-check"></i><b>1.1</b> A focus on workflow</a></li>
<li class="chapter" data-level="1.2" data-path="introduction.html"><a href="introduction.html#r-works-with-plug-ins"><i class="fa fa-check"></i><b>1.2</b> R works with plug-ins</a></li>
<li class="chapter" data-level="1.3" data-path="introduction.html"><a href="introduction.html#create-an-account-at-r-studio-cloud"><i class="fa fa-check"></i><b>1.3</b> Create an account at R Studio Cloud</a></li>
<li class="chapter" data-level="1.4" data-path="introduction.html"><a href="introduction.html#join-the-class-workspace"><i class="fa fa-check"></i><b>1.4</b> Join the class workspace</a></li>
<li class="chapter" data-level="1.5" data-path="introduction.html"><a href="introduction.html#exploring-the-r-studio-interface"><i class="fa fa-check"></i><b>1.5</b> Exploring the R Studio Interface</a><ul>
<li class="chapter" data-level="1.5.1" data-path="introduction.html"><a href="introduction.html#console-panel"><i class="fa fa-check"></i><b>1.5.1</b> Console panel</a></li>
<li class="chapter" data-level="1.5.2" data-path="introduction.html"><a href="introduction.html#script-panel"><i class="fa fa-check"></i><b>1.5.2</b> Script Panel</a></li>
</ul></li>
<li class="chapter" data-level="1.6" data-path="introduction.html"><a href="introduction.html#writing-your-first-script"><i class="fa fa-check"></i><b>1.6</b> Writing your first script</a><ul>
<li class="chapter" data-level="1.6.1" data-path="introduction.html"><a href="introduction.html#create-the-script-file"><i class="fa fa-check"></i><b>1.6.1</b> Create the script file</a></li>
<li class="chapter" data-level="1.6.2" data-path="introduction.html"><a href="introduction.html#add-a-comment-to-your-script"><i class="fa fa-check"></i><b>1.6.2</b> Add a comment to your script</a></li>
<li class="chapter" data-level="1.6.3" data-path="introduction.html"><a href="introduction.html#background-about-the-tidyverse"><i class="fa fa-check"></i><b>1.6.3</b> Background about the tidyverse</a></li>
<li class="chapter" data-level="1.6.4" data-path="introduction.html"><a href="introduction.html#add-librarytidyverse-to-your-script"><i class="fa fa-check"></i><b>1.6.4</b> Add library(tidyverse) to your script</a></li>
<li class="chapter" data-level="1.6.5" data-path="introduction.html"><a href="introduction.html#activate-tidyverse-auto-complete-for-your-script"><i class="fa fa-check"></i><b>1.6.5</b> Activate tidyverse auto-complete for your script</a></li>
</ul></li>
<li class="chapter" data-level="1.7" data-path="introduction.html"><a href="introduction.html#loading-your-data"><i class="fa fa-check"></i><b>1.7</b> Loading your data</a><ul>
<li class="chapter" data-level="1.7.1" data-path="introduction.html"><a href="introduction.html#use-read_csv-not-read.csv-to-open-files."><i class="fa fa-check"></i><b>1.7.1</b> Use read_csv (not read.csv) to open files.</a></li>
</ul></li>
<li class="chapter" data-level="1.8" data-path="introduction.html"><a href="introduction.html#checking-out-your-data"><i class="fa fa-check"></i><b>1.8</b> Checking out your data</a><ul>
<li class="chapter" data-level="1.8.1" data-path="introduction.html"><a href="introduction.html#view-see-a-spreadsheet-view-of-your-data"><i class="fa fa-check"></i><b>1.8.1</b> view(): See a spreadsheet view of your data</a></li>
<li class="chapter" data-level="1.8.2" data-path="introduction.html"><a href="introduction.html#print-see-you-data-in-the-console"><i class="fa fa-check"></i><b>1.8.2</b> print(): See you data in the Console</a></li>
<li class="chapter" data-level="1.8.3" data-path="introduction.html"><a href="introduction.html#head-check-out-the-first-few-rows-of-data"><i class="fa fa-check"></i><b>1.8.3</b> head(): Check out the first few rows of data</a></li>
<li class="chapter" data-level="1.8.4" data-path="introduction.html"><a href="introduction.html#tail-check-out-the-last-few-rows-of-data"><i class="fa fa-check"></i><b>1.8.4</b> tail(): Check out the last few rows of data</a></li>
<li class="chapter" data-level="1.8.5" data-path="introduction.html"><a href="introduction.html#summary-quick-summaries"><i class="fa fa-check"></i><b>1.8.5</b> summary(): Quick summaries</a></li>
</ul></li>
<li class="chapter" data-level="1.9" data-path="introduction.html"><a href="introduction.html#run-vs.-source-with-echo-vs.-source"><i class="fa fa-check"></i><b>1.9</b> Run <em>vs.</em> Source with Echo <em>vs.</em> Source</a><ul>
<li class="chapter" data-level="1.9.1" data-path="introduction.html"><a href="introduction.html#run-select-text"><i class="fa fa-check"></i><b>1.9.1</b> Run select text</a></li>
<li class="chapter" data-level="1.9.2" data-path="introduction.html"><a href="introduction.html#source-without-echo"><i class="fa fa-check"></i><b>1.9.2</b> Source (without Echo)</a></li>
<li class="chapter" data-level="1.9.3" data-path="introduction.html"><a href="introduction.html#source-with-echo"><i class="fa fa-check"></i><b>1.9.3</b> Source with Echo</a></li>
</ul></li>
<li class="chapter" data-level="1.10" data-path="introduction.html"><a href="introduction.html#trying-source-with-echo"><i class="fa fa-check"></i><b>1.10</b> Trying Source with Echo</a></li>
<li class="chapter" data-level="1.11" data-path="introduction.html"><a href="introduction.html#a-few-key-points-about"><i class="fa fa-check"></i><b>1.11</b> A few key points about</a><ul>
<li class="chapter" data-level="1.11.1" data-path="introduction.html"><a href="introduction.html#lists"><i class="fa fa-check"></i><b>1.11.1</b> Lists</a></li>
</ul></li>
<li class="chapter" data-level="1.12" data-path="introduction.html"><a href="introduction.html#thats-it"><i class="fa fa-check"></i><b>1.12</b> That’s it!</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="handling-data-with-the-tidyverse.html"><a href="handling-data-with-the-tidyverse.html"><i class="fa fa-check"></i><b>2</b> Handling Data with the Tidyverse</a><ul>
<li class="chapter" data-level="2.1" data-path="handling-data-with-the-tidyverse.html"><a href="handling-data-with-the-tidyverse.html#required"><i class="fa fa-check"></i><b>2.1</b> Required</a></li>
<li class="chapter" data-level="2.2" data-path="handling-data-with-the-tidyverse.html"><a href="handling-data-with-the-tidyverse.html#objective"><i class="fa fa-check"></i><b>2.2</b> Objective</a></li>
<li class="chapter" data-level="2.3" data-path="handling-data-with-the-tidyverse.html"><a href="handling-data-with-the-tidyverse.html#using-the-console"><i class="fa fa-check"></i><b>2.3</b> Using the Console</a></li>
<li class="chapter" data-level="2.4" data-path="handling-data-with-the-tidyverse.html"><a href="handling-data-with-the-tidyverse.html#basic-tidyverse-commands"><i class="fa fa-check"></i><b>2.4</b> Basic tidyverse commands</a><ul>
<li class="chapter" data-level="2.4.1" data-path="handling-data-with-the-tidyverse.html"><a href="handling-data-with-the-tidyverse.html#select"><i class="fa fa-check"></i><b>2.4.1</b> select()</a></li>
<li class="chapter" data-level="2.4.2" data-path="handling-data-with-the-tidyverse.html"><a href="handling-data-with-the-tidyverse.html#summarise"><i class="fa fa-check"></i><b>2.4.2</b> summarise()</a></li>
<li class="chapter" data-level="2.4.3" data-path="handling-data-with-the-tidyverse.html"><a href="handling-data-with-the-tidyverse.html#filter"><i class="fa fa-check"></i><b>2.4.3</b> filter()</a></li>
<li class="chapter" data-level="2.4.4" data-path="handling-data-with-the-tidyverse.html"><a href="handling-data-with-the-tidyverse.html#group_by"><i class="fa fa-check"></i><b>2.4.4</b> group_by()</a></li>
<li class="chapter" data-level="2.4.5" data-path="handling-data-with-the-tidyverse.html"><a href="handling-data-with-the-tidyverse.html#mutate"><i class="fa fa-check"></i><b>2.4.5</b> mutate()</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="handling-data-with-the-tidyverse.html"><a href="handling-data-with-the-tidyverse.html#advanced-tidyverse-commands"><i class="fa fa-check"></i><b>2.5</b> Advanced tidyverse commands</a><ul>
<li class="chapter" data-level="2.5.1" data-path="handling-data-with-the-tidyverse.html"><a href="handling-data-with-the-tidyverse.html#select-1"><i class="fa fa-check"></i><b>2.5.1</b> select()</a></li>
<li class="chapter" data-level="2.5.2" data-path="handling-data-with-the-tidyverse.html"><a href="handling-data-with-the-tidyverse.html#summarise-1"><i class="fa fa-check"></i><b>2.5.2</b> summarise()</a></li>
<li class="chapter" data-level="2.5.3" data-path="handling-data-with-the-tidyverse.html"><a href="handling-data-with-the-tidyverse.html#mutate-1"><i class="fa fa-check"></i><b>2.5.3</b> mutate()</a></li>
</ul></li>
<li class="chapter" data-level="2.6" data-path="handling-data-with-the-tidyverse.html"><a href="handling-data-with-the-tidyverse.html#using-help"><i class="fa fa-check"></i><b>2.6</b> Using help</a></li>
<li class="chapter" data-level="2.7" data-path="handling-data-with-the-tidyverse.html"><a href="handling-data-with-the-tidyverse.html#base-r-vs-tidyverse"><i class="fa fa-check"></i><b>2.7</b> Base R vs tidyverse</a><ul>
<li class="chapter" data-level="2.7.1" data-path="handling-data-with-the-tidyverse.html"><a href="handling-data-with-the-tidyverse.html#tibbles-vs.-data-frames"><i class="fa fa-check"></i><b>2.7.1</b> Tibbles vs. data frames</a></li>
<li class="chapter" data-level="2.7.2" data-path="handling-data-with-the-tidyverse.html"><a href="handling-data-with-the-tidyverse.html#read.csv-and-data-frames"><i class="fa fa-check"></i><b>2.7.2</b> read.csv() and data frames</a></li>
<li class="chapter" data-level="2.7.3" data-path="handling-data-with-the-tidyverse.html"><a href="handling-data-with-the-tidyverse.html#read_csv-and-tibbles"><i class="fa fa-check"></i><b>2.7.3</b> read_csv() and tibbles</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="populations.html"><a href="populations.html"><i class="fa fa-check"></i><b>3</b> Populations</a><ul>
<li class="chapter" data-level="3.1" data-path="populations.html"><a href="populations.html#notation"><i class="fa fa-check"></i><b>3.1</b> Notation</a></li>
<li class="chapter" data-level="3.2" data-path="populations.html"><a href="populations.html#population-vs-samples"><i class="fa fa-check"></i><b>3.2</b> Population vs samples</a></li>
<li class="chapter" data-level="3.3" data-path="populations.html"><a href="populations.html#a-small-population"><i class="fa fa-check"></i><b>3.3</b> A small population</a><ul>
<li class="chapter" data-level="3.3.1" data-path="populations.html"><a href="populations.html#mean-mu"><i class="fa fa-check"></i><b>3.3.1</b> Mean (<span class="math inline">\(\mu\)</span>)</a></li>
<li class="chapter" data-level="3.3.2" data-path="populations.html"><a href="populations.html#variance-sigma2"><i class="fa fa-check"></i><b>3.3.2</b> Variance (<span class="math inline">\(\sigma^2\)</span>)</a></li>
<li class="chapter" data-level="3.3.3" data-path="populations.html"><a href="populations.html#standard-deviation-sigma"><i class="fa fa-check"></i><b>3.3.3</b> Standard Deviation (<span class="math inline">\(\sigma\)</span>)</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="populations.html"><a href="populations.html#visualizing-populations"><i class="fa fa-check"></i><b>3.4</b> Visualizing populations</a></li>
<li class="chapter" data-level="3.5" data-path="populations.html"><a href="populations.html#comparisons-same-sigma"><i class="fa fa-check"></i><b>3.5</b> Comparisons: Same <span class="math inline">\(\sigma\)</span></a><ul>
<li class="chapter" data-level="3.5.1" data-path="populations.html"><a href="populations.html#standardized-units"><i class="fa fa-check"></i><b>3.5.1</b> Standardized units</a></li>
<li class="chapter" data-level="3.5.2" data-path="populations.html"><a href="populations.html#cohens-d-units"><i class="fa fa-check"></i><b>3.5.2</b> Cohen’s <span class="math inline">\(d\)</span> units</a></li>
<li class="chapter" data-level="3.5.3" data-path="populations.html"><a href="populations.html#cohens-d-advantages"><i class="fa fa-check"></i><b>3.5.3</b> Cohen’s <span class="math inline">\(d\)</span> advantages</a></li>
<li class="chapter" data-level="3.5.4" data-path="populations.html"><a href="populations.html#cohens-d-caveats"><i class="fa fa-check"></i><b>3.5.4</b> Cohen’s <span class="math inline">\(d\)</span> caveats</a></li>
</ul></li>
<li class="chapter" data-level="3.6" data-path="populations.html"><a href="populations.html#comparisons-different-sigma"><i class="fa fa-check"></i><b>3.6</b> Comparisons: Different <span class="math inline">\(\sigma\)</span></a></li>
<li class="chapter" data-level="3.7" data-path="populations.html"><a href="populations.html#comparisons-repeated-measures"><i class="fa fa-check"></i><b>3.7</b> Comparisons: Repeated Measures</a></li>
<li class="chapter" data-level="3.8" data-path="populations.html"><a href="populations.html#comparison-benchmarks"><i class="fa fa-check"></i><b>3.8</b> Comparison Benchmarks</a></li>
<li class="chapter" data-level="3.9" data-path="populations.html"><a href="populations.html#population-relations"><i class="fa fa-check"></i><b>3.9</b> Population relations</a></li>
<li class="chapter" data-level="3.10" data-path="populations.html"><a href="populations.html#relation-benchmarks"><i class="fa fa-check"></i><b>3.10</b> Relation benchmarks</a></li>
<li class="chapter" data-level="3.11" data-path="populations.html"><a href="populations.html#key-points"><i class="fa fa-check"></i><b>3.11</b> Key points</a></li>
<li class="chapter" data-level="3.12" data-path="populations.html"><a href="populations.html#minor-points"><i class="fa fa-check"></i><b>3.12</b> Minor Points</a></li>
<li class="chapter" data-level="3.13" data-path="populations.html"><a href="populations.html#self-assessment"><i class="fa fa-check"></i><b>3.13</b> Self Assessment</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="graphing.html"><a href="graphing.html"><i class="fa fa-check"></i><b>4</b> Graphing</a><ul>
<li class="chapter" data-level="4.1" data-path="handling-data-with-the-tidyverse.html"><a href="handling-data-with-the-tidyverse.html#required"><i class="fa fa-check"></i><b>4.1</b> Required</a></li>
<li class="chapter" data-level="4.2" data-path="graphing.html"><a href="graphing.html#data"><i class="fa fa-check"></i><b>4.2</b> Data</a></li>
<li class="chapter" data-level="4.3" data-path="graphing.html"><a href="graphing.html#graph-basics"><i class="fa fa-check"></i><b>4.3</b> Graph basics</a></li>
<li class="chapter" data-level="4.4" data-path="graphing.html"><a href="graphing.html#graphing-efficiently"><i class="fa fa-check"></i><b>4.4</b> Graphing efficiently</a></li>
<li class="chapter" data-level="4.5" data-path="graphing.html"><a href="graphing.html#aesthetics"><i class="fa fa-check"></i><b>4.5</b> Aesthetics</a><ul>
<li class="chapter" data-level="4.5.1" data-path="graphing.html"><a href="graphing.html#fill-color"><i class="fa fa-check"></i><b>4.5.1</b> Fill color</a></li>
<li class="chapter" data-level="4.5.2" data-path="graphing.html"><a href="graphing.html#overriding-aes"><i class="fa fa-check"></i><b>4.5.2</b> Overriding aes()</a></li>
</ul></li>
<li class="chapter" data-level="4.6" data-path="graphing.html"><a href="graphing.html#apa-style"><i class="fa fa-check"></i><b>4.6</b> APA style</a></li>
<li class="chapter" data-level="4.7" data-path="graphing.html"><a href="graphing.html#axes"><i class="fa fa-check"></i><b>4.7</b> Axes</a><ul>
<li class="chapter" data-level="4.7.1" data-path="graphing.html"><a href="graphing.html#range"><i class="fa fa-check"></i><b>4.7.1</b> Range</a></li>
<li class="chapter" data-level="4.7.2" data-path="graphing.html"><a href="graphing.html#ticks"><i class="fa fa-check"></i><b>4.7.2</b> Ticks</a></li>
<li class="chapter" data-level="4.7.3" data-path="graphing.html"><a href="graphing.html#labels"><i class="fa fa-check"></i><b>4.7.3</b> Labels</a></li>
</ul></li>
<li class="chapter" data-level="4.8" data-path="graphing.html"><a href="graphing.html#axis-values"><i class="fa fa-check"></i><b>4.8</b> Axis values</a><ul>
<li class="chapter" data-level="4.8.1" data-path="graphing.html"><a href="graphing.html#text"><i class="fa fa-check"></i><b>4.8.1</b> Text</a></li>
<li class="chapter" data-level="4.8.2" data-path="graphing.html"><a href="graphing.html#angle"><i class="fa fa-check"></i><b>4.8.2</b> Angle</a></li>
<li class="chapter" data-level="4.8.3" data-path="graphing.html"><a href="graphing.html#alignment"><i class="fa fa-check"></i><b>4.8.3</b> Alignment</a></li>
<li class="chapter" data-level="4.8.4" data-path="graphing.html"><a href="graphing.html#order"><i class="fa fa-check"></i><b>4.8.4</b> Order</a></li>
<li class="chapter" data-level="4.8.5" data-path="graphing.html"><a href="graphing.html#legend-order"><i class="fa fa-check"></i><b>4.8.5</b> Legend order</a></li>
</ul></li>
<li class="chapter" data-level="4.9" data-path="graphing.html"><a href="graphing.html#custom-colours"><i class="fa fa-check"></i><b>4.9</b> Custom colours</a><ul>
<li class="chapter" data-level="4.9.1" data-path="graphing.html"><a href="graphing.html#r-palette"><i class="fa fa-check"></i><b>4.9.1</b> R palette</a></li>
<li class="chapter" data-level="4.9.2" data-path="graphing.html"><a href="graphing.html#hex-colours"><i class="fa fa-check"></i><b>4.9.2</b> Hex colours</a></li>
</ul></li>
<li class="chapter" data-level="4.10" data-path="graphing.html"><a href="graphing.html#emoji"><i class="fa fa-check"></i><b>4.10</b> Emoji</a></li>
<li class="chapter" data-level="4.11" data-path="graphing.html"><a href="graphing.html#accessible-colors"><i class="fa fa-check"></i><b>4.11</b> Accessible Colors</a><ul>
<li class="chapter" data-level="4.11.1" data-path="graphing.html"><a href="graphing.html#rcolorbrewer"><i class="fa fa-check"></i><b>4.11.1</b> RColorBrewer</a></li>
<li class="chapter" data-level="4.11.2" data-path="graphing.html"><a href="graphing.html#avoid-color"><i class="fa fa-check"></i><b>4.11.2</b> Avoid color</a></li>
</ul></li>
<li class="chapter" data-level="4.12" data-path="graphing.html"><a href="graphing.html#saving"><i class="fa fa-check"></i><b>4.12</b> Saving</a><ul>
<li class="chapter" data-level="4.12.1" data-path="graphing.html"><a href="graphing.html#mac"><i class="fa fa-check"></i><b>4.12.1</b> MAC</a></li>
<li class="chapter" data-level="4.12.2" data-path="graphing.html"><a href="graphing.html#pc-or-mac"><i class="fa fa-check"></i><b>4.12.2</b> PC or MAC</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="sampling-accuracy.html"><a href="sampling-accuracy.html"><i class="fa fa-check"></i><b>5</b> Sampling Accuracy</a><ul>
<li class="chapter" data-level="5.1" data-path="sampling-accuracy.html"><a href="sampling-accuracy.html#overview"><i class="fa fa-check"></i><b>5.1</b> Overview</a></li>
<li class="chapter" data-level="5.2" data-path="sampling-accuracy.html"><a href="sampling-accuracy.html#data-for-the-chapter"><i class="fa fa-check"></i><b>5.2</b> Data for the chapter</a></li>
<li class="chapter" data-level="5.3" data-path="populations.html"><a href="populations.html#notation"><i class="fa fa-check"></i><b>5.3</b> Notation</a></li>
<li class="chapter" data-level="5.4" data-path="sampling-accuracy.html"><a href="sampling-accuracy.html#estimating-mu"><i class="fa fa-check"></i><b>5.4</b> Estimating <span class="math inline">\(\mu\)</span></a><ul>
<li class="chapter" data-level="5.4.1" data-path="sampling-accuracy.html"><a href="sampling-accuracy.html#assessing-bias"><i class="fa fa-check"></i><b>5.4.1</b> Assessing bias</a></li>
</ul></li>
<li class="chapter" data-level="5.5" data-path="sampling-accuracy.html"><a href="sampling-accuracy.html#estimating-sigma2"><i class="fa fa-check"></i><b>5.5</b> Estimating <span class="math inline">\(\sigma^2\)</span></a><ul>
<li class="chapter" data-level="5.5.1" data-path="sampling-accuracy.html"><a href="sampling-accuracy.html#assessing-bias-1"><i class="fa fa-check"></i><b>5.5.1</b> Assessing bias</a></li>
</ul></li>
<li class="chapter" data-level="5.6" data-path="sampling-accuracy.html"><a href="sampling-accuracy.html#estimating-sigma"><i class="fa fa-check"></i><b>5.6</b> Estimating <span class="math inline">\(\sigma\)</span></a></li>
<li class="chapter" data-level="5.7" data-path="sampling-accuracy.html"><a href="sampling-accuracy.html#estimating-delta"><i class="fa fa-check"></i><b>5.7</b> Estimating <span class="math inline">\(\delta\)</span></a><ul>
<li class="chapter" data-level="5.7.1" data-path="sampling-accuracy.html"><a href="sampling-accuracy.html#pooled-standard-deviation"><i class="fa fa-check"></i><b>5.7.1</b> Pooled standard deviation</a></li>
<li class="chapter" data-level="5.7.2" data-path="sampling-accuracy.html"><a href="sampling-accuracy.html#calculating-d"><i class="fa fa-check"></i><b>5.7.2</b> Calculating <span class="math inline">\(d\)</span></a></li>
<li class="chapter" data-level="5.7.3" data-path="sampling-accuracy.html"><a href="sampling-accuracy.html#assessing-bias-2"><i class="fa fa-check"></i><b>5.7.3</b> Assessing bias</a></li>
<li class="chapter" data-level="5.7.4" data-path="sampling-accuracy.html"><a href="sampling-accuracy.html#illustrating-variability"><i class="fa fa-check"></i><b>5.7.4</b> Illustrating variability</a></li>
</ul></li>
<li class="chapter" data-level="5.8" data-path="sampling-accuracy.html"><a href="sampling-accuracy.html#estimating-rho"><i class="fa fa-check"></i><b>5.8</b> Estimating <span class="math inline">\(\rho\)</span></a><ul>
<li class="chapter" data-level="5.8.1" data-path="sampling-accuracy.html"><a href="sampling-accuracy.html#assessing-bias-3"><i class="fa fa-check"></i><b>5.8.1</b> Assessing bias</a></li>
</ul></li>
<li class="chapter" data-level="5.9" data-path="sampling-accuracy.html"><a href="sampling-accuracy.html#overview-1"><i class="fa fa-check"></i><b>5.9</b> Overview</a></li>
<li class="chapter" data-level="5.10" data-path="sampling-accuracy.html"><a href="sampling-accuracy.html#meta-analysis"><i class="fa fa-check"></i><b>5.10</b> Meta-analysis</a></li>
<li class="chapter" data-level="5.11" data-path="sampling-accuracy.html"><a href="sampling-accuracy.html#a-joke"><i class="fa fa-check"></i><b>5.11</b> A joke</a></li>
<li class="chapter" data-level="5.12" data-path="populations.html"><a href="populations.html#key-points"><i class="fa fa-check"></i><b>5.12</b> Key Points</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="sampling-precision.html"><a href="sampling-precision.html"><i class="fa fa-check"></i><b>6</b> Sampling Precision</a><ul>
<li class="chapter" data-level="6.1" data-path="sampling-accuracy.html"><a href="sampling-accuracy.html#overview"><i class="fa fa-check"></i><b>6.1</b> Overview</a></li>
<li class="chapter" data-level="6.2" data-path="sampling-precision.html"><a href="sampling-precision.html#population-individuals"><i class="fa fa-check"></i><b>6.2</b> Population / Individuals</a></li>
<li class="chapter" data-level="6.3" data-path="sampling-precision.html"><a href="sampling-precision.html#sampling-distribution"><i class="fa fa-check"></i><b>6.3</b> Sampling distribution</a></li>
<li class="chapter" data-level="6.4" data-path="sampling-precision.html"><a href="sampling-precision.html#precision-indices"><i class="fa fa-check"></i><b>6.4</b> Precision indices</a></li>
<li class="chapter" data-level="6.5" data-path="sampling-precision.html"><a href="sampling-precision.html#a-short-cut"><i class="fa fa-check"></i><b>6.5</b> A short cut</a></li>
<li class="chapter" data-level="6.6" data-path="sampling-precision.html"><a href="sampling-precision.html#estimates-of-precision"><i class="fa fa-check"></i><b>6.6</b> Estimates of precision</a><ul>
<li class="chapter" data-level="6.6.1" data-path="sampling-precision.html"><a href="sampling-precision.html#a-worked-example"><i class="fa fa-check"></i><b>6.6.1</b> A worked example</a></li>
</ul></li>
<li class="chapter" data-level="6.7" data-path="sampling-precision.html"><a href="sampling-precision.html#bias-of-precision-estimates"><i class="fa fa-check"></i><b>6.7</b> Bias of precision estimates</a></li>
<li class="chapter" data-level="6.8" data-path="sampling-precision.html"><a href="sampling-precision.html#where-are-we"><i class="fa fa-check"></i><b>6.8</b> Where are we?</a></li>
<li class="chapter" data-level="6.9" data-path="sampling-precision.html"><a href="sampling-precision.html#precision-for-means-causes"><i class="fa fa-check"></i><b>6.9</b> Precision for means: Causes</a></li>
<li class="chapter" data-level="6.10" data-path="sampling-precision.html"><a href="sampling-precision.html#precision-for-d-values-causes"><i class="fa fa-check"></i><b>6.10</b> Precision for <span class="math inline">\(d\)</span>-values: Causes</a><ul>
<li class="chapter" data-level="6.10.1" data-path="sampling-precision.html"><a href="sampling-precision.html#sample-size"><i class="fa fa-check"></i><b>6.10.1</b> Sample size</a></li>
<li class="chapter" data-level="6.10.2" data-path="sampling-precision.html"><a href="sampling-precision.html#population-effect-size-delta"><i class="fa fa-check"></i><b>6.10.2</b> Population effect size (<span class="math inline">\(\delta\)</span>)</a></li>
</ul></li>
<li class="chapter" data-level="6.11" data-path="sampling-precision.html"><a href="sampling-precision.html#precision-for-sample-correlations-r-causes"><i class="fa fa-check"></i><b>6.11</b> Precision for sample correlations (<span class="math inline">\(r\)</span>): Causes</a><ul>
<li class="chapter" data-level="6.11.1" data-path="sampling-precision.html"><a href="sampling-precision.html#sample-size-1"><i class="fa fa-check"></i><b>6.11.1</b> Sample size</a></li>
<li class="chapter" data-level="6.11.2" data-path="sampling-precision.html"><a href="sampling-precision.html#population-effect-size-rho"><i class="fa fa-check"></i><b>6.11.2</b> Population effect size (<span class="math inline">\(\rho\)</span>)</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="effect-sizes-from-publications.html"><a href="effect-sizes-from-publications.html"><i class="fa fa-check"></i><b>7</b> Effect sizes from publications</a><ul>
<li class="chapter" data-level="7.1" data-path="handling-data-with-the-tidyverse.html"><a href="handling-data-with-the-tidyverse.html#required"><i class="fa fa-check"></i><b>7.1</b> Required</a></li>
<li class="chapter" data-level="7.2" data-path="handling-data-with-the-tidyverse.html"><a href="handling-data-with-the-tidyverse.html#objective"><i class="fa fa-check"></i><b>7.2</b> Objective</a></li>
<li class="chapter" data-level="7.3" data-path="sampling-accuracy.html"><a href="sampling-accuracy.html#estimating-delta"><i class="fa fa-check"></i><b>7.3</b> Estimating <span class="math inline">\(\delta\)</span></a><ul>
<li class="chapter" data-level="7.3.1" data-path="effect-sizes-from-publications.html"><a href="effect-sizes-from-publications.html#independent-groups"><i class="fa fa-check"></i><b>7.3.1</b> Independent Groups</a></li>
<li class="chapter" data-level="7.3.2" data-path="effect-sizes-from-publications.html"><a href="effect-sizes-from-publications.html#repeated-measures"><i class="fa fa-check"></i><b>7.3.2</b> Repeated Measures</a></li>
</ul></li>
<li class="chapter" data-level="7.4" data-path="sampling-accuracy.html"><a href="sampling-accuracy.html#estimating-rho"><i class="fa fa-check"></i><b>7.4</b> Estimating <span class="math inline">\(\rho\)</span></a><ul>
<li class="chapter" data-level="7.4.1" data-path="effect-sizes-from-publications.html"><a href="effect-sizes-from-publications.html#a-single-correlation"><i class="fa fa-check"></i><b>7.4.1</b> A single correlation</a></li>
<li class="chapter" data-level="7.4.2" data-path="effect-sizes-from-publications.html"><a href="effect-sizes-from-publications.html#difference-between-two-correlations"><i class="fa fa-check"></i><b>7.4.2</b> Difference between two correlations</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="8" data-path="nhst-and-sample-size.html"><a href="nhst-and-sample-size.html"><i class="fa fa-check"></i><b>8</b> NHST and sample size</a><ul>
<li class="chapter" data-level="8.1" data-path="handling-data-with-the-tidyverse.html"><a href="handling-data-with-the-tidyverse.html#required"><i class="fa fa-check"></i><b>8.1</b> Required</a></li>
<li class="chapter" data-level="8.2" data-path="sampling-accuracy.html"><a href="sampling-accuracy.html#overview"><i class="fa fa-check"></i><b>8.2</b> Overview</a></li>
<li class="chapter" data-level="8.3" data-path="nhst-and-sample-size.html"><a href="nhst-and-sample-size.html#goals"><i class="fa fa-check"></i><b>8.3</b> Goals</a></li>
<li class="chapter" data-level="8.4" data-path="nhst-and-sample-size.html"><a href="nhst-and-sample-size.html#independent-groups-t-test"><i class="fa fa-check"></i><b>8.4</b> Independent groups <span class="math inline">\(t\)</span>-test</a><ul>
<li class="chapter" data-level="8.4.1" data-path="nhst-and-sample-size.html"><a href="nhst-and-sample-size.html#population-effect-size"><i class="fa fa-check"></i><b>8.4.1</b> Population effect size</a></li>
<li class="chapter" data-level="8.4.2" data-path="nhst-and-sample-size.html"><a href="nhst-and-sample-size.html#determining-sample-size"><i class="fa fa-check"></i><b>8.4.2</b> Determining sample size</a></li>
<li class="chapter" data-level="8.4.3" data-path="nhst-and-sample-size.html"><a href="nhst-and-sample-size.html#what-will-be-signficant"><i class="fa fa-check"></i><b>8.4.3</b> What will be signficant?</a></li>
</ul></li>
<li class="chapter" data-level="8.5" data-path="nhst-and-sample-size.html"><a href="nhst-and-sample-size.html#repeated-measures-t-test"><i class="fa fa-check"></i><b>8.5</b> Repeated measures <span class="math inline">\(t\)</span>-test</a><ul>
<li class="chapter" data-level="8.5.1" data-path="nhst-and-sample-size.html"><a href="nhst-and-sample-size.html#population-effect-size-1"><i class="fa fa-check"></i><b>8.5.1</b> Population effect size</a></li>
<li class="chapter" data-level="8.5.2" data-path="nhst-and-sample-size.html"><a href="nhst-and-sample-size.html#determining-sample-size-1"><i class="fa fa-check"></i><b>8.5.2</b> Determining sample size</a></li>
<li class="chapter" data-level="8.5.3" data-path="nhst-and-sample-size.html"><a href="nhst-and-sample-size.html#what-will-be-signficant-1"><i class="fa fa-check"></i><b>8.5.3</b> What will be signficant?</a></li>
</ul></li>
<li class="chapter" data-level="8.6" data-path="nhst-and-sample-size.html"><a href="nhst-and-sample-size.html#correlations"><i class="fa fa-check"></i><b>8.6</b> Correlations</a><ul>
<li class="chapter" data-level="8.6.1" data-path="nhst-and-sample-size.html"><a href="nhst-and-sample-size.html#population-effect-size-2"><i class="fa fa-check"></i><b>8.6.1</b> Population effect size</a></li>
<li class="chapter" data-level="8.6.2" data-path="nhst-and-sample-size.html"><a href="nhst-and-sample-size.html#determining-sample-size-2"><i class="fa fa-check"></i><b>8.6.2</b> Determining sample size</a></li>
<li class="chapter" data-level="8.6.3" data-path="nhst-and-sample-size.html"><a href="nhst-and-sample-size.html#what-will-be-signficant-2"><i class="fa fa-check"></i><b>8.6.3</b> What will be signficant?</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="9" data-path="equivalence-tests-and-sample-size.html"><a href="equivalence-tests-and-sample-size.html"><i class="fa fa-check"></i><b>9</b> Equivalence tests and sample size</a><ul>
<li class="chapter" data-level="9.1" data-path="handling-data-with-the-tidyverse.html"><a href="handling-data-with-the-tidyverse.html#required"><i class="fa fa-check"></i><b>9.1</b> Required</a></li>
<li class="chapter" data-level="9.2" data-path="equivalence-tests-and-sample-size.html"><a href="equivalence-tests-and-sample-size.html#interpreting-non-significant-findings"><i class="fa fa-check"></i><b>9.2</b> Interpreting non-significant findings</a></li>
<li class="chapter" data-level="9.3" data-path="equivalence-tests-and-sample-size.html"><a href="equivalence-tests-and-sample-size.html#when-would-i-use-an-equivalence-test"><i class="fa fa-check"></i><b>9.3</b> When would I use an equivalence test?</a><ul>
<li class="chapter" data-level="9.3.1" data-path="equivalence-tests-and-sample-size.html"><a href="equivalence-tests-and-sample-size.html#t-test"><i class="fa fa-check"></i><b>9.3.1</b> <span class="math inline">\(t\)</span>-test</a></li>
<li class="chapter" data-level="9.3.2" data-path="equivalence-tests-and-sample-size.html"><a href="equivalence-tests-and-sample-size.html#correlation"><i class="fa fa-check"></i><b>9.3.2</b> Correlation</a></li>
</ul></li>
<li class="chapter" data-level="9.4" data-path="equivalence-tests-and-sample-size.html"><a href="equivalence-tests-and-sample-size.html#possible-outcomes"><i class="fa fa-check"></i><b>9.4</b> Possible Outcomes</a></li>
<li class="chapter" data-level="9.5" data-path="equivalence-tests-and-sample-size.html"><a href="equivalence-tests-and-sample-size.html#what-is-an-equivalence-test"><i class="fa fa-check"></i><b>9.5</b> What is an equivalence test</a></li>
<li class="chapter" data-level="9.6" data-path="equivalence-tests-and-sample-size.html"><a href="equivalence-tests-and-sample-size.html#defining-a-zero-effect"><i class="fa fa-check"></i><b>9.6</b> Defining a zero effect</a></li>
<li class="chapter" data-level="9.7" data-path="equivalence-tests-and-sample-size.html"><a href="equivalence-tests-and-sample-size.html#equivalence---repeated-measures"><i class="fa fa-check"></i><b>9.7</b> Equivalence - repeated measures</a><ul>
<li class="chapter" data-level="9.7.1" data-path="equivalence-tests-and-sample-size.html"><a href="equivalence-tests-and-sample-size.html#raw-units"><i class="fa fa-check"></i><b>9.7.1</b> Raw units</a></li>
<li class="chapter" data-level="9.7.2" data-path="populations.html"><a href="populations.html#standardized-units"><i class="fa fa-check"></i><b>9.7.2</b> Standardized units</a></li>
</ul></li>
<li class="chapter" data-level="9.8" data-path="equivalence-tests-and-sample-size.html"><a href="equivalence-tests-and-sample-size.html#equivalence---independent-groups"><i class="fa fa-check"></i><b>9.8</b> Equivalence - Independent groups</a><ul>
<li class="chapter" data-level="9.8.1" data-path="equivalence-tests-and-sample-size.html"><a href="equivalence-tests-and-sample-size.html#raw-units-1"><i class="fa fa-check"></i><b>9.8.1</b> Raw units</a></li>
<li class="chapter" data-level="9.8.2" data-path="equivalence-tests-and-sample-size.html"><a href="equivalence-tests-and-sample-size.html#standardized-units-1"><i class="fa fa-check"></i><b>9.8.2</b> Standardized units</a></li>
</ul></li>
<li class="chapter" data-level="9.9" data-path="equivalence-tests-and-sample-size.html"><a href="equivalence-tests-and-sample-size.html#equivalence-correlation"><i class="fa fa-check"></i><b>9.9</b> Equivalence Correlation</a></li>
<li class="chapter" data-level="9.10" data-path="equivalence-tests-and-sample-size.html"><a href="equivalence-tests-and-sample-size.html#sample-sizes-for-equivalence-testing"><i class="fa fa-check"></i><b>9.10</b> Sample sizes for equivalence testing</a><ul>
<li class="chapter" data-level="9.10.1" data-path="equivalence-tests-and-sample-size.html"><a href="equivalence-tests-and-sample-size.html#independent-t-test"><i class="fa fa-check"></i><b>9.10.1</b> Independent <em>t</em>-test</a></li>
<li class="chapter" data-level="9.10.2" data-path="equivalence-tests-and-sample-size.html"><a href="equivalence-tests-and-sample-size.html#repeated-t-test"><i class="fa fa-check"></i><b>9.10.2</b> Repeated <em>t</em>-test</a></li>
<li class="chapter" data-level="9.10.3" data-path="equivalence-tests-and-sample-size.html"><a href="equivalence-tests-and-sample-size.html#correlation-1"><i class="fa fa-check"></i><b>9.10.3</b> Correlation</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="10" data-path="precision-and-sample-size.html"><a href="precision-and-sample-size.html"><i class="fa fa-check"></i><b>10</b> Precision and sample size</a><ul>
<li class="chapter" data-level="10.1" data-path="handling-data-with-the-tidyverse.html"><a href="handling-data-with-the-tidyverse.html#required"><i class="fa fa-check"></i><b>10.1</b> Required</a></li>
<li class="chapter" data-level="10.2" data-path="sampling-accuracy.html"><a href="sampling-accuracy.html#overview"><i class="fa fa-check"></i><b>10.2</b> Overview</a></li>
<li class="chapter" data-level="10.3" data-path="precision-and-sample-size.html"><a href="precision-and-sample-size.html#precision"><i class="fa fa-check"></i><b>10.3</b> Precision</a><ul>
<li class="chapter" data-level="10.3.1" data-path="precision-and-sample-size.html"><a href="precision-and-sample-size.html#precision-independent-t-test"><i class="fa fa-check"></i><b>10.3.1</b> Precision Independent <em>t</em>-test</a></li>
<li class="chapter" data-level="10.3.2" data-path="precision-and-sample-size.html"><a href="precision-and-sample-size.html#precision-repeated-t-test"><i class="fa fa-check"></i><b>10.3.2</b> Precision Repeated <em>t</em>-test</a></li>
<li class="chapter" data-level="10.3.3" data-path="precision-and-sample-size.html"><a href="precision-and-sample-size.html#precision-correlation"><i class="fa fa-check"></i><b>10.3.3</b> Precision Correlation</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="11" data-path="starting-your-research.html"><a href="starting-your-research.html"><i class="fa fa-check"></i><b>11</b> Starting your research</a><ul>
<li class="chapter" data-level="11.1" data-path="starting-your-research.html"><a href="starting-your-research.html#required-packages"><i class="fa fa-check"></i><b>11.1</b> Required Packages</a></li>
<li class="chapter" data-level="11.2" data-path="handling-data-with-the-tidyverse.html"><a href="handling-data-with-the-tidyverse.html#objective"><i class="fa fa-check"></i><b>11.2</b> Objective</a></li>
<li class="chapter" data-level="11.3" data-path="starting-your-research.html"><a href="starting-your-research.html#begin-with-the-end-in-mind"><i class="fa fa-check"></i><b>11.3</b> Begin with the end in mind</a><ul>
<li class="chapter" data-level="11.3.1" data-path="starting-your-research.html"><a href="starting-your-research.html#structuring-data-obtaining-tidy-data"><i class="fa fa-check"></i><b>11.3.1</b> Structuring data: Obtaining tidy data</a></li>
</ul></li>
<li class="chapter" data-level="11.4" data-path="starting-your-research.html"><a href="starting-your-research.html#data-collection-considerations"><i class="fa fa-check"></i><b>11.4</b> Data collection considerations</a><ul>
<li class="chapter" data-level="11.4.1" data-path="starting-your-research.html"><a href="starting-your-research.html#naming-conventions"><i class="fa fa-check"></i><b>11.4.1</b> Naming conventions</a></li>
<li class="chapter" data-level="11.4.2" data-path="starting-your-research.html"><a href="starting-your-research.html#likert-type-items"><i class="fa fa-check"></i><b>11.4.2</b> Likert-type items</a></li>
<li class="chapter" data-level="11.4.3" data-path="starting-your-research.html"><a href="starting-your-research.html#anova-between"><i class="fa fa-check"></i><b>11.4.3</b> ANOVA between</a></li>
<li class="chapter" data-level="11.4.4" data-path="starting-your-research.html"><a href="starting-your-research.html#anova-within"><i class="fa fa-check"></i><b>11.4.4</b> ANOVA within</a></li>
</ul></li>
<li class="chapter" data-level="11.5" data-path="starting-your-research.html"><a href="starting-your-research.html#following-the-examples"><i class="fa fa-check"></i><b>11.5</b> Following the examples</a></li>
<li class="chapter" data-level="11.6" data-path="starting-your-research.html"><a href="starting-your-research.html#entering-data-into-spreadsheets"><i class="fa fa-check"></i><b>11.6</b> Entering data into spreadsheets</a></li>
<li class="chapter" data-level="11.7" data-path="starting-your-research.html"><a href="starting-your-research.html#experiment-between"><i class="fa fa-check"></i><b>11.7</b> Experiment: Between</a><ul>
<li class="chapter" data-level="11.7.1" data-path="starting-your-research.html"><a href="starting-your-research.html#creating-factors"><i class="fa fa-check"></i><b>11.7.1</b> Creating factors</a></li>
<li class="chapter" data-level="11.7.2" data-path="starting-your-research.html"><a href="starting-your-research.html#factor-screening"><i class="fa fa-check"></i><b>11.7.2</b> Factor screening</a></li>
<li class="chapter" data-level="11.7.3" data-path="starting-your-research.html"><a href="starting-your-research.html#numeric-screening"><i class="fa fa-check"></i><b>11.7.3</b> Numeric screening</a></li>
</ul></li>
<li class="chapter" data-level="11.8" data-path="starting-your-research.html"><a href="starting-your-research.html#experiment-within-one-way"><i class="fa fa-check"></i><b>11.8</b> Experiment: Within one-way</a><ul>
<li class="chapter" data-level="11.8.1" data-path="starting-your-research.html"><a href="starting-your-research.html#creating-factors-1"><i class="fa fa-check"></i><b>11.8.1</b> Creating factors</a></li>
<li class="chapter" data-level="11.8.2" data-path="starting-your-research.html"><a href="starting-your-research.html#factor-screening-1"><i class="fa fa-check"></i><b>11.8.2</b> Factor screening</a></li>
<li class="chapter" data-level="11.8.3" data-path="starting-your-research.html"><a href="starting-your-research.html#numeric-screening-1"><i class="fa fa-check"></i><b>11.8.3</b> Numeric screening</a></li>
<li class="chapter" data-level="11.8.4" data-path="starting-your-research.html"><a href="starting-your-research.html#pivot-to-tidy-data"><i class="fa fa-check"></i><b>11.8.4</b> Pivot to tidy data</a></li>
</ul></li>
<li class="chapter" data-level="11.9" data-path="starting-your-research.html"><a href="starting-your-research.html#experiment-within-n-way"><i class="fa fa-check"></i><b>11.9</b> Experiment: Within N-way</a><ul>
<li class="chapter" data-level="11.9.1" data-path="starting-your-research.html"><a href="starting-your-research.html#creating-factors-2"><i class="fa fa-check"></i><b>11.9.1</b> Creating factors</a></li>
<li class="chapter" data-level="11.9.2" data-path="starting-your-research.html"><a href="starting-your-research.html#factor-screening-2"><i class="fa fa-check"></i><b>11.9.2</b> Factor screening</a></li>
<li class="chapter" data-level="11.9.3" data-path="starting-your-research.html"><a href="starting-your-research.html#numeric-screening-2"><i class="fa fa-check"></i><b>11.9.3</b> Numeric screening</a></li>
<li class="chapter" data-level="11.9.4" data-path="starting-your-research.html"><a href="starting-your-research.html#pivot-to-tidy-data-1"><i class="fa fa-check"></i><b>11.9.4</b> Pivot to tidy data</a></li>
</ul></li>
<li class="chapter" data-level="11.10" data-path="starting-your-research.html"><a href="starting-your-research.html#surveys-single-occassion"><i class="fa fa-check"></i><b>11.10</b> Surveys: Single Occassion</a><ul>
<li class="chapter" data-level="11.10.1" data-path="starting-your-research.html"><a href="starting-your-research.html#creating-factors-3"><i class="fa fa-check"></i><b>11.10.1</b> Creating factors</a></li>
<li class="chapter" data-level="11.10.2" data-path="starting-your-research.html"><a href="starting-your-research.html#factor-screening-3"><i class="fa fa-check"></i><b>11.10.2</b> Factor screening</a></li>
<li class="chapter" data-level="11.10.3" data-path="starting-your-research.html"><a href="starting-your-research.html#numeric-screening-3"><i class="fa fa-check"></i><b>11.10.3</b> Numeric screening</a></li>
<li class="chapter" data-level="11.10.4" data-path="starting-your-research.html"><a href="starting-your-research.html#scale-scores"><i class="fa fa-check"></i><b>11.10.4</b> Scale scores</a></li>
</ul></li>
<li class="chapter" data-level="11.11" data-path="starting-your-research.html"><a href="starting-your-research.html#surveys-multiple-occasions"><i class="fa fa-check"></i><b>11.11</b> Surveys: Multiple Occasions</a><ul>
<li class="chapter" data-level="11.11.1" data-path="starting-your-research.html"><a href="starting-your-research.html#creating-factors-4"><i class="fa fa-check"></i><b>11.11.1</b> Creating factors</a></li>
<li class="chapter" data-level="11.11.2" data-path="starting-your-research.html"><a href="starting-your-research.html#factor-screening-4"><i class="fa fa-check"></i><b>11.11.2</b> Factor screening</a></li>
<li class="chapter" data-level="11.11.3" data-path="starting-your-research.html"><a href="starting-your-research.html#numeric-screening-4"><i class="fa fa-check"></i><b>11.11.3</b> Numeric screening</a></li>
<li class="chapter" data-level="11.11.4" data-path="starting-your-research.html"><a href="starting-your-research.html#scale-scores-1"><i class="fa fa-check"></i><b>11.11.4</b> Scale scores</a></li>
<li class="chapter" data-level="11.11.5" data-path="starting-your-research.html"><a href="starting-your-research.html#pivot-to-tidy-data-2"><i class="fa fa-check"></i><b>11.11.5</b> Pivot to tidy data</a></li>
</ul></li>
<li class="chapter" data-level="11.12" data-path="starting-your-research.html"><a href="starting-your-research.html#basic-descriptive-statistics"><i class="fa fa-check"></i><b>11.12</b> Basic descriptive statistics</a><ul>
<li class="chapter" data-level="11.12.1" data-path="starting-your-research.html"><a href="starting-your-research.html#skim"><i class="fa fa-check"></i><b>11.12.1</b> skim()</a></li>
<li class="chapter" data-level="11.12.2" data-path="starting-your-research.html"><a href="starting-your-research.html#apa.cor.table"><i class="fa fa-check"></i><b>11.12.2</b> apa.cor.table()</a></li>
<li class="chapter" data-level="11.12.3" data-path="starting-your-research.html"><a href="starting-your-research.html#tidyverse"><i class="fa fa-check"></i><b>11.12.3</b> tidyverse</a></li>
<li class="chapter" data-level="11.12.4" data-path="starting-your-research.html"><a href="starting-your-research.html#cronbachs-alpha"><i class="fa fa-check"></i><b>11.12.4</b> Cronbach’s alpha</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="12" data-path="positive-predictive-value.html"><a href="positive-predictive-value.html"><i class="fa fa-check"></i><b>12</b> Positive Predictive Value</a><ul>
<li class="chapter" data-level="12.1" data-path="handling-data-with-the-tidyverse.html"><a href="handling-data-with-the-tidyverse.html#required"><i class="fa fa-check"></i><b>12.1</b> Required</a></li>
<li class="chapter" data-level="12.2" data-path="sampling-accuracy.html"><a href="sampling-accuracy.html#overview"><i class="fa fa-check"></i><b>12.2</b> Overview</a></li>
<li class="chapter" data-level="12.3" data-path="positive-predictive-value.html"><a href="positive-predictive-value.html#informal-explanation"><i class="fa fa-check"></i><b>12.3</b> Informal explanation</a><ul>
<li class="chapter" data-level="12.3.1" data-path="positive-predictive-value.html"><a href="positive-predictive-value.html#probability-of-an-effect"><i class="fa fa-check"></i><b>12.3.1</b> Probability of an effect</a></li>
<li class="chapter" data-level="12.3.2" data-path="positive-predictive-value.html"><a href="positive-predictive-value.html#type-i-error"><i class="fa fa-check"></i><b>12.3.2</b> Type I Error</a></li>
<li class="chapter" data-level="12.3.3" data-path="positive-predictive-value.html"><a href="positive-predictive-value.html#power"><i class="fa fa-check"></i><b>12.3.3</b> Power</a></li>
<li class="chapter" data-level="12.3.4" data-path="positive-predictive-value.html"><a href="positive-predictive-value.html#calculating-ppv"><i class="fa fa-check"></i><b>12.3.4</b> Calculating PPV</a></li>
</ul></li>
<li class="chapter" data-level="12.4" data-path="positive-predictive-value.html"><a href="positive-predictive-value.html#formal-explanation"><i class="fa fa-check"></i><b>12.4</b> Formal explanation</a><ul>
<li class="chapter" data-level="12.4.1" data-path="positive-predictive-value.html"><a href="positive-predictive-value.html#no-effect"><i class="fa fa-check"></i><b>12.4.1</b> No effect</a></li>
<li class="chapter" data-level="12.4.2" data-path="positive-predictive-value.html"><a href="positive-predictive-value.html#effect"><i class="fa fa-check"></i><b>12.4.2</b> Effect</a></li>
<li class="chapter" data-level="12.4.3" data-path="positive-predictive-value.html"><a href="positive-predictive-value.html#calculation"><i class="fa fa-check"></i><b>12.4.3</b> Calculation</a></li>
<li class="chapter" data-level="12.4.4" data-path="positive-predictive-value.html"><a href="positive-predictive-value.html#alternative-calculation"><i class="fa fa-check"></i><b>12.4.4</b> Alternative calculation</a></li>
<li class="chapter" data-level="12.4.5" data-path="positive-predictive-value.html"><a href="positive-predictive-value.html#touchstone"><i class="fa fa-check"></i><b>12.4.5</b> Touchstone</a></li>
</ul></li>
<li class="chapter" data-level="12.5" data-path="positive-predictive-value.html"><a href="positive-predictive-value.html#calculating-power-for-your-study"><i class="fa fa-check"></i><b>12.5</b> Calculating power for your study</a><ul>
<li class="chapter" data-level="12.5.1" data-path="positive-predictive-value.html"><a href="positive-predictive-value.html#power-independent-groups-t-test"><i class="fa fa-check"></i><b>12.5.1</b> Power independent groups <span class="math inline">\(t\)</span>-test</a></li>
<li class="chapter" data-level="12.5.2" data-path="positive-predictive-value.html"><a href="positive-predictive-value.html#power-repeated-measures-t-test"><i class="fa fa-check"></i><b>12.5.2</b> Power repeated measures <span class="math inline">\(t\)</span>-test</a></li>
<li class="chapter" data-level="12.5.3" data-path="positive-predictive-value.html"><a href="positive-predictive-value.html#power-correlations"><i class="fa fa-check"></i><b>12.5.3</b> Power correlations</a></li>
<li class="chapter" data-level="12.5.4" data-path="positive-predictive-value.html"><a href="positive-predictive-value.html#equivalence-independent-t-test"><i class="fa fa-check"></i><b>12.5.4</b> Equivalence independent <em>t</em>-test</a></li>
<li class="chapter" data-level="12.5.5" data-path="positive-predictive-value.html"><a href="positive-predictive-value.html#equivalence-repeated-t-test"><i class="fa fa-check"></i><b>12.5.5</b> Equivalence repeated <em>t</em>-test</a></li>
<li class="chapter" data-level="12.5.6" data-path="equivalence-tests-and-sample-size.html"><a href="equivalence-tests-and-sample-size.html#equivalence-correlation"><i class="fa fa-check"></i><b>12.5.6</b> Equivalence correlation</a></li>
</ul></li>
<li class="chapter" data-level="12.6" data-path="positive-predictive-value.html"><a href="positive-predictive-value.html#calculating-ppv-for-your-study"><i class="fa fa-check"></i><b>12.6</b> Calculating PPV for your study</a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="open-science-preregistration.html"><a href="open-science-preregistration.html"><i class="fa fa-check"></i><b>13</b> Open Science Preregistration</a><ul>
<li class="chapter" data-level="13.1" data-path="sampling-accuracy.html"><a href="sampling-accuracy.html#overview"><i class="fa fa-check"></i><b>13.1</b> Overview</a></li>
<li class="chapter" data-level="13.2" data-path="open-science-preregistration.html"><a href="open-science-preregistration.html#daniel-simmons-interview"><i class="fa fa-check"></i><b>13.2</b> Daniel Simmons Interview</a></li>
<li class="chapter" data-level="13.3" data-path="open-science-preregistration.html"><a href="open-science-preregistration.html#preregistration-impact"><i class="fa fa-check"></i><b>13.3</b> Preregistration Impact</a></li>
<li class="chapter" data-level="13.4" data-path="open-science-preregistration.html"><a href="open-science-preregistration.html#preregistration-details"><i class="fa fa-check"></i><b>13.4</b> Preregistration Details</a></li>
<li class="chapter" data-level="13.5" data-path="open-science-preregistration.html"><a href="open-science-preregistration.html#learn-more"><i class="fa fa-check"></i><b>13.5</b> Learn more</a></li>
</ul></li>
<li class="chapter" data-level="14" data-path="research-tools.html"><a href="research-tools.html"><i class="fa fa-check"></i><b>14</b> Research Tools</a><ul>
<li class="chapter" data-level="14.1" data-path="research-tools.html"><a href="research-tools.html#statcheck"><i class="fa fa-check"></i><b>14.1</b> statcheck</a><ul>
<li class="chapter" data-level="14.1.1" data-path="research-tools.html"><a href="research-tools.html#statcheck-software"><i class="fa fa-check"></i><b>14.1.1</b> statcheck software</a></li>
<li class="chapter" data-level="14.1.2" data-path="research-tools.html"><a href="research-tools.html#statcheck-website"><i class="fa fa-check"></i><b>14.1.2</b> statcheck website</a></li>
<li class="chapter" data-level="14.1.3" data-path="research-tools.html"><a href="research-tools.html#statcheck-and-word"><i class="fa fa-check"></i><b>14.1.3</b> statcheck and Word</a></li>
<li class="chapter" data-level="14.1.4" data-path="research-tools.html"><a href="research-tools.html#statcheck-process"><i class="fa fa-check"></i><b>14.1.4</b> statcheck process</a></li>
<li class="chapter" data-level="14.1.5" data-path="research-tools.html"><a href="research-tools.html#statcheck-validity"><i class="fa fa-check"></i><b>14.1.5</b> statcheck validity</a></li>
</ul></li>
<li class="chapter" data-level="14.2" data-path="research-tools.html"><a href="research-tools.html#rmarkdown-bookdown"><i class="fa fa-check"></i><b>14.2</b> rmarkdown / bookdown</a></li>
<li class="chapter" data-level="14.3" data-path="research-tools.html"><a href="research-tools.html#papaja"><i class="fa fa-check"></i><b>14.3</b> papaja</a></li>
<li class="chapter" data-level="14.4" data-path="research-tools.html"><a href="research-tools.html#apatables"><i class="fa fa-check"></i><b>14.4</b> apaTables</a></li>
<li class="chapter" data-level="14.5" data-path="research-tools.html"><a href="research-tools.html#retracted-articles"><i class="fa fa-check"></i><b>14.5</b> Retracted articles</a><ul>
<li class="chapter" data-level="14.5.1" data-path="research-tools.html"><a href="research-tools.html#doi"><i class="fa fa-check"></i><b>14.5.1</b> DOI</a></li>
<li class="chapter" data-level="14.5.2" data-path="research-tools.html"><a href="research-tools.html#retractiondatabase.org"><i class="fa fa-check"></i><b>14.5.2</b> retractiondatabase.org</a></li>
<li class="chapter" data-level="14.5.3" data-path="research-tools.html"><a href="research-tools.html#openretractions.com"><i class="fa fa-check"></i><b>14.5.3</b> openretractions.com</a></li>
<li class="chapter" data-level="14.5.4" data-path="research-tools.html"><a href="research-tools.html#retractcheck"><i class="fa fa-check"></i><b>14.5.4</b> retractcheck</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="15" data-path="nhst-and-sample-size.html"><a href="nhst-and-sample-size.html#correlations"><i class="fa fa-check"></i><b>15</b> Correlations</a><ul>
<li class="chapter" data-level="15.1" data-path="correlations.html"><a href="correlations.html"><i class="fa fa-check"></i><b>15.1</b> Obtaining a data set from the internet</a></li>
<li class="chapter" data-level="15.2" data-path="correlations.html"><a href="correlations.html#creating-analytic-data"><i class="fa fa-check"></i><b>15.2</b> Creating analytic data</a><ul>
<li class="chapter" data-level="15.2.1" data-path="correlations.html"><a href="correlations.html#extracting-the-relevant-columns"><i class="fa fa-check"></i><b>15.2.1</b> Extracting the relevant columns</a></li>
</ul></li>
<li class="chapter" data-level="15.3" data-path="starting-your-research.html"><a href="starting-your-research.html#creating-factors"><i class="fa fa-check"></i><b>15.3</b> Creating factors</a></li>
<li class="chapter" data-level="15.4" data-path="correlations.html"><a href="correlations.html#all-the-data-single-correlation"><i class="fa fa-check"></i><b>15.4</b> All the data: Single Correlation</a></li>
</ul></li>
<li class="chapter" data-level="16" data-path="all-the-data-several-correlations.html"><a href="all-the-data-several-correlations.html"><i class="fa fa-check"></i><b>16</b> All the data: Several correlations</a><ul>
<li class="chapter" data-level="16.1" data-path="all-the-data-several-correlations.html"><a href="all-the-data-several-correlations.html#subgroup-analyses"><i class="fa fa-check"></i><b>16.1</b> Subgroup Analyses</a><ul>
<li class="chapter" data-level="16.1.1" data-path="all-the-data-several-correlations.html"><a href="all-the-data-several-correlations.html#single-subgroup"><i class="fa fa-check"></i><b>16.1.1</b> <em>Single</em> subgroup</a></li>
<li class="chapter" data-level="16.1.2" data-path="all-the-data-several-correlations.html"><a href="all-the-data-several-correlations.html#multiple-subgroups"><i class="fa fa-check"></i><b>16.1.2</b> <em>Multiple</em> subgroups</a></li>
<li class="chapter" data-level="16.1.3" data-path="all-the-data-several-correlations.html"><a href="all-the-data-several-correlations.html#background"><i class="fa fa-check"></i><b>16.1.3</b> Background</a></li>
<li class="chapter" data-level="16.1.4" data-path="all-the-data-several-correlations.html"><a href="all-the-data-several-correlations.html#implementation"><i class="fa fa-check"></i><b>16.1.4</b> Implementation</a></li>
</ul></li>
<li class="chapter" data-level="16.2" data-path="all-the-data-several-correlations.html"><a href="all-the-data-several-correlations.html#comparing-correlations"><i class="fa fa-check"></i><b>16.2</b> Comparing correlations</a></li>
<li class="chapter" data-level="16.3" data-path="all-the-data-several-correlations.html"><a href="all-the-data-several-correlations.html#comparing-correlations-within-a-data-set"><i class="fa fa-check"></i><b>16.3</b> Comparing correlations within a data set</a><ul>
<li class="chapter" data-level="16.3.1" data-path="all-the-data-several-correlations.html"><a href="all-the-data-several-correlations.html#non-overlapping-correlations"><i class="fa fa-check"></i><b>16.3.1</b> Non-overlapping correlations</a></li>
<li class="chapter" data-level="16.3.2" data-path="all-the-data-several-correlations.html"><a href="all-the-data-several-correlations.html#overlapping-correlations"><i class="fa fa-check"></i><b>16.3.2</b> Overlapping correlations</a></li>
</ul></li>
<li class="chapter" data-level="16.4" data-path="all-the-data-several-correlations.html"><a href="all-the-data-several-correlations.html#comparing-correlations-between-data-sets"><i class="fa fa-check"></i><b>16.4</b> Comparing correlations between data sets</a></li>
<li class="chapter" data-level="16.5" data-path="all-the-data-several-correlations.html"><a href="all-the-data-several-correlations.html#create-seperate-data-files-for-men-and-women-if-needed"><i class="fa fa-check"></i><b>16.5</b> Create seperate data files for men and women (if needed)</a></li>
<li class="chapter" data-level="16.6" data-path="all-the-data-several-correlations.html"><a href="all-the-data-several-correlations.html#check-out-the-subgroup-columns"><i class="fa fa-check"></i><b>16.6</b> Check out the subgroup columns</a></li>
<li class="chapter" data-level="16.7" data-path="all-the-data-several-correlations.html"><a href="all-the-data-several-correlations.html#check-out-the-subgroup-correlations"><i class="fa fa-check"></i><b>16.7</b> Check out the subgroup correlations</a><ul>
<li class="chapter" data-level="16.7.1" data-path="all-the-data-several-correlations.html"><a href="all-the-data-several-correlations.html#correlations-for-men"><i class="fa fa-check"></i><b>16.7.1</b> Correlations for men</a></li>
<li class="chapter" data-level="16.7.2" data-path="all-the-data-several-correlations.html"><a href="all-the-data-several-correlations.html#correlations-for-women"><i class="fa fa-check"></i><b>16.7.2</b> Correlations for women</a></li>
</ul></li>
<li class="chapter" data-level="16.8" data-path="all-the-data-several-correlations.html"><a href="all-the-data-several-correlations.html#actual-comparison-of-a1-e1-correlation-for-men-to-the-a1-e1-correlation-for-women"><i class="fa fa-check"></i><b>16.8</b> Actual comparison of (a1, e1) correlation for men to the (a1, e1) correlation for women</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://bookdown.org" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Welcome!</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="all-the-data-several-correlations" class="section level1">
<h1><span class="header-section-number">Chapter 16</span> All the data: Several correlations</h1>
<p>We can view the correlations between all three variables using the apaTables packages.</p>
<div class="sourceCode" id="cb593"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb593-1"><a href="all-the-data-several-correlations.html#cb593-1"></a><span class="kw">library</span>(apaTables)</span>
<span id="cb593-2"><a href="all-the-data-several-correlations.html#cb593-2"></a></span>
<span id="cb593-3"><a href="all-the-data-several-correlations.html#cb593-3"></a><span class="kw">apa.cor.table</span>(analytic_data)</span></code></pre></div>
<pre><code>## 
## 
## Means, standard deviations, and correlations with confidence intervals
##  
## 
##   Variable   M     SD    1           2           
##   1. class   50.37 29.08                         
##                                                  
##   2. extrav  5.21  1.26  .02                     
##                          [-.02, .06]             
##                                                  
##   3. popular 5.08  1.38  .03         .32**       
##                          [-.01, .08] [.28, .35]  
##                                                  
##   4. texp    14.26 6.55  .07**       -.39**      
##                          [.03, .12]  [-.42, -.35]
##                                                  
##   3         
##             
##             
##             
##             
##             
##             
##             
##             
##   .29**     
##   [.25, .33]
##             
## 
## Note. M and SD are used to represent mean and standard deviation, respectively.
## Values in square brackets indicate the 95% confidence interval.
## The confidence interval is a plausible range of population correlations 
## that could have caused the sample correlation (Cumming, 2014).
## * indicates p &lt; .05. ** indicates p &lt; .01.
## </code></pre>
<p>Before interpreting a correlation, it is important to view the scatter plot. You can obtain a scatter plot for all possible correlations in analytic_data (i.e., every correlation in the table above) using the pairs.panels command from the psych package. Note we do not use the the library command for the psych package we use psych:: as per below. This creates the desired plot. The argument lm = TRUE ensures we also get a regression line on these plots.</p>
<div class="sourceCode" id="cb595"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb595-1"><a href="all-the-data-several-correlations.html#cb595-1"></a><span class="kw">library</span>(GGally)</span>
<span id="cb595-2"><a href="all-the-data-several-correlations.html#cb595-2"></a><span class="kw">ggpairs</span>(<span class="dt">data =</span> analytic_data)</span></code></pre></div>
<p><img src="bookdown_files/figure-html/unnamed-chunk-434-1.png" width="672" /></p>
<div id="subgroup-analyses" class="section level2">
<h2><span class="header-section-number">16.1</span> Subgroup Analyses</h2>
<div id="single-subgroup" class="section level3">
<h3><span class="header-section-number">16.1.1</span> <em>Single</em> subgroup</h3>
<p>We want to obtain a correlation between extraversion and popularity for just the students in class 5. To do so, we use the <em>filter</em> command from the <strong>tidyverse</strong> package.</p>
<div class="sourceCode" id="cb596"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb596-1"><a href="all-the-data-several-correlations.html#cb596-1"></a>analytic_data_class_is_<span class="dv">5</span> &lt;-<span class="st"> </span><span class="kw">filter</span>(analytic_data, class <span class="op">==</span><span class="st"> </span><span class="dv">5</span>)</span></code></pre></div>
<p>As you can see with the <em>print</em> command we now have just class 5 in the data set my_data.class.is.5.</p>
<div class="sourceCode" id="cb597"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb597-1"><a href="all-the-data-several-correlations.html#cb597-1"></a><span class="kw">print</span>(analytic_data_class_is_<span class="dv">5</span>)</span></code></pre></div>
<p>To obtain the correlation for class 5:</p>
<div class="sourceCode" id="cb598"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb598-1"><a href="all-the-data-several-correlations.html#cb598-1"></a><span class="kw">cor.test</span>(<span class="dt">x =</span> analytic_data_class_is_<span class="dv">5</span><span class="op">$</span>extrav,</span>
<span id="cb598-2"><a href="all-the-data-several-correlations.html#cb598-2"></a>         <span class="dt">y =</span> analytic_data_class_is_<span class="dv">5</span><span class="op">$</span>popular)</span></code></pre></div>
<pre><code>## 
## 	Pearson&#39;s product-moment correlation
## 
## data:  analytic_data_class_is_5$extrav and analytic_data_class_is_5$popular
## t = 3.6, df = 19, p-value = 0.002
## alternative hypothesis: true correlation is not equal to 0
## 95 percent confidence interval:
##  0.2899 0.8403
## sample estimates:
##    cor 
## 0.6413</code></pre>
</div>
<div id="multiple-subgroups" class="section level3">
<h3><span class="header-section-number">16.1.2</span> <em>Multiple</em> subgroups</h3>
</div>
<div id="background" class="section level3">
<h3><span class="header-section-number">16.1.3</span> Background</h3>
<p>Before we can calculate correlation for subgroups we need to know how R stores/handles information</p>
<p>This next bit is about how R works - not how you would typically run the analysis. Going into detail about how R works will help you to understand what we do later in this exercise when we encounter subgroups. With R, you can store the result of any analysis in a variable. In this case, you can store the correlation information in a variable we will call my_cor_result.</p>
<div class="sourceCode" id="cb600"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb600-1"><a href="all-the-data-several-correlations.html#cb600-1"></a>my_cor_result &lt;-<span class="st"> </span><span class="kw">cor.test</span>(<span class="dt">x =</span> analytic_data<span class="op">$</span>extrav,</span>
<span id="cb600-2"><a href="all-the-data-several-correlations.html#cb600-2"></a>                          <span class="dt">y =</span> analytic_data<span class="op">$</span>popular)</span></code></pre></div>
<p>If you type my_cor_result you get all the information:</p>
<div class="sourceCode" id="cb601"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb601-1"><a href="all-the-data-several-correlations.html#cb601-1"></a>my_cor_result</span></code></pre></div>
<pre><code>## 
## 	Pearson&#39;s product-moment correlation
## 
## data:  analytic_data$extrav and analytic_data$popular
## t = 15, df = 1998, p-value &lt;2e-16
## alternative hypothesis: true correlation is not equal to 0
## 95 percent confidence interval:
##  0.2758 0.3547
## sample estimates:
##    cor 
## 0.3158</code></pre>
<p>But you can see the structure of the resulting information with the str() function.</p>
<div class="sourceCode" id="cb603"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb603-1"><a href="all-the-data-several-correlations.html#cb603-1"></a><span class="kw">str</span>(my_cor_result)</span></code></pre></div>
<pre><code>## List of 9
##  $ statistic  : Named num 14.9
##   ..- attr(*, &quot;names&quot;)= chr &quot;t&quot;
##  $ parameter  : Named int 1998
##   ..- attr(*, &quot;names&quot;)= chr &quot;df&quot;
##  $ p.value    : num 1.48e-47
##  $ estimate   : Named num 0.316
##   ..- attr(*, &quot;names&quot;)= chr &quot;cor&quot;
##  $ null.value : Named num 0
##   ..- attr(*, &quot;names&quot;)= chr &quot;correlation&quot;
##  $ alternative: chr &quot;two.sided&quot;
##  $ method     : chr &quot;Pearson&#39;s product-moment correlation&quot;
##  $ data.name  : chr &quot;analytic_data$extrav and analytic_data$popular&quot;
##  $ conf.int   : num [1:2] 0.276 0.355
##   ..- attr(*, &quot;conf.level&quot;)= num 0.95
##  - attr(*, &quot;class&quot;)= chr &quot;htest&quot;</code></pre>
<p>From the above information you can see the correlation value is stored under the label <strong>estimate</strong>. Therefore, you can get just the correlation by typing the following:</p>
<div class="sourceCode" id="cb605"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb605-1"><a href="all-the-data-several-correlations.html#cb605-1"></a>my_cor_result<span class="op">$</span>estimate</span></code></pre></div>
<pre><code>##    cor 
## 0.3158</code></pre>
<p>You can use this information to access just the correlation in a later section when we deal with subgroup analyses.</p>
</div>
<div id="implementation" class="section level3">
<h3><span class="header-section-number">16.1.4</span> Implementation</h3>
<p>If you’re interested in getting a correlation for 100 classes, there is any easy way to do so. We begin by using the <em>group_by</em> command from the <strong>tidyverse</strong> package.</p>
<div class="sourceCode" id="cb607"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb607-1"><a href="all-the-data-several-correlations.html#cb607-1"></a>analytic_data_grouped_by_class &lt;-<span class="st"> </span><span class="kw">group_by</span>(analytic_data, class)</span></code></pre></div>
<p>Then you calculate the correlation for each group:</p>
<div class="sourceCode" id="cb608"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb608-1"><a href="all-the-data-several-correlations.html#cb608-1"></a>cor_by_group &lt;-<span class="st"> </span><span class="kw">summarise</span>(analytic_data_grouped_by_class, </span>
<span id="cb608-2"><a href="all-the-data-several-correlations.html#cb608-2"></a>                          <span class="dt">cor_for_class =</span> <span class="kw">cor.test</span>(<span class="dt">x =</span> extrav,</span>
<span id="cb608-3"><a href="all-the-data-several-correlations.html#cb608-3"></a>                                                   <span class="dt">y =</span> popular)<span class="op">$</span>estimate)</span></code></pre></div>
<pre><code>## `summarise()` ungrouping output (override with `.groups` argument)</code></pre>
<p>You can then print the correlation for the first few groups with the print command. Notice that the result for class 5 (i.e., <em>r</em> = .64) is the same as when we did analyses specifically for group 5 in the previous section.</p>
<div class="sourceCode" id="cb610"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb610-1"><a href="all-the-data-several-correlations.html#cb610-1"></a><span class="kw">print</span>(cor_by_group)</span></code></pre></div>
<pre><code>## # A tibble: 100 x 2
##    class cor_for_class
##    &lt;dbl&gt;         &lt;dbl&gt;
##  1     1         0.515
##  2     2         0.656
##  3     3         0.576
##  4     4         0.519
##  5     5         0.641
##  6     6         0.647
##  7     7         0.231
##  8     8         0.700
##  9     9         0.623
## 10    10         0.278
## # … with 90 more rows</code></pre>
<p>You can print all the rows with:</p>
<div class="sourceCode" id="cb612"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb612-1"><a href="all-the-data-several-correlations.html#cb612-1"></a><span class="kw">print</span>(<span class="kw">as.data.frame</span>(cor_by_group))</span></code></pre></div>
<p>As previously noted, it’s a good idea to inspect the scatter plot for each correlation you calculate. In this case, that means you want a plot of the correlation for each group. To do so, we get the subset of the groups you want (e.g., just groups 15 to 30) using the <em>filter</em> command from the <strong>tidyverse</strong> package. This command creates a new data set with just the desired groups. In the example below we create a data set that contains just groups 15 to 30.</p>
<div class="sourceCode" id="cb613"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb613-1"><a href="all-the-data-several-correlations.html#cb613-1"></a>analytic_data_groups_<span class="dv">15</span>_to_<span class="dv">30</span> &lt;-<span class="st"> </span><span class="kw">filter</span>(analytic_data_grouped_by_class, </span>
<span id="cb613-2"><a href="all-the-data-several-correlations.html#cb613-2"></a>                                        class <span class="op">&gt;=</span><span class="st"> </span><span class="dv">15</span> <span class="op">&amp;</span><span class="st"> </span>class <span class="op">&lt;=</span><span class="st"> </span><span class="dv">30</span>)</span></code></pre></div>
<p>The scatter plot for those 15 groups is generated by using the <strong>ggplot2</strong> package with the commands below. Don’t forget to install the tidyverse package (which contains ggplot2) if you haven’t used it before.</p>
<div class="sourceCode" id="cb614"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb614-1"><a href="all-the-data-several-correlations.html#cb614-1"></a><span class="kw">library</span>(tidyverse)</span>
<span id="cb614-2"><a href="all-the-data-several-correlations.html#cb614-2"></a></span>
<span id="cb614-3"><a href="all-the-data-several-correlations.html#cb614-3"></a>my_scatter &lt;-<span class="st"> </span><span class="kw">ggplot</span>(<span class="dt">data =</span> analytic_data_groups_<span class="dv">15</span>_to_<span class="dv">30</span>,</span>
<span id="cb614-4"><a href="all-the-data-several-correlations.html#cb614-4"></a>                     <span class="dt">mapping =</span> <span class="kw">aes</span>(<span class="dt">x =</span> extrav, <span class="dt">y =</span> popular)) <span class="op">+</span></span>
<span id="cb614-5"><a href="all-the-data-several-correlations.html#cb614-5"></a><span class="st">               </span><span class="kw">geom_point</span>() <span class="op">+</span></span>
<span id="cb614-6"><a href="all-the-data-several-correlations.html#cb614-6"></a><span class="st">               </span><span class="kw">facet_wrap</span>(<span class="op">~</span>class)</span>
<span id="cb614-7"><a href="all-the-data-several-correlations.html#cb614-7"></a></span>
<span id="cb614-8"><a href="all-the-data-several-correlations.html#cb614-8"></a><span class="kw">print</span>(my_scatter)</span></code></pre></div>
<p><img src="bookdown_files/figure-html/unnamed-chunk-447-1.png" width="672" /></p>
<p>You can easily add the regression line for these groups. Notice how the regression line does not extend beyond the data points. This is ideal behavior for the software because regression predictions are not valid beyond the range of the data.</p>
<div class="sourceCode" id="cb615"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb615-1"><a href="all-the-data-several-correlations.html#cb615-1"></a><span class="kw">library</span>(tidyverse)</span>
<span id="cb615-2"><a href="all-the-data-several-correlations.html#cb615-2"></a></span>
<span id="cb615-3"><a href="all-the-data-several-correlations.html#cb615-3"></a>my_scatter &lt;-<span class="st"> </span><span class="kw">ggplot</span>(<span class="dt">data =</span> analytic_data_groups_<span class="dv">15</span>_to_<span class="dv">30</span>,</span>
<span id="cb615-4"><a href="all-the-data-several-correlations.html#cb615-4"></a>                     <span class="dt">mapping =</span> <span class="kw">aes</span>(<span class="dt">x =</span> extrav, <span class="dt">y =</span> popular)) <span class="op">+</span></span>
<span id="cb615-5"><a href="all-the-data-several-correlations.html#cb615-5"></a><span class="st">               </span><span class="kw">geom_point</span>() <span class="op">+</span><span class="st"> </span></span>
<span id="cb615-6"><a href="all-the-data-several-correlations.html#cb615-6"></a><span class="st">               </span><span class="kw">geom_smooth</span>(<span class="dt">method =</span> <span class="st">&quot;lm&quot;</span>,</span>
<span id="cb615-7"><a href="all-the-data-several-correlations.html#cb615-7"></a>                           <span class="dt">se =</span> <span class="ot">FALSE</span>,</span>
<span id="cb615-8"><a href="all-the-data-several-correlations.html#cb615-8"></a>                           <span class="dt">color =</span> <span class="st">&quot;black&quot;</span>) <span class="op">+</span></span>
<span id="cb615-9"><a href="all-the-data-several-correlations.html#cb615-9"></a><span class="st">               </span><span class="kw">facet_wrap</span>(<span class="op">~</span>class)</span>
<span id="cb615-10"><a href="all-the-data-several-correlations.html#cb615-10"></a></span>
<span id="cb615-11"><a href="all-the-data-several-correlations.html#cb615-11"></a><span class="kw">print</span>(my_scatter)</span></code></pre></div>
<pre><code>## `geom_smooth()` using formula &#39;y ~ x&#39;</code></pre>
<p><img src="bookdown_files/figure-html/unnamed-chunk-448-1.png" width="672" /></p>
<p>Now change the geom_smooth command so se = TRUE. Notice the confidence intervals are on the regression lines.</p>
<div class="sourceCode" id="cb617"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb617-1"><a href="all-the-data-several-correlations.html#cb617-1"></a><span class="kw">library</span>(tidyverse)</span>
<span id="cb617-2"><a href="all-the-data-several-correlations.html#cb617-2"></a>my_scatter &lt;-<span class="st"> </span><span class="kw">ggplot</span>(<span class="dt">data =</span> analytic_data_groups_<span class="dv">15</span>_to_<span class="dv">30</span>, </span>
<span id="cb617-3"><a href="all-the-data-several-correlations.html#cb617-3"></a>                     <span class="dt">mapping =</span> <span class="kw">aes</span>(<span class="dt">x =</span> extrav, <span class="dt">y =</span> popular)) <span class="op">+</span></span>
<span id="cb617-4"><a href="all-the-data-several-correlations.html#cb617-4"></a><span class="st">               </span><span class="kw">geom_point</span>() <span class="op">+</span><span class="st"> </span></span>
<span id="cb617-5"><a href="all-the-data-several-correlations.html#cb617-5"></a><span class="st">               </span><span class="kw">geom_smooth</span>(<span class="dt">method =</span> <span class="st">&quot;lm&quot;</span>,</span>
<span id="cb617-6"><a href="all-the-data-several-correlations.html#cb617-6"></a>                           <span class="dt">se =</span> <span class="ot">TRUE</span>,</span>
<span id="cb617-7"><a href="all-the-data-several-correlations.html#cb617-7"></a>                           <span class="dt">color =</span> <span class="st">&quot;black&quot;</span>) <span class="op">+</span></span>
<span id="cb617-8"><a href="all-the-data-several-correlations.html#cb617-8"></a><span class="st">               </span><span class="kw">facet_wrap</span>(<span class="op">~</span>class)</span>
<span id="cb617-9"><a href="all-the-data-several-correlations.html#cb617-9"></a></span>
<span id="cb617-10"><a href="all-the-data-several-correlations.html#cb617-10"></a><span class="kw">print</span>(my_scatter)</span></code></pre></div>
<pre><code>## `geom_smooth()` using formula &#39;y ~ x&#39;</code></pre>
<p><img src="bookdown_files/figure-html/unnamed-chunk-449-1.png" width="672" /></p>
<p>Any ggplot2 graph can be saved (in the project folder) with the ggsave command.
In the command below you save it as a PDF that is 6 inches wide and 6 inches tall. By changing the extension you can save it as several other file types: eps/ps, tex (pictex), pdf, jpeg, tiff, png, bmp, svg and wmf.</p>
<div class="sourceCode" id="cb619"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb619-1"><a href="all-the-data-several-correlations.html#cb619-1"></a><span class="kw">ggsave</span>(<span class="st">&quot;graph_scatter_with_ci.pdf&quot;</span>, </span>
<span id="cb619-2"><a href="all-the-data-several-correlations.html#cb619-2"></a>       <span class="dt">plot =</span> my_scatter, </span>
<span id="cb619-3"><a href="all-the-data-several-correlations.html#cb619-3"></a>       <span class="dt">width =</span> <span class="dv">6</span>, </span>
<span id="cb619-4"><a href="all-the-data-several-correlations.html#cb619-4"></a>       <span class="dt">height =</span> <span class="dv">6</span>)</span></code></pre></div>
</div>
</div>
<div id="comparing-correlations" class="section level2">
<h2><span class="header-section-number">16.2</span> Comparing correlations</h2>
<p>The part of the exercise involves comparing correlations within and across studies.</p>
<div class="sourceCode" id="cb620"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb620-1"><a href="all-the-data-several-correlations.html#cb620-1"></a>bfi &lt;-<span class="st"> </span>psych<span class="op">::</span>bfi</span>
<span id="cb620-2"><a href="all-the-data-several-correlations.html#cb620-2"></a></span>
<span id="cb620-3"><a href="all-the-data-several-correlations.html#cb620-3"></a>bfi &lt;-<span class="st"> </span>bfi <span class="op">%&gt;%</span></span>
<span id="cb620-4"><a href="all-the-data-several-correlations.html#cb620-4"></a><span class="st">  </span><span class="kw">remove_empty</span>(<span class="st">&quot;rows&quot;</span>) <span class="op">%&gt;%</span></span>
<span id="cb620-5"><a href="all-the-data-several-correlations.html#cb620-5"></a><span class="st">  </span><span class="kw">remove_empty</span>(<span class="st">&quot;cols&quot;</span>) <span class="op">%&gt;%</span></span>
<span id="cb620-6"><a href="all-the-data-several-correlations.html#cb620-6"></a><span class="st">  </span><span class="kw">clean_names</span>()</span></code></pre></div>
<div class="sourceCode" id="cb621"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb621-1"><a href="all-the-data-several-correlations.html#cb621-1"></a><span class="kw">glimpse</span>(bfi)</span></code></pre></div>
<pre><code>## Rows: 2,800
## Columns: 28
## $ a1        &lt;int&gt; 2, 2, 5, 4, 2, 6, 2, 4, 4, 2, 4, 2, 5, …
## $ a2        &lt;int&gt; 4, 4, 4, 4, 3, 6, 5, 3, 3, 5, 4, 5, 5, …
## $ a3        &lt;int&gt; 3, 5, 5, 6, 3, 5, 5, 1, 6, 6, 5, 5, 5, …
## $ a4        &lt;int&gt; 4, 2, 4, 5, 4, 6, 3, 5, 3, 6, 6, 5, 6, …
## $ a5        &lt;int&gt; 4, 5, 4, 5, 5, 5, 5, 1, 3, 5, 5, 5, 4, …
## $ c1        &lt;int&gt; 2, 5, 4, 4, 4, 6, 5, 3, 6, 6, 4, 5, 5, …
## $ c2        &lt;int&gt; 3, 4, 5, 4, 4, 6, 4, 2, 6, 5, 3, 4, 4, …
## $ c3        &lt;int&gt; 3, 4, 4, 3, 5, 6, 4, 4, 3, 6, 5, 5, 3, …
## $ c4        &lt;int&gt; 4, 3, 2, 5, 3, 1, 2, 2, 4, 2, 3, 4, 2, …
## $ c5        &lt;int&gt; 4, 4, 5, 5, 2, 3, 3, 4, 5, 1, 2, 5, 2, …
## $ e1        &lt;int&gt; 3, 1, 2, 5, 2, 2, 4, 3, 5, 2, 1, 3, 3, …
## $ e2        &lt;int&gt; 3, 1, 4, 3, 2, 1, 3, 6, 3, 2, 3, 3, 3, …
## $ e3        &lt;int&gt; 3, 6, 4, 4, 5, 6, 4, 4, NA, 4, 2, 4, 3,…
## $ e4        &lt;int&gt; 4, 4, 4, 4, 4, 5, 5, 2, 4, 5, 5, 5, 2, …
## $ e5        &lt;int&gt; 4, 3, 5, 4, 5, 6, 5, 1, 3, 5, 4, 4, 4, …
## $ n1        &lt;int&gt; 3, 3, 4, 2, 2, 3, 1, 6, 5, 5, 3, 4, 1, …
## $ n2        &lt;int&gt; 4, 3, 5, 5, 3, 5, 2, 3, 5, 5, 3, 5, 2, …
## $ n3        &lt;int&gt; 2, 3, 4, 2, 4, 2, 2, 2, 2, 5, 4, 3, 2, …
## $ n4        &lt;int&gt; 2, 5, 2, 4, 4, 2, 1, 6, 3, 2, 2, 2, 2, …
## $ n5        &lt;int&gt; 3, 5, 3, 1, 3, 3, 1, 4, 3, 4, 3, NA, 2,…
## $ o1        &lt;int&gt; 3, 4, 4, 3, 3, 4, 5, 3, 6, 5, 5, 4, 4, …
## $ o2        &lt;int&gt; 6, 2, 2, 3, 3, 3, 2, 2, 6, 1, 3, 6, 2, …
## $ o3        &lt;int&gt; 3, 4, 5, 4, 4, 5, 5, 4, 6, 5, 5, 4, 4, …
## $ o4        &lt;int&gt; 4, 3, 5, 3, 3, 6, 6, 5, 6, 5, 6, 5, 5, …
## $ o5        &lt;int&gt; 3, 3, 2, 5, 3, 1, 1, 3, 1, 2, 3, 4, 2, …
## $ gender    &lt;int&gt; 1, 2, 2, 2, 1, 2, 1, 1, 1, 2, 1, 1, 2, …
## $ education &lt;int&gt; NA, NA, NA, NA, NA, 3, NA, 2, 1, NA, 1,…
## $ age       &lt;int&gt; 16, 18, 17, 17, 17, 21, 18, 19, 19, 17,…</code></pre>
<div class="sourceCode" id="cb623"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb623-1"><a href="all-the-data-several-correlations.html#cb623-1"></a>bfi &lt;-<span class="st"> </span>bfi <span class="op">%&gt;%</span></span>
<span id="cb623-2"><a href="all-the-data-several-correlations.html#cb623-2"></a><span class="st">  </span><span class="kw">select</span>(a1, c1, e1, o1, n1, gender)</span></code></pre></div>
<div class="sourceCode" id="cb624"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb624-1"><a href="all-the-data-several-correlations.html#cb624-1"></a><span class="kw">glimpse</span>(bfi)</span></code></pre></div>
<pre><code>## Rows: 2,800
## Columns: 6
## $ a1     &lt;int&gt; 2, 2, 5, 4, 2, 6, 2, 4, 4, 2, 4, 2, 5, 5, …
## $ c1     &lt;int&gt; 2, 5, 4, 4, 4, 6, 5, 3, 6, 6, 4, 5, 5, 4, …
## $ e1     &lt;int&gt; 3, 1, 2, 5, 2, 2, 4, 3, 5, 2, 1, 3, 3, 2, …
## $ o1     &lt;int&gt; 3, 4, 4, 3, 3, 4, 5, 3, 6, 5, 5, 4, 4, 5, …
## $ n1     &lt;int&gt; 3, 3, 4, 2, 2, 3, 1, 6, 5, 5, 3, 4, 1, 1, …
## $ gender &lt;int&gt; 1, 2, 2, 2, 1, 2, 1, 1, 1, 2, 1, 1, 2, 1, …</code></pre>
<p>Quickly see a condensed correlation matrix using the cor() command. You can specify use = “pairwise.complete.obs” for pairwise correlation - the documentation covers other options. The round(2) command rounds the correlations to two decimal places.</p>
<div class="sourceCode" id="cb626"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb626-1"><a href="all-the-data-several-correlations.html#cb626-1"></a><span class="kw">cor</span>(bfi, <span class="dt">use =</span> <span class="st">&quot;pairwise.complete.obs&quot;</span>) <span class="op">%&gt;%</span></span>
<span id="cb626-2"><a href="all-the-data-several-correlations.html#cb626-2"></a><span class="st">    </span><span class="kw">round</span>(<span class="dv">2</span>)</span></code></pre></div>
<pre><code>##           a1    c1    e1    o1    n1 gender
## a1      1.00  0.03  0.11  0.01  0.17  -0.16
## c1      0.03  1.00 -0.02  0.17 -0.07   0.01
## e1      0.11 -0.02  1.00 -0.10  0.02  -0.13
## o1      0.01  0.17 -0.10  1.00 -0.05  -0.10
## n1      0.17 -0.07  0.02 -0.05  1.00   0.04
## gender -0.16  0.01 -0.13 -0.10  0.04   1.00</code></pre>
<p>Or you could use apaTable apa.cor.table() command:</p>
<div class="sourceCode" id="cb628"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb628-1"><a href="all-the-data-several-correlations.html#cb628-1"></a><span class="kw">library</span>(apaTables)</span>
<span id="cb628-2"><a href="all-the-data-several-correlations.html#cb628-2"></a><span class="kw">apa.cor.table</span>(bfi)</span></code></pre></div>
<pre><code>## 
## 
## Means, standard deviations, and correlations with confidence intervals
##  
## 
##   Variable  M    SD   1            2           
##   1. a1     2.41 1.41                          
##                                                
##   2. c1     4.50 1.24 .03                      
##                       [-.01, .07]              
##                                                
##   3. e1     2.97 1.63 .11**        -.02        
##                       [.07, .14]   [-.06, .01] 
##                                                
##   4. o1     4.82 1.13 .01          .17**       
##                       [-.02, .05]  [.13, .20]  
##                                                
##   5. n1     2.93 1.57 .17**        -.07**      
##                       [.13, .20]   [-.10, -.03]
##                                                
##   6. gender 1.67 0.47 -.16**       .01         
##                       [-.19, -.12] [-.02, .05] 
##                                                
##   3            4            5         
##                                       
##                                       
##                                       
##                                       
##                                       
##                                       
##                                       
##                                       
##   -.10**                              
##   [-.14, -.06]                        
##                                       
##   .02          -.05**                 
##   [-.02, .05]  [-.09, -.01]           
##                                       
##   -.13**       -.10**       .04*      
##   [-.16, -.09] [-.14, -.07] [.01, .08]
##                                       
## 
## Note. M and SD are used to represent mean and standard deviation, respectively.
## Values in square brackets indicate the 95% confidence interval.
## The confidence interval is a plausible range of population correlations 
## that could have caused the sample correlation (Cumming, 2014).
## * indicates p &lt; .05. ** indicates p &lt; .01.
## </code></pre>
<p>If you do this on your own computer you will see that the correlation between a1 and c1 with rounding is <em>r</em> = .03. Likewise, the correlation between e1 and o1 with rounding is <em>r</em> = -.10.</p>
</div>
<div id="comparing-correlations-within-a-data-set" class="section level2">
<h2><span class="header-section-number">16.3</span> Comparing correlations within a data set</h2>
<div id="non-overlapping-correlations" class="section level3">
<h3><span class="header-section-number">16.3.1</span> Non-overlapping correlations</h3>
<p>We will compare the correlation to between (a1, c1) to the correlation between (e1, o1) with cocor. In this case, because neither of the variables in the first correlation (a1, c1) are in the second correlation (e1, o1) we refer to this as a non-overlapping correlation comparison.</p>
<p>The cocor command will provide a lot of output. We are most interested in the last part of the output corresponding to Zou (2007).
But we also want to examine the first part of the output which will show us the two original correlations (a1, c1) = 0.0276, and (e1, o1) = -0.1002. As well it also shows us the difference between them, Difference: r.jk - r.hm = 0.1278.</p>
<div class="sourceCode" id="cb630"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb630-1"><a href="all-the-data-several-correlations.html#cb630-1"></a><span class="kw">library</span>(cocor)</span>
<span id="cb630-2"><a href="all-the-data-several-correlations.html#cb630-2"></a></span>
<span id="cb630-3"><a href="all-the-data-several-correlations.html#cb630-3"></a><span class="kw">cocor</span>( <span class="op">~</span><span class="st"> </span>a1 <span class="op">+</span><span class="st"> </span>c1 <span class="op">|</span><span class="st"> </span>e1 <span class="op">+</span><span class="st"> </span>o1, <span class="dt">data =</span> <span class="kw">as.data.frame</span>(bfi))</span></code></pre></div>
<pre><code>## 
##   Results of a comparison of two nonoverlapping correlations based on dependent groups
## 
## Comparison between r.jk (a1, c1) = 0.0276 and r.hm (e1, o1) = -0.1002
## Difference: r.jk - r.hm = 0.1278
## Related correlations: r.jh = 0.1036, r.jm = 0.0125, r.kh = -0.0259, r.km = 0.1688
## Data: as.data.frame(bfi): j = a1, k = c1, h = e1, m = o1
## Group size: n = 2724
## Null hypothesis: r.jk is equal to r.hm
## Alternative hypothesis: r.jk is not equal to r.hm (two-sided)
## Alpha: 0.05
## 
## pearson1898: Pearson and Filon&#39;s z (1898)
##   z = 4.7832, p-value = 0.0000
##   Null hypothesis rejected
## 
## dunn1969: Dunn and Clark&#39;s z (1969)
##   z = 4.7676, p-value = 0.0000
##   Null hypothesis rejected
## 
## steiger1980: Steiger&#39;s (1980) modification of Dunn and Clark&#39;s z (1969) using average correlations
##   z = 4.7671, p-value = 0.0000
##   Null hypothesis rejected
## 
## raghunathan1996: Raghunathan, Rosenthal, and Rubin&#39;s (1996) modification of Pearson and Filon&#39;s z (1898)
##   z = 4.7676, p-value = 0.0000
##   Null hypothesis rejected
## 
## silver2004: Silver, Hittner, and May&#39;s (2004) modification of Dunn and Clark&#39;s z (1969) using a backtransformed average Fisher&#39;s (1921) Z procedure
##   z = 4.7671, p-value = 0.0000
##   Null hypothesis rejected
## 
## zou2007: Zou&#39;s (2007) confidence interval
##   95% confidence interval for r.jk - r.hm: 0.0753 0.1800
##   Null hypothesis rejected (Interval does not include 0)</code></pre>
<p>We could write this as <span class="math inline">\(\Delta\)</span><em>r</em> = .13, 95% CI [.07, .18]. We could also add the p-value from silver2004. In this case we would write this as <span class="math inline">\(\Delta\)</span><em>r</em> = .13, 95% CI [.07, .18], <em>p</em> &lt; .001.</p>
</div>
<div id="overlapping-correlations" class="section level3">
<h3><span class="header-section-number">16.3.2</span> Overlapping correlations</h3>
<p>We will compare the correlation to between (a1, c1) to the correlation between (a1, e1) with cocor. In this case, because A1 is common to the first correlation (a1, c1) and the second correlation (e1, o1) we refer to this as an overlapping correlation comparison.</p>
<p>The cocor command will provide a lot of output. We are most interested in the last part of the output corresponding to Zou (2007).
But we also want to examine the first part of the output which will show us the two original correlations (a1, c1) = 0.0276, and (a1, e1) = 0.10472 As well it also shows us the difference between them, Difference: r.jk - r.jh = -0.0784 (with rounding, -.08).</p>
<p>Look in the APA correlation table above to confirm the correlations that are being compared (.0276 (i.e., .03) and .10472 (i.e., .10)).</p>
<div class="sourceCode" id="cb632"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb632-1"><a href="all-the-data-several-correlations.html#cb632-1"></a><span class="kw">library</span>(cocor)</span>
<span id="cb632-2"><a href="all-the-data-several-correlations.html#cb632-2"></a></span>
<span id="cb632-3"><a href="all-the-data-several-correlations.html#cb632-3"></a><span class="kw">cocor</span>( <span class="op">~</span><span class="st"> </span>a1 <span class="op">+</span><span class="st"> </span>c1 <span class="op">|</span><span class="st"> </span>a1 <span class="op">+</span><span class="st"> </span>e1, <span class="dt">data =</span> <span class="kw">as.data.frame</span>(bfi))</span></code></pre></div>
<pre><code>## 
##   Results of a comparison of two overlapping correlations based on dependent groups
## 
## Comparison between r.jk (a1, c1) = 0.0263 and r.jh (a1, e1) = 0.1047
## Difference: r.jk - r.jh = -0.0784
## Related correlation: r.kh = -0.0248
## Data: as.data.frame(bfi): j = a1, k = c1, h = e1
## Group size: n = 2741
## Null hypothesis: r.jk is equal to r.jh
## Alternative hypothesis: r.jk is not equal to r.jh (two-sided)
## Alpha: 0.05
## 
## pearson1898: Pearson and Filon&#39;s z (1898)
##   z = -2.8820, p-value = 0.0040
##   Null hypothesis rejected
## 
## hotelling1940: Hotelling&#39;s t (1940)
##   t = -2.8827, df = 2738, p-value = 0.0040
##   Null hypothesis rejected
## 
## williams1959: Williams&#39; t (1959)
##   t = -2.8793, df = 2738, p-value = 0.0040
##   Null hypothesis rejected
## 
## olkin1967: Olkin&#39;s z (1967)
##   z = -2.8820, p-value = 0.0040
##   Null hypothesis rejected
## 
## dunn1969: Dunn and Clark&#39;s z (1969)
##   z = -2.8775, p-value = 0.0040
##   Null hypothesis rejected
## 
## hendrickson1970: Hendrickson, Stanley, and Hills&#39; (1970) modification of Williams&#39; t (1959)
##   t = -2.8827, df = 2738, p-value = 0.0040
##   Null hypothesis rejected
## 
## steiger1980: Steiger&#39;s (1980) modification of Dunn and Clark&#39;s z (1969) using average correlations
##   z = -2.8765, p-value = 0.0040
##   Null hypothesis rejected
## 
## meng1992: Meng, Rosenthal, and Rubin&#39;s z (1992)
##   z = -2.8754, p-value = 0.0040
##   Null hypothesis rejected
##   95% confidence interval for r.jk - r.jh: -0.1325 -0.0251
##   Null hypothesis rejected (Interval does not include 0)
## 
## hittner2003: Hittner, May, and Silver&#39;s (2003) modification of Dunn and Clark&#39;s z (1969) using a backtransformed average Fisher&#39;s (1921) Z procedure
##   z = -2.8765, p-value = 0.0040
##   Null hypothesis rejected
## 
## zou2007: Zou&#39;s (2007) confidence interval
##   95% confidence interval for r.jk - r.jh: -0.1317 -0.0250
##   Null hypothesis rejected (Interval does not include 0)</code></pre>
<p>We could write this as <span class="math inline">\(\Delta\)</span><em>r</em> = -.08, 95% CI [-.13, -.03]. If we include the p-value from hittner2003 it becomes:</p>
<p><span class="math inline">\(\Delta\)</span><em>r</em> = -.08, 95% CI [-.13, -.03], <em>p</em> = .004.</p>
</div>
</div>
<div id="comparing-correlations-between-data-sets" class="section level2">
<h2><span class="header-section-number">16.4</span> Comparing correlations between data sets</h2>
</div>
<div id="create-seperate-data-files-for-men-and-women-if-needed" class="section level2">
<h2><span class="header-section-number">16.5</span> Create seperate data files for men and women (if needed)</h2>
<div class="sourceCode" id="cb634"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb634-1"><a href="all-the-data-several-correlations.html#cb634-1"></a>bfi_men   &lt;-<span class="st"> </span>bfi <span class="op">%&gt;%</span></span>
<span id="cb634-2"><a href="all-the-data-several-correlations.html#cb634-2"></a><span class="st">  </span><span class="kw">filter</span>(gender <span class="op">==</span><span class="st"> </span><span class="dv">1</span>) <span class="op">%&gt;%</span></span>
<span id="cb634-3"><a href="all-the-data-several-correlations.html#cb634-3"></a><span class="st">  </span><span class="kw">select</span>(<span class="op">-</span>gender)</span>
<span id="cb634-4"><a href="all-the-data-several-correlations.html#cb634-4"></a></span>
<span id="cb634-5"><a href="all-the-data-several-correlations.html#cb634-5"></a>bfi_women &lt;-<span class="st"> </span>bfi <span class="op">%&gt;%</span></span>
<span id="cb634-6"><a href="all-the-data-several-correlations.html#cb634-6"></a><span class="st">  </span><span class="kw">filter</span>(gender <span class="op">==</span><span class="st"> </span><span class="dv">2</span>) <span class="op">%&gt;%</span></span>
<span id="cb634-7"><a href="all-the-data-several-correlations.html#cb634-7"></a><span class="st">  </span><span class="kw">select</span>(<span class="op">-</span>gender)</span></code></pre></div>
</div>
<div id="check-out-the-subgroup-columns" class="section level2">
<h2><span class="header-section-number">16.6</span> Check out the subgroup columns</h2>
<p>Use glimpse to check out the subgroups. Note that it also tells you the number of participants in each subgroup.</p>
<div class="sourceCode" id="cb635"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb635-1"><a href="all-the-data-several-correlations.html#cb635-1"></a><span class="kw">glimpse</span>(bfi_men)</span></code></pre></div>
<pre><code>## Rows: 919
## Columns: 5
## $ a1 &lt;int&gt; 2, 2, 2, 4, 4, 4, 2, 5, 4, 4, 5, 5, 1, 4, 1, 4…
## $ c1 &lt;int&gt; 2, 4, 5, 3, 6, 4, 5, 4, 5, 5, 5, 4, 4, 5, 1, 4…
## $ e1 &lt;int&gt; 3, 2, 4, 3, 5, 1, 3, 2, 3, 1, 2, 3, 2, 3, 6, 2…
## $ o1 &lt;int&gt; 3, 3, 5, 3, 6, 5, 4, 5, 5, 6, 5, 6, 6, 6, 6, 4…
## $ n1 &lt;int&gt; 3, 2, 1, 6, 5, 3, 4, 1, 2, 4, 6, 1, 2, 2, 1, N…</code></pre>
<div class="sourceCode" id="cb637"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb637-1"><a href="all-the-data-several-correlations.html#cb637-1"></a><span class="kw">glimpse</span>(bfi_women)</span></code></pre></div>
<pre><code>## Rows: 1,881
## Columns: 5
## $ a1 &lt;int&gt; 2, 5, 4, 6, 2, 5, 4, 4, 4, 1, 2, 1, 2, 2, 2, 4…
## $ c1 &lt;int&gt; 5, 4, 4, 6, 6, 5, 4, 5, 1, 5, 3, 5, 6, 4, 5, 5…
## $ e1 &lt;int&gt; 1, 2, 5, 2, 2, 3, 1, 1, 1, 1, 2, 1, 2, 1, 1, 1…
## $ o1 &lt;int&gt; 4, 4, 3, 4, 5, 4, 5, 4, 4, 5, 6, 6, 5, 6, 2, 4…
## $ n1 &lt;int&gt; 3, 4, 2, 3, 5, 1, 4, 5, 5, 2, 4, 2, 3, 4, 1, 5…</code></pre>
</div>
<div id="check-out-the-subgroup-correlations" class="section level2">
<h2><span class="header-section-number">16.7</span> Check out the subgroup correlations</h2>
<div id="correlations-for-men" class="section level3">
<h3><span class="header-section-number">16.7.1</span> Correlations for men</h3>
<p>Check out the correlation between a1 and e1 for men in the table created</p>
<div class="sourceCode" id="cb639"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb639-1"><a href="all-the-data-several-correlations.html#cb639-1"></a><span class="kw">apa.cor.table</span>(bfi_men)</span></code></pre></div>
<pre><code>## 
## 
## Means, standard deviations, and correlations with confidence intervals
##  
## 
##   Variable M    SD   1           2            3           
##   1. a1    2.73 1.43                                      
##                                                           
##   2. c1    4.48 1.24 .02                                  
##                      [-.05, .08]                          
##                                                           
##   3. e1    3.27 1.66 .14**       .01                      
##                      [.07, .20]  [-.06, .07]              
##                                                           
##   4. o1    4.98 1.08 -.02        .18**        -.11**      
##                      [-.09, .04] [.11, .24]   [-.18, -.05]
##                                                           
##   5. n1    2.83 1.56 .17**       -.07*        .05         
##                      [.10, .23]  [-.13, -.00] [-.02, .11] 
##                                                           
##   4          
##              
##              
##              
##              
##              
##              
##              
##              
##              
##              
##              
##   -.05       
##   [-.12, .01]
##              
## 
## Note. M and SD are used to represent mean and standard deviation, respectively.
## Values in square brackets indicate the 95% confidence interval.
## The confidence interval is a plausible range of population correlations 
## that could have caused the sample correlation (Cumming, 2014).
## * indicates p &lt; .05. ** indicates p &lt; .01.
## </code></pre>
</div>
<div id="correlations-for-women" class="section level3">
<h3><span class="header-section-number">16.7.2</span> Correlations for women</h3>
<p>Check out the correlation between a1 and e1 for women in the table created</p>
<div class="sourceCode" id="cb641"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb641-1"><a href="all-the-data-several-correlations.html#cb641-1"></a><span class="kw">apa.cor.table</span>(bfi_women)</span></code></pre></div>
<pre><code>## 
## 
## Means, standard deviations, and correlations with confidence intervals
##  
## 
##   Variable M    SD   1           2            3           
##   1. a1    2.26 1.37                                      
##                                                           
##   2. c1    4.52 1.24 .04                                  
##                      [-.01, .08]                          
##                                                           
##   3. e1    2.83 1.60 .06**       -.04                     
##                      [.02, .11]  [-.08, .01]              
##                                                           
##   4. o1    4.73 1.14 .00         .17**        -.12**      
##                      [-.04, .05] [.12, .21]   [-.16, -.07]
##                                                           
##   5. n1    2.98 1.57 .18**       -.07**       .01         
##                      [.13, .22]  [-.11, -.02] [-.03, .06] 
##                                                           
##   4          
##              
##              
##              
##              
##              
##              
##              
##              
##              
##              
##              
##   -.04       
##   [-.09, .00]
##              
## 
## Note. M and SD are used to represent mean and standard deviation, respectively.
## Values in square brackets indicate the 95% confidence interval.
## The confidence interval is a plausible range of population correlations 
## that could have caused the sample correlation (Cumming, 2014).
## * indicates p &lt; .05. ** indicates p &lt; .01.
## </code></pre>
</div>
</div>
<div id="actual-comparison-of-a1-e1-correlation-for-men-to-the-a1-e1-correlation-for-women" class="section level2">
<h2><span class="header-section-number">16.8</span> Actual comparison of (a1, e1) correlation for men to the (a1, e1) correlation for women</h2>
<p>As per the correlations tables above we find the correlations for men ((a1, e1) = 0.1387) and women ((a1, e1) = 0.1387) in the output. We also see the comparison: Difference: r1.jk - r2.hm = 0.0765. Looking below we see the zou2007 confidence interval.</p>
<div class="sourceCode" id="cb643"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb643-1"><a href="all-the-data-several-correlations.html#cb643-1"></a><span class="kw">library</span>(cocor)</span>
<span id="cb643-2"><a href="all-the-data-several-correlations.html#cb643-2"></a>bfi_men_dataframe   &lt;-<span class="st"> </span><span class="kw">as.data.frame</span>(bfi_men)</span>
<span id="cb643-3"><a href="all-the-data-several-correlations.html#cb643-3"></a>bfi_women_dataframe &lt;-<span class="st"> </span><span class="kw">as.data.frame</span>(bfi_women)</span>
<span id="cb643-4"><a href="all-the-data-several-correlations.html#cb643-4"></a></span>
<span id="cb643-5"><a href="all-the-data-several-correlations.html#cb643-5"></a><span class="kw">cocor</span>( <span class="op">~</span><span class="st"> </span>a1 <span class="op">+</span><span class="st"> </span>e1 <span class="op">|</span><span class="st"> </span>a1 <span class="op">+</span><span class="st"> </span>e1,</span>
<span id="cb643-6"><a href="all-the-data-several-correlations.html#cb643-6"></a>       <span class="dt">data =</span> <span class="kw">list</span>(bfi_men_dataframe, bfi_women_dataframe))</span></code></pre></div>
<pre><code>## 
##   Results of a comparison of two correlations based on independent groups
## 
## Comparison between r1.jk (a1, e1) = 0.1387 and r2.hm (a1, e1) = 0.0623
## Difference: r1.jk - r2.hm = 0.0765
## Data: list(bfi_men_dataframe, bfi_women_dataframe): j = a1, k = e1, h = a1, m = e1
## Group sizes: n1 = 912, n2 = 1849
## Null hypothesis: r1.jk is equal to r2.hm
## Alternative hypothesis: r1.jk is not equal to r2.hm (two-sided)
## Alpha: 0.05
## 
## fisher1925: Fisher&#39;s z (1925)
##   z = 1.9074, p-value = 0.0565
##   Null hypothesis retained
## 
## zou2007: Zou&#39;s (2007) confidence interval
##   95% confidence interval for r1.jk - r2.hm: -0.0021 0.1543
##   Null hypothesis retained (Interval includes 0)</code></pre>
<p>We could write this as <span class="math inline">\(\Delta\)</span><em>r</em> = .08, 95% CI [-.002, .15]. If we include the p-value from fisher1925. We would write:</p>
<p><span class="math inline">\(\Delta\)</span><em>r</em> = .08, 95% CI [-.002, .15], <em>p</em> = .057.</p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="correlations.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="references.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook/js/app.min.js"></script>
<script src="libs/gitbook/js/lunr.js"></script>
<script src="libs/gitbook/js/clipboard.min.js"></script>
<script src="libs/gitbook/js/plugin-search.js"></script>
<script src="libs/gitbook/js/plugin-sharing.js"></script>
<script src="libs/gitbook/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook/js/plugin-bookdown.js"></script>
<script src="libs/gitbook/js/jquery.highlight.js"></script>
<script src="libs/gitbook/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": true,
"facebook": false,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/yihui/bookdown-crc/edit/master/15-correlation.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["bookdown.pdf", "bookdown.epub"],
"toc": {
"collapse": "none"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
