<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 6 Sampling Precision | PSYC6060 Course Notes</title>
  <meta name="description" content="Course notes for PSYC 6060" />
  <meta name="generator" content="bookdown 0.20 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 6 Sampling Precision | PSYC6060 Course Notes" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="Course notes for PSYC 6060" />
  <meta name="github-repo" content="dstanley4/psyc6060bookdown" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 6 Sampling Precision | PSYC6060 Course Notes" />
  
  <meta name="twitter:description" content="Course notes for PSYC 6060" />
  

<meta name="author" content="David J. Stanley" />


<meta name="date" content="2020-09-02" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="sampling-accuracy.html"/>
<link rel="next" href="probability-of-a-sample-mean.html"/>
<script src="libs/jquery/jquery.min.js"></script>
<link href="libs/gitbook/css/style.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-clipboard.css" rel="stylesheet" />









<script src="libs/accessible-code-block/empty-anchor.js"></script>


<style type="text/css">
code.sourceCode > span { display: inline-block; line-height: 1.25; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="css/style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">A Book Example</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a><ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#structure-of-the-book"><i class="fa fa-check"></i>Structure of the book</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#software-information-and-conventions"><i class="fa fa-check"></i>Software information and conventions</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="about-the-author.html"><a href="about-the-author.html"><i class="fa fa-check"></i>About the Author</a></li>
<li class="chapter" data-level="1" data-path="introduction.html"><a href="introduction.html"><i class="fa fa-check"></i><b>1</b> Introduction</a><ul>
<li class="chapter" data-level="1.1" data-path="introduction.html"><a href="introduction.html#a-focus-on-workflow"><i class="fa fa-check"></i><b>1.1</b> A focus on workflow</a></li>
<li class="chapter" data-level="1.2" data-path="introduction.html"><a href="introduction.html#r-works-with-plug-ins"><i class="fa fa-check"></i><b>1.2</b> R works with plug-ins</a></li>
<li class="chapter" data-level="1.3" data-path="introduction.html"><a href="introduction.html#create-an-account-at-r-studio-cloud"><i class="fa fa-check"></i><b>1.3</b> Create an account at R Studio Cloud</a></li>
<li class="chapter" data-level="1.4" data-path="introduction.html"><a href="introduction.html#join-the-class-workspace"><i class="fa fa-check"></i><b>1.4</b> Join the class workspace</a></li>
<li class="chapter" data-level="1.5" data-path="introduction.html"><a href="introduction.html#exploring-the-r-studio-interface"><i class="fa fa-check"></i><b>1.5</b> Exploring the R Studio Interface</a><ul>
<li class="chapter" data-level="1.5.1" data-path="introduction.html"><a href="introduction.html#console-panel"><i class="fa fa-check"></i><b>1.5.1</b> Console panel</a></li>
<li class="chapter" data-level="1.5.2" data-path="introduction.html"><a href="introduction.html#script-panel"><i class="fa fa-check"></i><b>1.5.2</b> Script Panel</a></li>
</ul></li>
<li class="chapter" data-level="1.6" data-path="introduction.html"><a href="introduction.html#writing-your-first-script"><i class="fa fa-check"></i><b>1.6</b> Writing your first script</a><ul>
<li class="chapter" data-level="1.6.1" data-path="introduction.html"><a href="introduction.html#create-the-script-file"><i class="fa fa-check"></i><b>1.6.1</b> Create the script file</a></li>
<li class="chapter" data-level="1.6.2" data-path="introduction.html"><a href="introduction.html#add-a-comment-to-your-script"><i class="fa fa-check"></i><b>1.6.2</b> Add a comment to your script</a></li>
<li class="chapter" data-level="1.6.3" data-path="introduction.html"><a href="introduction.html#background-about-the-tidyverse"><i class="fa fa-check"></i><b>1.6.3</b> Background about the tidyverse</a></li>
<li class="chapter" data-level="1.6.4" data-path="introduction.html"><a href="introduction.html#add-librarytidyverse-to-your-script"><i class="fa fa-check"></i><b>1.6.4</b> Add library(tidyverse) to your script</a></li>
<li class="chapter" data-level="1.6.5" data-path="introduction.html"><a href="introduction.html#activate-tidyverse-auto-complete-for-your-script"><i class="fa fa-check"></i><b>1.6.5</b> Activate tidyverse auto-complete for your script</a></li>
</ul></li>
<li class="chapter" data-level="1.7" data-path="introduction.html"><a href="introduction.html#loading-your-data"><i class="fa fa-check"></i><b>1.7</b> Loading your data</a><ul>
<li class="chapter" data-level="1.7.1" data-path="introduction.html"><a href="introduction.html#use-read_csv-not-read.csv-to-open-files."><i class="fa fa-check"></i><b>1.7.1</b> Use read_csv (not read.csv) to open files.</a></li>
</ul></li>
<li class="chapter" data-level="1.8" data-path="introduction.html"><a href="introduction.html#checking-out-your-data"><i class="fa fa-check"></i><b>1.8</b> Checking out your data</a><ul>
<li class="chapter" data-level="1.8.1" data-path="introduction.html"><a href="introduction.html#view-see-a-spreadsheet-view-of-your-data"><i class="fa fa-check"></i><b>1.8.1</b> view(): See a spreadsheet view of your data</a></li>
<li class="chapter" data-level="1.8.2" data-path="introduction.html"><a href="introduction.html#print-see-you-data-in-the-console"><i class="fa fa-check"></i><b>1.8.2</b> print(): See you data in the Console</a></li>
<li class="chapter" data-level="1.8.3" data-path="introduction.html"><a href="introduction.html#head-check-out-the-first-few-rows-of-data"><i class="fa fa-check"></i><b>1.8.3</b> head(): Check out the first few rows of data</a></li>
<li class="chapter" data-level="1.8.4" data-path="introduction.html"><a href="introduction.html#tail-check-out-the-last-few-rows-of-data"><i class="fa fa-check"></i><b>1.8.4</b> tail(): Check out the last few rows of data</a></li>
<li class="chapter" data-level="1.8.5" data-path="introduction.html"><a href="introduction.html#summary-quick-summaries"><i class="fa fa-check"></i><b>1.8.5</b> summary(): Quick summaries</a></li>
</ul></li>
<li class="chapter" data-level="1.9" data-path="introduction.html"><a href="introduction.html#run-vs.-source-with-echo-vs.-source"><i class="fa fa-check"></i><b>1.9</b> Run <em>vs.</em> Source with Echo <em>vs.</em> Source</a><ul>
<li class="chapter" data-level="1.9.1" data-path="introduction.html"><a href="introduction.html#run-select-text"><i class="fa fa-check"></i><b>1.9.1</b> Run select text</a></li>
<li class="chapter" data-level="1.9.2" data-path="introduction.html"><a href="introduction.html#source-without-echo"><i class="fa fa-check"></i><b>1.9.2</b> Source (without Echo)</a></li>
<li class="chapter" data-level="1.9.3" data-path="introduction.html"><a href="introduction.html#source-with-echo"><i class="fa fa-check"></i><b>1.9.3</b> Source with Echo</a></li>
</ul></li>
<li class="chapter" data-level="1.10" data-path="introduction.html"><a href="introduction.html#trying-source-with-echo"><i class="fa fa-check"></i><b>1.10</b> Trying Source with Echo</a></li>
<li class="chapter" data-level="1.11" data-path="introduction.html"><a href="introduction.html#a-few-key-points-about"><i class="fa fa-check"></i><b>1.11</b> A few key points about</a><ul>
<li class="chapter" data-level="1.11.1" data-path="introduction.html"><a href="introduction.html#lists"><i class="fa fa-check"></i><b>1.11.1</b> Lists</a></li>
</ul></li>
<li class="chapter" data-level="1.12" data-path="introduction.html"><a href="introduction.html#thats-it"><i class="fa fa-check"></i><b>1.12</b> That’s it!</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="handling-data-with-the-tidyverse.html"><a href="handling-data-with-the-tidyverse.html"><i class="fa fa-check"></i><b>2</b> Handling Data with the Tidyverse</a><ul>
<li class="chapter" data-level="2.1" data-path="handling-data-with-the-tidyverse.html"><a href="handling-data-with-the-tidyverse.html#required"><i class="fa fa-check"></i><b>2.1</b> Required</a></li>
<li class="chapter" data-level="2.2" data-path="handling-data-with-the-tidyverse.html"><a href="handling-data-with-the-tidyverse.html#objective"><i class="fa fa-check"></i><b>2.2</b> Objective</a></li>
<li class="chapter" data-level="2.3" data-path="handling-data-with-the-tidyverse.html"><a href="handling-data-with-the-tidyverse.html#using-the-console"><i class="fa fa-check"></i><b>2.3</b> Using the Console</a></li>
<li class="chapter" data-level="2.4" data-path="handling-data-with-the-tidyverse.html"><a href="handling-data-with-the-tidyverse.html#basic-tidyverse-commands"><i class="fa fa-check"></i><b>2.4</b> Basic tidyverse commands</a><ul>
<li class="chapter" data-level="2.4.1" data-path="handling-data-with-the-tidyverse.html"><a href="handling-data-with-the-tidyverse.html#select"><i class="fa fa-check"></i><b>2.4.1</b> select()</a></li>
<li class="chapter" data-level="2.4.2" data-path="handling-data-with-the-tidyverse.html"><a href="handling-data-with-the-tidyverse.html#summarise"><i class="fa fa-check"></i><b>2.4.2</b> summarise()</a></li>
<li class="chapter" data-level="2.4.3" data-path="handling-data-with-the-tidyverse.html"><a href="handling-data-with-the-tidyverse.html#filter"><i class="fa fa-check"></i><b>2.4.3</b> filter()</a></li>
<li class="chapter" data-level="2.4.4" data-path="handling-data-with-the-tidyverse.html"><a href="handling-data-with-the-tidyverse.html#group_by"><i class="fa fa-check"></i><b>2.4.4</b> group_by()</a></li>
<li class="chapter" data-level="2.4.5" data-path="handling-data-with-the-tidyverse.html"><a href="handling-data-with-the-tidyverse.html#mutate"><i class="fa fa-check"></i><b>2.4.5</b> mutate()</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="handling-data-with-the-tidyverse.html"><a href="handling-data-with-the-tidyverse.html#advanced-tidyverse-commands"><i class="fa fa-check"></i><b>2.5</b> Advanced tidyverse commands</a><ul>
<li class="chapter" data-level="2.5.1" data-path="handling-data-with-the-tidyverse.html"><a href="handling-data-with-the-tidyverse.html#select-1"><i class="fa fa-check"></i><b>2.5.1</b> select()</a></li>
<li class="chapter" data-level="2.5.2" data-path="handling-data-with-the-tidyverse.html"><a href="handling-data-with-the-tidyverse.html#summarise-1"><i class="fa fa-check"></i><b>2.5.2</b> summarise()</a></li>
<li class="chapter" data-level="2.5.3" data-path="handling-data-with-the-tidyverse.html"><a href="handling-data-with-the-tidyverse.html#mutate-1"><i class="fa fa-check"></i><b>2.5.3</b> mutate()</a></li>
</ul></li>
<li class="chapter" data-level="2.6" data-path="handling-data-with-the-tidyverse.html"><a href="handling-data-with-the-tidyverse.html#using-help"><i class="fa fa-check"></i><b>2.6</b> Using help</a></li>
<li class="chapter" data-level="2.7" data-path="handling-data-with-the-tidyverse.html"><a href="handling-data-with-the-tidyverse.html#base-r-vs-tidyverse"><i class="fa fa-check"></i><b>2.7</b> Base R vs tidyverse</a><ul>
<li class="chapter" data-level="2.7.1" data-path="handling-data-with-the-tidyverse.html"><a href="handling-data-with-the-tidyverse.html#tibbles-vs.-data-frames"><i class="fa fa-check"></i><b>2.7.1</b> Tibbles vs. data frames</a></li>
<li class="chapter" data-level="2.7.2" data-path="handling-data-with-the-tidyverse.html"><a href="handling-data-with-the-tidyverse.html#read.csv-and-data-frames"><i class="fa fa-check"></i><b>2.7.2</b> read.csv() and data frames</a></li>
<li class="chapter" data-level="2.7.3" data-path="handling-data-with-the-tidyverse.html"><a href="handling-data-with-the-tidyverse.html#read_csv-and-tibbles"><i class="fa fa-check"></i><b>2.7.3</b> read_csv() and tibbles</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="making-your-data-ready-for-analysis.html"><a href="making-your-data-ready-for-analysis.html"><i class="fa fa-check"></i><b>3</b> Making your data ready for analysis</a><ul>
<li class="chapter" data-level="3.1" data-path="making-your-data-ready-for-analysis.html"><a href="making-your-data-ready-for-analysis.html#required-packages"><i class="fa fa-check"></i><b>3.1</b> Required Packages</a></li>
<li class="chapter" data-level="3.2" data-path="handling-data-with-the-tidyverse.html"><a href="handling-data-with-the-tidyverse.html#objective"><i class="fa fa-check"></i><b>3.2</b> Objective</a></li>
<li class="chapter" data-level="3.3" data-path="making-your-data-ready-for-analysis.html"><a href="making-your-data-ready-for-analysis.html#context"><i class="fa fa-check"></i><b>3.3</b> Context</a></li>
<li class="chapter" data-level="3.4" data-path="making-your-data-ready-for-analysis.html"><a href="making-your-data-ready-for-analysis.html#begin-with-the-end-in-mind"><i class="fa fa-check"></i><b>3.4</b> Begin with the end in mind</a><ul>
<li class="chapter" data-level="3.4.1" data-path="making-your-data-ready-for-analysis.html"><a href="making-your-data-ready-for-analysis.html#structuring-data-obtaining-tidy-data"><i class="fa fa-check"></i><b>3.4.1</b> Structuring data: Obtaining tidy data</a></li>
</ul></li>
<li class="chapter" data-level="3.5" data-path="making-your-data-ready-for-analysis.html"><a href="making-your-data-ready-for-analysis.html#data-collection-considerations"><i class="fa fa-check"></i><b>3.5</b> Data collection considerations</a><ul>
<li class="chapter" data-level="3.5.1" data-path="making-your-data-ready-for-analysis.html"><a href="making-your-data-ready-for-analysis.html#naming-conventions"><i class="fa fa-check"></i><b>3.5.1</b> Naming conventions</a></li>
<li class="chapter" data-level="3.5.2" data-path="making-your-data-ready-for-analysis.html"><a href="making-your-data-ready-for-analysis.html#likert-type-items"><i class="fa fa-check"></i><b>3.5.2</b> Likert-type items</a></li>
<li class="chapter" data-level="3.5.3" data-path="making-your-data-ready-for-analysis.html"><a href="making-your-data-ready-for-analysis.html#anova-between"><i class="fa fa-check"></i><b>3.5.3</b> ANOVA between</a></li>
<li class="chapter" data-level="3.5.4" data-path="making-your-data-ready-for-analysis.html"><a href="making-your-data-ready-for-analysis.html#anova-within"><i class="fa fa-check"></i><b>3.5.4</b> ANOVA within</a></li>
</ul></li>
<li class="chapter" data-level="3.6" data-path="making-your-data-ready-for-analysis.html"><a href="making-your-data-ready-for-analysis.html#following-the-examples"><i class="fa fa-check"></i><b>3.6</b> Following the examples</a></li>
<li class="chapter" data-level="3.7" data-path="making-your-data-ready-for-analysis.html"><a href="making-your-data-ready-for-analysis.html#entering-data-into-spreadsheets"><i class="fa fa-check"></i><b>3.7</b> Entering data into spreadsheets</a></li>
<li class="chapter" data-level="3.8" data-path="making-your-data-ready-for-analysis.html"><a href="making-your-data-ready-for-analysis.html#experiment-between"><i class="fa fa-check"></i><b>3.8</b> Experiment: Between</a><ul>
<li class="chapter" data-level="3.8.1" data-path="making-your-data-ready-for-analysis.html"><a href="making-your-data-ready-for-analysis.html#creating-factors"><i class="fa fa-check"></i><b>3.8.1</b> Creating factors</a></li>
<li class="chapter" data-level="3.8.2" data-path="making-your-data-ready-for-analysis.html"><a href="making-your-data-ready-for-analysis.html#factor-screening"><i class="fa fa-check"></i><b>3.8.2</b> Factor screening</a></li>
<li class="chapter" data-level="3.8.3" data-path="making-your-data-ready-for-analysis.html"><a href="making-your-data-ready-for-analysis.html#numeric-screening"><i class="fa fa-check"></i><b>3.8.3</b> Numeric screening</a></li>
</ul></li>
<li class="chapter" data-level="3.9" data-path="making-your-data-ready-for-analysis.html"><a href="making-your-data-ready-for-analysis.html#experiment-within-one-way"><i class="fa fa-check"></i><b>3.9</b> Experiment: Within one-way</a><ul>
<li class="chapter" data-level="3.9.1" data-path="making-your-data-ready-for-analysis.html"><a href="making-your-data-ready-for-analysis.html#creating-factors-1"><i class="fa fa-check"></i><b>3.9.1</b> Creating factors</a></li>
<li class="chapter" data-level="3.9.2" data-path="making-your-data-ready-for-analysis.html"><a href="making-your-data-ready-for-analysis.html#factor-screening-1"><i class="fa fa-check"></i><b>3.9.2</b> Factor screening</a></li>
<li class="chapter" data-level="3.9.3" data-path="making-your-data-ready-for-analysis.html"><a href="making-your-data-ready-for-analysis.html#numeric-screening-1"><i class="fa fa-check"></i><b>3.9.3</b> Numeric screening</a></li>
<li class="chapter" data-level="3.9.4" data-path="making-your-data-ready-for-analysis.html"><a href="making-your-data-ready-for-analysis.html#pivot-to-tidy-data"><i class="fa fa-check"></i><b>3.9.4</b> Pivot to tidy data</a></li>
</ul></li>
<li class="chapter" data-level="3.10" data-path="making-your-data-ready-for-analysis.html"><a href="making-your-data-ready-for-analysis.html#experiment-within-n-way"><i class="fa fa-check"></i><b>3.10</b> Experiment: Within N-way</a><ul>
<li class="chapter" data-level="3.10.1" data-path="making-your-data-ready-for-analysis.html"><a href="making-your-data-ready-for-analysis.html#creating-factors-2"><i class="fa fa-check"></i><b>3.10.1</b> Creating factors</a></li>
<li class="chapter" data-level="3.10.2" data-path="making-your-data-ready-for-analysis.html"><a href="making-your-data-ready-for-analysis.html#factor-screening-2"><i class="fa fa-check"></i><b>3.10.2</b> Factor screening</a></li>
<li class="chapter" data-level="3.10.3" data-path="making-your-data-ready-for-analysis.html"><a href="making-your-data-ready-for-analysis.html#numeric-screening-2"><i class="fa fa-check"></i><b>3.10.3</b> Numeric screening</a></li>
<li class="chapter" data-level="3.10.4" data-path="making-your-data-ready-for-analysis.html"><a href="making-your-data-ready-for-analysis.html#pivot-to-tidy-data-1"><i class="fa fa-check"></i><b>3.10.4</b> Pivot to tidy data</a></li>
</ul></li>
<li class="chapter" data-level="3.11" data-path="making-your-data-ready-for-analysis.html"><a href="making-your-data-ready-for-analysis.html#surveys-single-occassion"><i class="fa fa-check"></i><b>3.11</b> Surveys: Single Occassion</a><ul>
<li class="chapter" data-level="3.11.1" data-path="making-your-data-ready-for-analysis.html"><a href="making-your-data-ready-for-analysis.html#creating-factors-3"><i class="fa fa-check"></i><b>3.11.1</b> Creating factors</a></li>
<li class="chapter" data-level="3.11.2" data-path="making-your-data-ready-for-analysis.html"><a href="making-your-data-ready-for-analysis.html#factor-screening-3"><i class="fa fa-check"></i><b>3.11.2</b> Factor screening</a></li>
<li class="chapter" data-level="3.11.3" data-path="making-your-data-ready-for-analysis.html"><a href="making-your-data-ready-for-analysis.html#numeric-screening-3"><i class="fa fa-check"></i><b>3.11.3</b> Numeric screening</a></li>
<li class="chapter" data-level="3.11.4" data-path="making-your-data-ready-for-analysis.html"><a href="making-your-data-ready-for-analysis.html#scale-scores"><i class="fa fa-check"></i><b>3.11.4</b> Scale scores</a></li>
</ul></li>
<li class="chapter" data-level="3.12" data-path="making-your-data-ready-for-analysis.html"><a href="making-your-data-ready-for-analysis.html#surveys-multiple-occasions"><i class="fa fa-check"></i><b>3.12</b> Surveys: Multiple Occasions</a><ul>
<li class="chapter" data-level="3.12.1" data-path="making-your-data-ready-for-analysis.html"><a href="making-your-data-ready-for-analysis.html#creating-factors-4"><i class="fa fa-check"></i><b>3.12.1</b> Creating factors</a></li>
<li class="chapter" data-level="3.12.2" data-path="making-your-data-ready-for-analysis.html"><a href="making-your-data-ready-for-analysis.html#factor-screening-4"><i class="fa fa-check"></i><b>3.12.2</b> Factor screening</a></li>
<li class="chapter" data-level="3.12.3" data-path="making-your-data-ready-for-analysis.html"><a href="making-your-data-ready-for-analysis.html#numeric-screening-4"><i class="fa fa-check"></i><b>3.12.3</b> Numeric screening</a></li>
<li class="chapter" data-level="3.12.4" data-path="making-your-data-ready-for-analysis.html"><a href="making-your-data-ready-for-analysis.html#scale-scores-1"><i class="fa fa-check"></i><b>3.12.4</b> Scale scores</a></li>
<li class="chapter" data-level="3.12.5" data-path="making-your-data-ready-for-analysis.html"><a href="making-your-data-ready-for-analysis.html#pivot-to-tidy-data-2"><i class="fa fa-check"></i><b>3.12.5</b> Pivot to tidy data</a></li>
</ul></li>
<li class="chapter" data-level="3.13" data-path="making-your-data-ready-for-analysis.html"><a href="making-your-data-ready-for-analysis.html#basic-descriptive-statistics"><i class="fa fa-check"></i><b>3.13</b> Basic descriptive statistics</a><ul>
<li class="chapter" data-level="3.13.1" data-path="making-your-data-ready-for-analysis.html"><a href="making-your-data-ready-for-analysis.html#skim"><i class="fa fa-check"></i><b>3.13.1</b> skim()</a></li>
<li class="chapter" data-level="3.13.2" data-path="making-your-data-ready-for-analysis.html"><a href="making-your-data-ready-for-analysis.html#apa.cor.table"><i class="fa fa-check"></i><b>3.13.2</b> apa.cor.table()</a></li>
<li class="chapter" data-level="3.13.3" data-path="making-your-data-ready-for-analysis.html"><a href="making-your-data-ready-for-analysis.html#tidyverse"><i class="fa fa-check"></i><b>3.13.3</b> tidyverse</a></li>
<li class="chapter" data-level="3.13.4" data-path="making-your-data-ready-for-analysis.html"><a href="making-your-data-ready-for-analysis.html#cronbachs-alpha"><i class="fa fa-check"></i><b>3.13.4</b> Cronbach’s alpha</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="populations.html"><a href="populations.html"><i class="fa fa-check"></i><b>4</b> Populations</a><ul>
<li class="chapter" data-level="4.1" data-path="populations.html"><a href="populations.html#notation"><i class="fa fa-check"></i><b>4.1</b> Notation</a></li>
<li class="chapter" data-level="4.2" data-path="populations.html"><a href="populations.html#population-vs-samples"><i class="fa fa-check"></i><b>4.2</b> Population vs samples</a></li>
<li class="chapter" data-level="4.3" data-path="populations.html"><a href="populations.html#a-small-population"><i class="fa fa-check"></i><b>4.3</b> A small population</a><ul>
<li class="chapter" data-level="4.3.1" data-path="populations.html"><a href="populations.html#mean-mu"><i class="fa fa-check"></i><b>4.3.1</b> Mean (<span class="math inline">\(\mu\)</span>)</a></li>
<li class="chapter" data-level="4.3.2" data-path="populations.html"><a href="populations.html#variance-sigma2"><i class="fa fa-check"></i><b>4.3.2</b> Variance (<span class="math inline">\(\sigma^2\)</span>)</a></li>
<li class="chapter" data-level="4.3.3" data-path="populations.html"><a href="populations.html#standard-deviation-sigma"><i class="fa fa-check"></i><b>4.3.3</b> Standard Deviation (<span class="math inline">\(\sigma\)</span>)</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="populations.html"><a href="populations.html#visualizing-populations"><i class="fa fa-check"></i><b>4.4</b> Visualizing populations</a></li>
<li class="chapter" data-level="4.5" data-path="populations.html"><a href="populations.html#population-comparisons"><i class="fa fa-check"></i><b>4.5</b> Population comparisons</a><ul>
<li class="chapter" data-level="4.5.1" data-path="populations.html"><a href="populations.html#standardized-units"><i class="fa fa-check"></i><b>4.5.1</b> Standardized units</a></li>
<li class="chapter" data-level="4.5.2" data-path="populations.html"><a href="populations.html#cohens-d-units"><i class="fa fa-check"></i><b>4.5.2</b> Cohen’s <span class="math inline">\(d\)</span> units</a></li>
<li class="chapter" data-level="4.5.3" data-path="populations.html"><a href="populations.html#cohens-d-advantages"><i class="fa fa-check"></i><b>4.5.3</b> Cohen’s <span class="math inline">\(d\)</span> advantages</a></li>
<li class="chapter" data-level="4.5.4" data-path="populations.html"><a href="populations.html#cohens-d-caveats"><i class="fa fa-check"></i><b>4.5.4</b> Cohen’s <span class="math inline">\(d\)</span> caveats</a></li>
<li class="chapter" data-level="4.5.5" data-path="populations.html"><a href="populations.html#benchmarks"><i class="fa fa-check"></i><b>4.5.5</b> Benchmarks</a></li>
</ul></li>
<li class="chapter" data-level="4.6" data-path="populations.html"><a href="populations.html#population-relations"><i class="fa fa-check"></i><b>4.6</b> Population relations</a></li>
<li class="chapter" data-level="4.7" data-path="populations.html"><a href="populations.html#linear-relations"><i class="fa fa-check"></i><b>4.7</b> Linear relations</a></li>
<li class="chapter" data-level="4.8" data-path="populations.html"><a href="populations.html#key-points"><i class="fa fa-check"></i><b>4.8</b> Key points</a></li>
<li class="chapter" data-level="4.9" data-path="populations.html"><a href="populations.html#self-assessment"><i class="fa fa-check"></i><b>4.9</b> Self Assessment</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="sampling-accuracy.html"><a href="sampling-accuracy.html"><i class="fa fa-check"></i><b>5</b> Sampling Accuracy</a><ul>
<li class="chapter" data-level="5.1" data-path="sampling-accuracy.html"><a href="sampling-accuracy.html#overview"><i class="fa fa-check"></i><b>5.1</b> Overview</a></li>
<li class="chapter" data-level="5.2" data-path="sampling-accuracy.html"><a href="sampling-accuracy.html#data-for-the-chapter"><i class="fa fa-check"></i><b>5.2</b> Data for the chapter</a></li>
<li class="chapter" data-level="5.3" data-path="populations.html"><a href="populations.html#notation"><i class="fa fa-check"></i><b>5.3</b> Notation</a></li>
<li class="chapter" data-level="5.4" data-path="sampling-accuracy.html"><a href="sampling-accuracy.html#estimating-the-mean"><i class="fa fa-check"></i><b>5.4</b> Estimating the mean</a></li>
<li class="chapter" data-level="5.5" data-path="sampling-accuracy.html"><a href="sampling-accuracy.html#estimating-variance"><i class="fa fa-check"></i><b>5.5</b> Estimating variance</a></li>
<li class="chapter" data-level="5.6" data-path="sampling-accuracy.html"><a href="sampling-accuracy.html#estimating-standard-deviation"><i class="fa fa-check"></i><b>5.6</b> Estimating standard deviation</a></li>
<li class="chapter" data-level="5.7" data-path="sampling-accuracy.html"><a href="sampling-accuracy.html#estimating-smd"><i class="fa fa-check"></i><b>5.7</b> Estimating SMD</a><ul>
<li class="chapter" data-level="5.7.1" data-path="sampling-accuracy.html"><a href="sampling-accuracy.html#pooled-standard-deviation"><i class="fa fa-check"></i><b>5.7.1</b> Pooled standard deviation</a></li>
<li class="chapter" data-level="5.7.2" data-path="sampling-accuracy.html"><a href="sampling-accuracy.html#calculating-d"><i class="fa fa-check"></i><b>5.7.2</b> Calculating <span class="math inline">\(d\)</span></a></li>
<li class="chapter" data-level="5.7.3" data-path="sampling-accuracy.html"><a href="sampling-accuracy.html#assessing-bias"><i class="fa fa-check"></i><b>5.7.3</b> Assessing bias</a></li>
<li class="chapter" data-level="5.7.4" data-path="sampling-accuracy.html"><a href="sampling-accuracy.html#illustrating-variability"><i class="fa fa-check"></i><b>5.7.4</b> Illustrating variability</a></li>
</ul></li>
<li class="chapter" data-level="5.8" data-path="sampling-accuracy.html"><a href="sampling-accuracy.html#overview-1"><i class="fa fa-check"></i><b>5.8</b> Overview</a></li>
<li class="chapter" data-level="5.9" data-path="sampling-accuracy.html"><a href="sampling-accuracy.html#meta-analysis"><i class="fa fa-check"></i><b>5.9</b> Meta-analysis</a></li>
<li class="chapter" data-level="5.10" data-path="sampling-accuracy.html"><a href="sampling-accuracy.html#a-joke"><i class="fa fa-check"></i><b>5.10</b> A joke</a></li>
<li class="chapter" data-level="5.11" data-path="populations.html"><a href="populations.html#key-points"><i class="fa fa-check"></i><b>5.11</b> Key Points</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="sampling-precision.html"><a href="sampling-precision.html"><i class="fa fa-check"></i><b>6</b> Sampling Precision</a><ul>
<li class="chapter" data-level="6.1" data-path="sampling-accuracy.html"><a href="sampling-accuracy.html#overview"><i class="fa fa-check"></i><b>6.1</b> Overview</a></li>
<li class="chapter" data-level="6.2" data-path="sampling-precision.html"><a href="sampling-precision.html#population-individuals"><i class="fa fa-check"></i><b>6.2</b> Population / Individuals</a></li>
<li class="chapter" data-level="6.3" data-path="sampling-precision.html"><a href="sampling-precision.html#sampling-distribution"><i class="fa fa-check"></i><b>6.3</b> Sampling distribution</a></li>
<li class="chapter" data-level="6.4" data-path="sampling-precision.html"><a href="sampling-precision.html#precision-indices"><i class="fa fa-check"></i><b>6.4</b> Precision indices</a></li>
<li class="chapter" data-level="6.5" data-path="sampling-precision.html"><a href="sampling-precision.html#a-short-cut"><i class="fa fa-check"></i><b>6.5</b> A short cut</a></li>
<li class="chapter" data-level="6.6" data-path="sampling-precision.html"><a href="sampling-precision.html#estimates-of-precision"><i class="fa fa-check"></i><b>6.6</b> Estimates of precision</a><ul>
<li class="chapter" data-level="6.6.1" data-path="sampling-precision.html"><a href="sampling-precision.html#a-worked-example"><i class="fa fa-check"></i><b>6.6.1</b> A worked example</a></li>
</ul></li>
<li class="chapter" data-level="6.7" data-path="sampling-precision.html"><a href="sampling-precision.html#bias-of-precision-estimates"><i class="fa fa-check"></i><b>6.7</b> Bias of precision estimates</a></li>
<li class="chapter" data-level="6.8" data-path="sampling-precision.html"><a href="sampling-precision.html#where-are-we"><i class="fa fa-check"></i><b>6.8</b> Where are we?</a></li>
<li class="chapter" data-level="6.9" data-path="sampling-precision.html"><a href="sampling-precision.html#factors-influencing-precision"><i class="fa fa-check"></i><b>6.9</b> Factors influencing precision</a></li>
<li class="chapter" data-level="6.10" data-path="sampling-precision.html"><a href="sampling-precision.html#precision-for-other-statistics"><i class="fa fa-check"></i><b>6.10</b> Precision for other statistics</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="probability-of-a-sample-mean.html"><a href="probability-of-a-sample-mean.html"><i class="fa fa-check"></i><b>7</b> Probability of a sample mean</a></li>
<li class="chapter" data-level="8" data-path="graphing.html"><a href="graphing.html"><i class="fa fa-check"></i><b>8</b> Graphing</a><ul>
<li class="chapter" data-level="8.1" data-path="handling-data-with-the-tidyverse.html"><a href="handling-data-with-the-tidyverse.html#required"><i class="fa fa-check"></i><b>8.1</b> Required</a></li>
<li class="chapter" data-level="8.2" data-path="graphing.html"><a href="graphing.html#data"><i class="fa fa-check"></i><b>8.2</b> Data</a></li>
<li class="chapter" data-level="8.3" data-path="graphing.html"><a href="graphing.html#graph-basics"><i class="fa fa-check"></i><b>8.3</b> Graph basics</a></li>
<li class="chapter" data-level="8.4" data-path="graphing.html"><a href="graphing.html#graphing-efficiently"><i class="fa fa-check"></i><b>8.4</b> Graphing efficiently</a></li>
<li class="chapter" data-level="8.5" data-path="graphing.html"><a href="graphing.html#aesthetics"><i class="fa fa-check"></i><b>8.5</b> Aesthetics</a><ul>
<li class="chapter" data-level="8.5.1" data-path="graphing.html"><a href="graphing.html#fill-color"><i class="fa fa-check"></i><b>8.5.1</b> Fill color</a></li>
<li class="chapter" data-level="8.5.2" data-path="graphing.html"><a href="graphing.html#overriding-aes"><i class="fa fa-check"></i><b>8.5.2</b> Overriding aes()</a></li>
</ul></li>
<li class="chapter" data-level="8.6" data-path="graphing.html"><a href="graphing.html#apa-style"><i class="fa fa-check"></i><b>8.6</b> APA style</a></li>
<li class="chapter" data-level="8.7" data-path="graphing.html"><a href="graphing.html#axes"><i class="fa fa-check"></i><b>8.7</b> Axes</a><ul>
<li class="chapter" data-level="8.7.1" data-path="graphing.html"><a href="graphing.html#range"><i class="fa fa-check"></i><b>8.7.1</b> Range</a></li>
<li class="chapter" data-level="8.7.2" data-path="graphing.html"><a href="graphing.html#ticks"><i class="fa fa-check"></i><b>8.7.2</b> Ticks</a></li>
<li class="chapter" data-level="8.7.3" data-path="graphing.html"><a href="graphing.html#labels"><i class="fa fa-check"></i><b>8.7.3</b> Labels</a></li>
</ul></li>
<li class="chapter" data-level="8.8" data-path="graphing.html"><a href="graphing.html#axis-values"><i class="fa fa-check"></i><b>8.8</b> Axis values</a><ul>
<li class="chapter" data-level="8.8.1" data-path="graphing.html"><a href="graphing.html#text"><i class="fa fa-check"></i><b>8.8.1</b> Text</a></li>
<li class="chapter" data-level="8.8.2" data-path="graphing.html"><a href="graphing.html#angle"><i class="fa fa-check"></i><b>8.8.2</b> Angle</a></li>
<li class="chapter" data-level="8.8.3" data-path="graphing.html"><a href="graphing.html#alignment"><i class="fa fa-check"></i><b>8.8.3</b> Alignment</a></li>
<li class="chapter" data-level="8.8.4" data-path="graphing.html"><a href="graphing.html#order"><i class="fa fa-check"></i><b>8.8.4</b> Order</a></li>
<li class="chapter" data-level="8.8.5" data-path="graphing.html"><a href="graphing.html#legend-order"><i class="fa fa-check"></i><b>8.8.5</b> Legend order</a></li>
</ul></li>
<li class="chapter" data-level="8.9" data-path="graphing.html"><a href="graphing.html#custom-colours"><i class="fa fa-check"></i><b>8.9</b> Custom colours</a><ul>
<li class="chapter" data-level="8.9.1" data-path="graphing.html"><a href="graphing.html#r-palette"><i class="fa fa-check"></i><b>8.9.1</b> R palette</a></li>
<li class="chapter" data-level="8.9.2" data-path="graphing.html"><a href="graphing.html#hex-colours"><i class="fa fa-check"></i><b>8.9.2</b> Hex colours</a></li>
</ul></li>
<li class="chapter" data-level="8.10" data-path="graphing.html"><a href="graphing.html#emoji"><i class="fa fa-check"></i><b>8.10</b> Emoji</a></li>
<li class="chapter" data-level="8.11" data-path="graphing.html"><a href="graphing.html#accessible-colors"><i class="fa fa-check"></i><b>8.11</b> Accessible Colors</a><ul>
<li class="chapter" data-level="8.11.1" data-path="graphing.html"><a href="graphing.html#rcolorbrewer"><i class="fa fa-check"></i><b>8.11.1</b> RColorBrewer</a></li>
<li class="chapter" data-level="8.11.2" data-path="graphing.html"><a href="graphing.html#avoid-color"><i class="fa fa-check"></i><b>8.11.2</b> Avoid color</a></li>
</ul></li>
<li class="chapter" data-level="8.12" data-path="graphing.html"><a href="graphing.html#saving"><i class="fa fa-check"></i><b>8.12</b> Saving</a><ul>
<li class="chapter" data-level="8.12.1" data-path="graphing.html"><a href="graphing.html#mac"><i class="fa fa-check"></i><b>8.12.1</b> MAC</a></li>
<li class="chapter" data-level="8.12.2" data-path="graphing.html"><a href="graphing.html#pc-or-mac"><i class="fa fa-check"></i><b>8.12.2</b> PC or MAC</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="9" data-path="effect-sizes-with-confidence-intervals-from-a-published-study.html"><a href="effect-sizes-with-confidence-intervals-from-a-published-study.html"><i class="fa fa-check"></i><b>9</b> Effect sizes with confidence intervals from a published study</a><ul>
<li class="chapter" data-level="9.1" data-path="effect-sizes-with-confidence-intervals-from-a-published-study.html"><a href="effect-sizes-with-confidence-intervals-from-a-published-study.html#correlations"><i class="fa fa-check"></i><b>9.1</b> Correlations</a></li>
<li class="chapter" data-level="9.2" data-path="effect-sizes-with-confidence-intervals-from-a-published-study.html"><a href="effect-sizes-with-confidence-intervals-from-a-published-study.html#repeated-measures-d-values"><i class="fa fa-check"></i><b>9.2</b> Repeated Measures <span class="math inline">\(d\)</span>-values</a><ul>
<li class="chapter" data-level="9.2.1" data-path="effect-sizes-with-confidence-intervals-from-a-published-study.html"><a href="effect-sizes-with-confidence-intervals-from-a-published-study.html#reported-repeated-d-value-no-confidence-interval"><i class="fa fa-check"></i><b>9.2.1</b> Reported repeated <span class="math inline">\(d\)</span>-value, no confidence interval</a></li>
<li class="chapter" data-level="9.2.2" data-path="effect-sizes-with-confidence-intervals-from-a-published-study.html"><a href="effect-sizes-with-confidence-intervals-from-a-published-study.html#using-repeated-measures-mean-difference"><i class="fa fa-check"></i><b>9.2.2</b> Using repeated measures mean difference</a></li>
<li class="chapter" data-level="9.2.3" data-path="effect-sizes-with-confidence-intervals-from-a-published-study.html"><a href="effect-sizes-with-confidence-intervals-from-a-published-study.html#using-repeated-measures-cell-information"><i class="fa fa-check"></i><b>9.2.3</b> Using repeated measures cell information</a></li>
<li class="chapter" data-level="9.2.4" data-path="effect-sizes-with-confidence-intervals-from-a-published-study.html"><a href="effect-sizes-with-confidence-intervals-from-a-published-study.html#using-repeated-measures-t-value"><i class="fa fa-check"></i><b>9.2.4</b> Using repeated measures <span class="math inline">\(t\)</span>-value</a></li>
</ul></li>
<li class="chapter" data-level="9.3" data-path="effect-sizes-with-confidence-intervals-from-a-published-study.html"><a href="effect-sizes-with-confidence-intervals-from-a-published-study.html#independent-groups-d-value-pooled-variance"><i class="fa fa-check"></i><b>9.3</b> Independent Groups <span class="math inline">\(d\)</span>-value: Pooled Variance</a><ul>
<li class="chapter" data-level="9.3.1" data-path="effect-sizes-with-confidence-intervals-from-a-published-study.html"><a href="effect-sizes-with-confidence-intervals-from-a-published-study.html#reported-d-value-no-confidence-interval"><i class="fa fa-check"></i><b>9.3.1</b> Reported <span class="math inline">\(d\)</span>-value no confidence interval</a></li>
<li class="chapter" data-level="9.3.2" data-path="effect-sizes-with-confidence-intervals-from-a-published-study.html"><a href="effect-sizes-with-confidence-intervals-from-a-published-study.html#using-cell-means"><i class="fa fa-check"></i><b>9.3.2</b> Using cell means</a></li>
</ul></li>
<li class="chapter" data-level="9.4" data-path="effect-sizes-with-confidence-intervals-from-a-published-study.html"><a href="effect-sizes-with-confidence-intervals-from-a-published-study.html#independent-groups-d-value-control-group-variance"><i class="fa fa-check"></i><b>9.4</b> Independent Groups <span class="math inline">\(d\)</span>-value: Control Group Variance</a><ul>
<li class="chapter" data-level="9.4.1" data-path="effect-sizes-with-confidence-intervals-from-a-published-study.html"><a href="effect-sizes-with-confidence-intervals-from-a-published-study.html#reported-d-value-no-confidence-interval-1"><i class="fa fa-check"></i><b>9.4.1</b> Reported <span class="math inline">\(d\)</span>-value no confidence interval</a></li>
<li class="chapter" data-level="9.4.2" data-path="effect-sizes-with-confidence-intervals-from-a-published-study.html"><a href="effect-sizes-with-confidence-intervals-from-a-published-study.html#using-cell-means-1"><i class="fa fa-check"></i><b>9.4.2</b> Using cell means</a></li>
</ul></li>
</ul></li>
<li class="appendix"><span><b>Appendix</b></span></li>
<li class="chapter" data-level="A" data-path="more-to-say.html"><a href="more-to-say.html"><i class="fa fa-check"></i><b>A</b> More to Say</a></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://bookdown.org" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">PSYC6060 Course Notes</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="sampling-precision" class="section level1">
<h1><span class="header-section-number">Chapter 6</span> Sampling Precision</h1>
<div id="overview" class="section level2">
<h2><span class="header-section-number">6.1</span> Overview</h2>
<p>In the previous chapter we focused on examining the extent to which we could estimate a population parameter from a statistic in an unbiased manner. That is, we focused on the fact that, due to sampling error, a sample estimate (i.e., a statistic) of a population parameter will likely be wrong. Sample statistics may overestimate, or underestimate, a population parameter - often substantially. Consequently, we learned to think about the accuracy of sample statistics. More specifically, we learned to think about accuracy not in terms of a single study, but rather in terms of whether sample statistics correctly estimate the population parameter on average over many studies (as illustrated in Figure <a href="sampling-precision.html#fig:showbias2">6.1</a>). When the average of many sample statistics (e.g., sample means) equals the population parameter (e.g., population mean) there is no bias and the sample statistic can be considered accurate (on average).</p>
<p>In this chapter, we assume there is no bias and that sample means are, on average, accurate. In doing so, we focus now on the precision of sample means as estimates of the population mean, see Figure <a href="sampling-precision.html#fig:showbias2">6.1</a>. That is, assuming no bias, when you conduct a single study you know the sample mean will differ from the population mean due to sampling error. You might wonder, how much does my sample mean differ from the population mean? That’s the question we address in this chapter. When we conduct a single study we can’t know how much that particular sample mean differs from the population mean, but we can estimate the extent to which sample means differ from the population mean in general. We focus on two indices of precision – variance of sample mean and standard error of sample means. By the end of the chapter you will understand how to a) conceptualize these indices with respect to a large number of samples/studies and b) estimate them for a single study.</p>
<div class="figure"><span id="fig:showbias2"></span>
<img src="ch_samples_precision/images/sampling_accuracy.png" alt="Sampling accuracy and precision" width="80%" />
<p class="caption">
FIGURE 6.1: Sampling accuracy and precision
</p>
</div>
</div>
<div id="population-individuals" class="section level2">
<h2><span class="header-section-number">6.2</span> Population / Individuals</h2>
<p>We use a population of heights to learn about random sampling and the precision of sample estimates. We can obtain that population with the code below:</p>
<div class="sourceCode" id="cb347"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb347-1"><a href="sampling-precision.html#cb347-1"></a><span class="kw">library</span>(tidyverse)</span>
<span id="cb347-2"><a href="sampling-precision.html#cb347-2"></a><span class="kw">library</span>(learnSampling)</span>
<span id="cb347-3"><a href="sampling-precision.html#cb347-3"></a></span>
<span id="cb347-4"><a href="sampling-precision.html#cb347-4"></a>pop_data &lt;-<span class="st"> </span><span class="kw">get_height_population</span>() </span></code></pre></div>
<p>The glimpse() command can be used to confirm that the population contains 100,000 people.</p>
<div class="sourceCode" id="cb348"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb348-1"><a href="sampling-precision.html#cb348-1"></a><span class="kw">glimpse</span>(pop_data)</span></code></pre></div>
<pre><code>## Rows: 100,000
## Columns: 3
## $ id     &lt;int&gt; 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,…
## $ sex    &lt;chr&gt; &quot;male&quot;, &quot;female&quot;, &quot;female&quot;, &quot;male&quot;, &quot;male&quot;…
## $ height &lt;dbl&gt; 177, 150, 171, 157, 169, 187, 163, 173, 17…</code></pre>
<p>We can use the head() command to see the first 10 rows of the 100,00 rows. We see that each row in pop_data represents a single person. There is a column called height that contains the height for everyone in the population.</p>
<div class="sourceCode" id="cb350"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb350-1"><a href="sampling-precision.html#cb350-1"></a><span class="kw">head</span>(pop_data, <span class="dv">10</span>)</span></code></pre></div>
<pre><code>## # A tibble: 10 x 3
##       id sex    height
##    &lt;int&gt; &lt;chr&gt;   &lt;dbl&gt;
##  1     1 male      177
##  2     2 female    150
##  3     3 female    171
##  4     4 male      157
##  5     5 male      169
##  6     6 male      187
##  7     7 female    163
##  8     8 male      173
##  9     9 female    172
## 10    10 male      193</code></pre>
<p>We can calculate the descriptive parameters for the population with the code below:</p>
<div class="sourceCode" id="cb352"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb352-1"><a href="sampling-precision.html#cb352-1"></a>pop_data <span class="op">%&gt;%</span></span>
<span id="cb352-2"><a href="sampling-precision.html#cb352-2"></a><span class="st">  </span><span class="kw">summarise</span>(<span class="dt">pop_mean =</span> <span class="kw">mean</span>(height),</span>
<span id="cb352-3"><a href="sampling-precision.html#cb352-3"></a>            <span class="dt">pop_var =</span> <span class="kw">var.pop</span>(height),</span>
<span id="cb352-4"><a href="sampling-precision.html#cb352-4"></a>            <span class="dt">pop_sd =</span> <span class="kw">sd.pop</span>(height)) <span class="op">%&gt;%</span></span>
<span id="cb352-5"><a href="sampling-precision.html#cb352-5"></a><span class="st">  </span><span class="kw">as.data.frame</span>()</span></code></pre></div>
<pre><code>##   pop_mean pop_var pop_sd
## 1    172.5   157.5  12.55</code></pre>
<p>We see the mean of the population of heights is 172.5 (<span class="math inline">\(\mu = 172.5\)</span>) and the variance is 157.5 (<span class="math inline">\(\sigma^2 = 157.5\)</span>). Correspondingly, the standard deviation of the population of heights is 12.5 (<span class="math inline">\(\sigma = 12.5\)</span>); simply the square root of the variance.</p>
<p><span class="math display">\[
\begin{aligned} 
\mu &amp;= 172.5 \\
\sigma^2 &amp;= 157.5 \\
\sigma &amp;= 12.5 \\
\end{aligned} 
\]</span></p>
</div>
<div id="sampling-distribution" class="section level2">
<h2><span class="header-section-number">6.3</span> Sampling distribution</h2>
<p>A sampling distribution is composed of an infinite number of samples. For pedagogical purposes, we will use a sampling distribution of just 50000 samples. This large number of samples will lead us to roughly the same conclusions as using an infinite, but impractical, number of samples. We obtain 50000 samples with code below:</p>
<div class="sourceCode" id="cb354"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb354-1"><a href="sampling-precision.html#cb354-1"></a>many_samples &lt;-<span class="st"> </span><span class="kw">get_M_samples</span>(<span class="dt">pop.data =</span> pop_data, </span>
<span id="cb354-2"><a href="sampling-precision.html#cb354-2"></a>                              <span class="dt">pop.column.name =</span> height,</span>
<span id="cb354-3"><a href="sampling-precision.html#cb354-3"></a>                              <span class="dt">n =</span> <span class="dv">50</span>,</span>
<span id="cb354-4"><a href="sampling-precision.html#cb354-4"></a>                              <span class="dt">number.of.samples =</span> <span class="dv">50000</span>)</span></code></pre></div>
<p>We can use the head() command to see the first few rows of many_samples. Every row represents a sample of 10 people. That is, each row represents a study with 10 participants for which we measured their heights. For each row/study we have the sample mean and variance (using n-1) for the 10 heights.</p>
<div class="sourceCode" id="cb355"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb355-1"><a href="sampling-precision.html#cb355-1"></a><span class="kw">head</span>(many_samples)</span></code></pre></div>
<pre><code>##   study  n sample_mean sample_var_n sample_var_n_1
## 1     1 10       174.3        27.81          30.90
## 2     2 10       161.8        83.36          92.62
## 3     3 10       173.2       139.16         154.62
## 4     4 10       180.0       321.80         357.56
## 5     5 10       172.8       160.96         178.84
## 6     6 10       172.0       159.60         177.33</code></pre>
<p>We will study the precision of sample means as estimates of the population mean using the values in the sample_mean column. Each of the 50000 values in the sample_mean column is a sample mean (<span class="math inline">\(\bar{x}\)</span>), based on <span class="math inline">\(n\)</span> = 10. Each sample mean provides an estimate of the population mean (<span class="math inline">\(\mu = 172.5\)</span>). Sample means often overestimate, or underestimate, the population mean. We can see this using the code below which reveals that the smallest sample mean is 155.6 (<span class="math inline">\(\bar{x} = 155.6\)</span>) and the largest sample mean is 188.8 (<span class="math inline">\(\bar{x} = 188.8\)</span>). Both are estimates of the population mean (<span class="math inline">\(\mu = 172.5\)</span>) but differ from that value due to sampling error (i.e., the fact that sample means are based on a small subset of the population). You can see that the conclusions of any single study may differ rather substantially from what is true for the overall population.</p>
<div class="sourceCode" id="cb357"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb357-1"><a href="sampling-precision.html#cb357-1"></a>many_samples <span class="op">%&gt;%</span></span>
<span id="cb357-2"><a href="sampling-precision.html#cb357-2"></a><span class="st">   </span><span class="kw">summarise</span>(<span class="dt">min_mean =</span> <span class="kw">min</span>(sample_mean),</span>
<span id="cb357-3"><a href="sampling-precision.html#cb357-3"></a>             <span class="dt">max_mean =</span> <span class="kw">max</span>(sample_mean))</span></code></pre></div>
<pre><code>##   min_mean max_mean
## 1    155.6    188.8</code></pre>
<p>The 50000 means in the sample_mean column form a <strong>sampling distribution</strong>; specifically, the sampling distribution of the mean. It’s critical to distinguish between a) the distribution of the sample means and b) the distribution of population heights. Examine Figure <a href="sampling-precision.html#fig:bothdist2">6.2</a> below. The top part of this figure illustrates the variability in the heights for the 100,000 people (represented by X’s). There are more people than X’s; the X’s are a reminder it is a distribution of people’s heights. The bottom part of this figure illustrates the variability in sample means - each based on 10 people. Each sample mean is an estimate of the mean height of the population (172.5 cm). There are more sample means than <span class="math inline">\(\bar{x}\)</span>’s; the <span class="math inline">\(\bar{x}\)</span>’s are a reminder it is a distribution of sample means. When we describe how precisely sample means estimate the mean height for the population we are referring to the width of this distribution of means.</p>
<div class="figure"><span id="fig:bothdist2"></span>
<img src="ch_samples_precision/images/sampling_dist.png" alt="Sampling distribution of the mean. The population of individual height's is presented at the top and filled with X's to remind you they are individuals. There are more individuals than X's. The sampling distribution of means is presented in the bottom part of the graph. The sampling distribution of means is filled with $\bar{x}$'s to remind you that sample means are being graphed. There are more means than $\bar{x}$'s. The population mean (green line) and the mean of sample means (blue line) are in the same spot, indicating high accuracy (i.e., no bias)." width="80%" />
<p class="caption">
FIGURE 6.2: Sampling distribution of the mean. The population of individual height’s is presented at the top and filled with X’s to remind you they are individuals. There are more individuals than X’s. The sampling distribution of means is presented in the bottom part of the graph. The sampling distribution of means is filled with <span class="math inline">\(\bar{x}\)</span>’s to remind you that sample means are being graphed. There are more means than <span class="math inline">\(\bar{x}\)</span>’s. The population mean (green line) and the mean of sample means (blue line) are in the same spot, indicating high accuracy (i.e., no bias).
</p>
</div>
</div>
<div id="precision-indices" class="section level2">
<h2><span class="header-section-number">6.4</span> Precision indices</h2>
<p>The most common way of referring to the width of this distribution of sample means is with the term standard error. Standard error is simply the standard deviation of the sample means. We calculate the standard error of the mean using Formula <a href="sampling-precision.html#eq:samplesechnext">(6.1)</a> below. We use <span class="math inline">\(k\)</span> in the formula to refer to the number of sample means in the distribution.</p>
<p><span class="math display" id="eq:samplesechnext">\[\begin{equation} 
\sigma_{\bar{x}} = \sqrt{\frac{\sum{(\bar{x} - \bar{\bar{x}})^2}}{k}}
      \tag{6.1}
\end{equation}\]</span></p>
<p>Notice that the formula for standard error is actually just the formula for standard deviation but with notation adapted to reflect the fact we are examing sample means (i.e., <span class="math inline">\(\bar{x}\)</span>’s) instead of people (i.e., X’s).</p>
<p>Often we will not talk about standard error but rather the variance of the distribution of sample means. When we do so, we are talking about the same thing - the variability in sample means - but using different units. You can see that the formula for the variance of sample means, see Formula <a href="sampling-precision.html#eq:samplevarchnext">(6.2)</a> below, is just a squared version of the standard error equation, Formula <a href="sampling-precision.html#eq:samplesechnext">(6.1)</a> above.</p>
<p><span class="math display" id="eq:samplevarchnext">\[\begin{equation} 
\sigma_{\bar{x}}^2 = \frac{\sum{(\bar{x} - \bar{\bar{x}})^2}}{k}
      \tag{6.2}
\end{equation}\]</span></p>
<p>How do we interpret variance of sample means? Assuming the sample mean provides an unbiased estimate of the population mean (i.e., <span class="math inline">\(\bar{\bar{x}} = \mu\)</span>), then the <strong>variance of the sample means is simply the average of the squared differences between sample means and the population mean</strong>. Standard error is simply the square root of the variance of sample means. Both are different ways of describing the same thing - the precision with which sample means estimate the population mean.</p>
<p>If the variance of sample means is large, it indicates sample means differ considerably (on average) from the population mean. If the variance of sample means is small, it indicates sample means differ only slightly (on average) from the population mean. If the variance of sample means is zero, all the sample means are exactly the same as the population mean.</p>
<p>We can calculate the variance of sample means below:</p>
<div class="sourceCode" id="cb359"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb359-1"><a href="sampling-precision.html#cb359-1"></a>many_samples <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb359-2"><a href="sampling-precision.html#cb359-2"></a><span class="st">   </span><span class="kw">summarise</span>(<span class="dt">var_of_means =</span> <span class="kw">var.pop</span>(sample_mean)) <span class="op">%&gt;%</span></span>
<span id="cb359-3"><a href="sampling-precision.html#cb359-3"></a><span class="st">   </span><span class="kw">as.data.frame</span>()</span></code></pre></div>
<pre><code>##   var_of_means
## 1        15.73</code></pre>
<p>The standard error of sample mean is just the square root of this value:</p>
<div class="sourceCode" id="cb361"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb361-1"><a href="sampling-precision.html#cb361-1"></a>many_samples <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb361-2"><a href="sampling-precision.html#cb361-2"></a><span class="st">   </span><span class="kw">summarise</span>(<span class="dt">sd_of_means =</span> <span class="kw">sqrt</span>(<span class="kw">var.pop</span>(sample_mean))) <span class="op">%&gt;%</span></span>
<span id="cb361-3"><a href="sampling-precision.html#cb361-3"></a><span class="st">   </span><span class="kw">as.data.frame</span>()</span></code></pre></div>
<pre><code>##   sd_of_means
## 1       3.967</code></pre>
<p>Thus, we can indicate the precision with which sample means (<span class="math inline">\(\bar{x}\)</span>) estimate the population mean (<span class="math inline">\(\mu\)</span>) using the notation below. We use <span class="math inline">\(\sigma_{\bar{x}}^2\)</span> to refer to the variance of sample means and <span class="math inline">\(\sigma_{\bar{x}}\)</span> to refer to the standard error of sample means. Again notice in the notation that for both of these symbols there is a subscript with an <span class="math inline">\(\bar{x}\)</span> to remind us we are talking about the variability of sample means (and not people).</p>
<p><span class="math display">\[
\begin{aligned} 
\sigma_{\bar{x}}^2 &amp;= 15.73 \\
\sigma_{\bar{x}} &amp;= 3.97 \\
\end{aligned} 
\]</span></p>
</div>
<div id="a-short-cut" class="section level2">
<h2><span class="header-section-number">6.5</span> A short cut</h2>
<p>In the previous section we used a computer simulation to calculate the variance of sample means. This involved several steps:</p>
<ol style="list-style-type: decimal">
<li>Obtaining the entire population</li>
<li>Creating 50000 samples (each n = 10) from the population</li>
<li>Calculating the mean for each of the 50000 samples</li>
<li>Calculating the variance of the 50000 sample means as per Formula <a href="sampling-precision.html#eq:samplevarchnext">(6.2)</a></li>
</ol>
<p>All those steps are a lot of work - and a lot of computer time. Interestingly, we don’t need to go to all that work to determine the variance of sample means. There is a quicker way to obtain the variance of sample means. That is, there is a quicker way to determine the precision with which sample means estimate the population mean when we use a sample size of <span class="math inline">\(n\)</span> = 10.</p>
<p>Statisticians have created a short-cut formula for obtaining the variance of sample means. The equation by itself, see Formula <a href="sampling-precision.html#eq:samplevar2chnext">(6.3)</a> below, is extraordinarily simple to use. The formula, however, is not easy to understand. Over many years of teaching, we’ve seen students struggle to understand why the formula is structured in the way that it is - looking for a straightforward logic as to why the short-cut formula works. We encourage you to avoid going down that road. Understanding Formula <a href="sampling-precision.html#eq:samplevar2chnext">(6.3)</a> below is beyond the scope of this chapter and, likely, your mathematical background at this point. It was derived via a complex mathematical proof discussed in <span class="citation">Hays (<a href="#ref-hays1994" role="doc-biblioref">1994</a>)</span> if you want more information. Simply accept that there is a short-cut formula and do not try to understand the logic of the formula.</p>
<p>Variance sample means:</p>
<p><span class="math display" id="eq:samplevar2chnext">\[\begin{equation} 
\sigma_{\bar{x}}^2 = \frac{\sigma^2}{n}
      \tag{6.3}
\end{equation}\]</span></p>
<p>You can see that with this formula the variance of sample means, Formula <a href="sampling-precision.html#eq:samplevar2chnext">(6.3)</a>, is simply the variance of heights of the individuals in the population divided by the sample size. Oddly, this short cut works and provides the variance of sample means. Notice that we don’t need to have the entire population, create thousands of samples, or go through any of the calculation work. All we need to know is the variance of the population and the sample size. In the context of the current example we can compute the variance of the sample means using this information. Recall the variance of people’s heights in the population is <span class="math inline">\(\sigma^2=157.5\)</span> and our sample size is <span class="math inline">\(n\)</span> = 10.</p>
<p><span class="math display">\[
\begin{aligned} 
\sigma_{\bar{x}}^2 &amp;= \frac{\sigma^2}{n} \\
&amp;= \frac{157.5}{10}\\
&amp;= \frac{157.5}{10}\\
&amp;= 15.75
\end{aligned} 
\]</span></p>
<p>We see that the variance of the sample means from this short-cut approach is 15.75 (i.e., <span class="math inline">\(\sigma_{\bar{x}}^2\)</span> = 15.75). Likewise, the variance of the sample means from our simulation was 15.73; incredibly close. If we had used substantially more than 50000 samples in the simulation the 15.73 value would have been 15.75 – making the two results identical. Thus, the short-cut formula gives us the variance of sample means without having to do all the simulation work.</p>
<p>Of course, the variance of sample means is only one of the two ways we can describe the precision of sample estimates of the population mean. Many people prefer to use standard error (i.e. standard deviation of sample means) instead. The calculation for standard error is below:</p>
<p><span class="math display">\[
\begin{aligned} 
\sigma_{\bar{x}} &amp;= \sqrt{\frac{\sigma^2}{n}} \\
&amp;= \sqrt{\frac{157.5}{10}}\\
&amp;= \sqrt{\frac{157.5}{10}}\\
&amp;= \sqrt{15.75} \\
&amp;= 3.97 \\
\end{aligned} 
\]</span></p>
</div>
<div id="estimates-of-precision" class="section level2">
<h2><span class="header-section-number">6.6</span> Estimates of precision</h2>
<p>As wonderful as it is to have a short-cut formula for obtaining the variance of sample means (or standard error) there is a catch. The formula requires knowledge of the population variance (or standard deviation). In a research scenario we don’t know the mean or standard deviation of the population - that’s why we’re conducting research. Consequently, we can’t directly calculate the variance of sample means (or standard error) using Formula <a href="sampling-precision.html#eq:samplevar2chnext">(6.3)</a> above.</p>
<p>Fortunately, if we have only a single study, we can use the sample variance (with n-1 in the denominator) to estimate the population variance. This estimate of the population variance may be higher or lower than the actual population variance - but it will, on average, be correct across many studies. With this estimate of the population variance in hand we can calculate an estimate of the variance of sample means (i.e, the precision of sample means) using Formula <a href="sampling-precision.html#eq:samplevar2estchnext">(6.4)</a> below.</p>
<p>Estimated variance sample means:</p>
<p><span class="math display" id="eq:samplevar2estchnext">\[\begin{equation} 
s_{\bar{x}}^2 = \frac{s^2}{n}
      \tag{6.4}
\end{equation}\]</span></p>
<p>Estimated standard error for the mean:</p>
<p><span class="math display" id="eq:samplese2estchnext">\[\begin{equation} 
s_{\bar{x}} = \sqrt{\frac{s^2}{n}} = \frac{s}{{\sqrt{n}}}
      \tag{6.5}
\end{equation}\]</span></p>
<div id="a-worked-example" class="section level3">
<h3><span class="header-section-number">6.6.1</span> A worked example</h3>
<p>Consider a worked example below. Imagine a scenario where we do not know anything about the population of heights. Therefore we conduct a study by taking a random sample of 10 people to estimate the average height of people in the population. The sample mean is 174.3cm and the sample variance is 30.90. Therefore, our best guess of the unknown population mean is 174.3cm. Because we used a sample (a small subset of the population) we know that 174.3cm is unlikely to be the actual mean height for the population. The mean height for the population might be higher or lower than 174.3cm. Nonetheless, at this point our best guess is that the mean of the population is 174.3cm; but we recognize that this is just an estimate of the population mean and is likely off by some amount.</p>
<p>Wouldn’t it be great to know the extent to which the sample mean in our study might differ from the population mean? As budding statisticians, we know we can’t know that for this particular sample/study, but we can try to figure out how much sample means differ from the population mean on average (when using <span class="math inline">\(n\)</span> = 10) to help us understand the precision of our current sample/study estimate (174.3cm) of the population mean. This precision information is exactly what is conveyed by the variance of sample means, <span class="math inline">\(\sigma_{\bar{x}}^2\)</span>, or standard error of sample means, <span class="math inline">\(\sigma_{\bar{x}}\)</span>. We can’t obtain these precision indices but we can estimate them (via <span class="math inline">\(s_{\bar{x}}^2\)</span> and <span class="math inline">\(s_{\bar{x}}\)</span>).</p>
<p>We want to know the precision with which sample means estimate the population mean. Said another way, we want to know the variance of sample means (or standard error of sample means) but we only have a single study. Therefore, we have to rely on the short-cut formula for determining the variability in sample means. Unfortunately, the short-cut formula for the variance of sample means formula requires the population variance which we don’t know. We do, however, have an estimate of the population variance from our sample. The sample variance is 30.9cm<span class="math inline">\(^2\)</span>. Therefore, our best guess of the unknown population variance is 30.9cm<span class="math inline">\(^2\)</span>. Because we used a sample (a small subset of the population) we know that 30.9cm<span class="math inline">\(^2\)</span> is likely to be different than the actual variance for the population. The variance for the population might be higher or lower than 30.9cm<span class="math inline">\(^2\)</span>. So even though our estimate of the population variance may be “off” in this single sample we know it will be accurate in the long run averaging over many studies (see previous chapter).</p>
<p>Nonetheless, at this point our best guess is that the variance of the population is 30.9cm<span class="math inline">\(^2\)</span>. We use this information to estimate the variance of sample means:</p>
<p><span class="math display">\[
\begin{aligned} 
s^2_{\bar{x}} &amp;= \frac{s^2}{n} \\
&amp;= \frac{30.90}{10} \\
&amp;= 3.09 \\
\end{aligned} 
\]</span></p>
<p>Or alternatively, estimate standard error:</p>
<p><span class="math display">\[
\begin{aligned} 
s_{\bar{x}} &amp;= \sqrt{\frac{s^2}{n}} \\
&amp;= \sqrt{\frac{30.90}{10}} \\
&amp;= \sqrt{3.09} \\
&amp;= 1.76 \\
\end{aligned} 
\]</span></p>
<p>At this point we don’t know the precision of sample means when <span class="math inline">\(n\)</span> = 10; that is, we don’t know <span class="math inline">\(\sigma_{\bar{x}}^2\)</span> or <span class="math inline">\(\sigma_{\bar{x}}\)</span>. We do have an estimate of the precision of sample means (i.e., with via <span class="math inline">\(s_{\bar{x}}^2\)</span> and <span class="math inline">\(s_{\bar{x}}\)</span>). Whenever you calculate the variance of sample means, or standard error, based on sample data it is ALWAYS just an estimate of the actual variance of sample means or the actual standard error.</p>
<p>That fact that an estimate of the variance of sample means is the best you can do with sample data is evident when we calculate the estimate for the many samples. We do that with the R code below:</p>
<div class="sourceCode" id="cb363"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb363-1"><a href="sampling-precision.html#cb363-1"></a>many_samples &lt;-<span class="st"> </span>many_samples <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb363-2"><a href="sampling-precision.html#cb363-2"></a><span class="st">   </span><span class="kw">mutate</span>(<span class="dt">est_se2 =</span> sample_var_n_<span class="dv">1</span><span class="op">/</span>n)</span></code></pre></div>
<p>The command above calculated the estimate variance of sample means (est_se2 or <span class="math inline">\(s_{\bar{x}}^2\)</span>) for each of the 50000 samples. We can see the first few samples with the head() command.</p>
<div class="sourceCode" id="cb364"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb364-1"><a href="sampling-precision.html#cb364-1"></a><span class="kw">head</span>(many_samples)</span></code></pre></div>
<pre><code>##   study  n sample_mean sample_var_n sample_var_n_1 est_se2
## 1     1 10       174.3        27.81          30.90   3.090
## 2     2 10       161.8        83.36          92.62   9.262
## 3     3 10       173.2       139.16         154.62  15.462
## 4     4 10       180.0       321.80         357.56  35.756
## 5     5 10       172.8       160.96         178.84  17.884
## 6     6 10       172.0       159.60         177.33  17.733</code></pre>
<p>Inspect the est_se2 column. Notice how each of these values is an <span class="math inline">\(s_{\bar{x}}^2\)</span> number that is an estimate of <span class="math inline">\(\sigma_{\bar{x}}^2\)</span> = 15.75. The first estimate, <span class="math inline">\(s_{\bar{x}}^2\)</span> = 3.09, is the one we did by hand above. This estimate of the variance of sample means (<span class="math inline">\(s_{\bar{x}}^2\)</span> = 3.09) is much lower than the actual variance of sample means (<span class="math inline">\(\sigma_{\bar{x}}^2\)</span> = 15.75). Notice how the other values in the est_se2 column tend to either overestimate, or underestimate, the variance of sample means. That is, the other studies also overestimate, or underestimate, the precision with which sample means (<span class="math inline">\(n\)</span> = 10) estimate the population mean.</p>
</div>
</div>
<div id="bias-of-precision-estimates" class="section level2">
<h2><span class="header-section-number">6.7</span> Bias of precision estimates</h2>
<p>At this point, you might be a bit concerned about our ability to estimate the variance of sample means ( <span class="math inline">\(\sigma_{\bar{x}}^2\)</span> = 15.75). In the simulation above, we calculated an estimate of the variance of sample means (<span class="math inline">\(s_{\bar{x}}^2\)</span>) and placed those values in the est_se2 column. We saw that the values in this column mostly differed from the actual variance of sample means (15.75). You might wonder if these estimates of the variance of sample means are themselves biased? The answer is no - they are not biased. Our estimate of the population variance (n-1 in the denominator) was not biased so there is no reason to suspect that the estimate of the variance of sample means is biased. But we can confirm this by averaging over the 50000 samples. If the average of the est_est2 column is 15.75 (or very close) than <span class="math inline">\(s_{\bar{x}}^2\)</span> is not a biased estimate of <span class="math inline">\(\sigma_{\bar{x}}^2\)</span> = 15.75.</p>
<div class="sourceCode" id="cb366"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb366-1"><a href="sampling-precision.html#cb366-1"></a>many_samples <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb366-2"><a href="sampling-precision.html#cb366-2"></a><span class="st">   </span><span class="kw">summarise</span>(<span class="dt">avg.of.est_se2 =</span> <span class="kw">mean</span>(est_se2))</span></code></pre></div>
<pre><code>##   avg.of.est_se2
## 1          15.73</code></pre>
<p>We see that the average of the 50000 estimates of the variance of sample means (<span class="math inline">\(s_{\bar{x}}^2\)</span>) is 15.73 which is very close to the actual value of <span class="math inline">\(\sigma_{\bar{x}}^2\)</span> = 15.75. Any sample estimate of the variance of sample means will be off somewhat due to sampling error. But, on average, estimates of the variance of sample means will be unbiased/accurate.</p>
</div>
<div id="where-are-we" class="section level2">
<h2><span class="header-section-number">6.8</span> Where are we?</h2>
<p>So where are we? We’ve learned that sample means may overestimate, or underestimate, the population mean. Over many studies, on average, sample means will approximate the population mean. In other words, on average, sample means are accurate. As well, we’ve learned that the variability in estimates of the population mean is referred to as <strong>precision</strong>. We can index the precision of sample means, for a given sample size, using two indices: variance of sample means and standard error of sample means (i.e., standard deviation of sample means). Both of these formulas require knowledge of the population variance - something we never have.</p>
<p>When we conduct a single study, we get a sample mean. We cannot estimate how precise that sample mean is; we can however, estimate how precise sample means are in general – via the variance of sample means (or standard error). There is a formula for calculating the variance of sample means, Formula <a href="sampling-precision.html#eq:samplevar2chnext">(6.3)</a>, but it requires knowledge of the (unknown) population variance. Consequently, we use an estimate of the population variance in these formulas rather than the actual population variance, see Formula <a href="sampling-precision.html#eq:samplevar2estchnext">(6.4)</a>. As a result, when we calculate variance of sample means (or standard error) using an estimate of the population variance (from our sample) we only obtain an estimates of the variance of sample means. Moreover, this estimate of the variance of sample means is itself influenced by sampling error - but accurate when averaged over many studies.</p>
</div>
<div id="factors-influencing-precision" class="section level2">
<h2><span class="header-section-number">6.9</span> Factors influencing precision</h2>
<p>The formula for variance of the sampling distribution for the mean reveals that it is influenced only by the population variance and sample size. In a research scenario we don’t have any control over the population variance (it is what it is), but we do have control over sample size. Increasing the sample size decreases the variability in sample means - as illustrated in the formulas below.</p>
<p><span class="math display">\[
\begin{aligned} 
\sigma^2 &amp;= 157.5 \\
\sigma_{\bar{x}}^2 &amp;= \frac{\sigma^2}{n} = \frac{157.5}{10} = 15.75 \\
\sigma_{\bar{x}}^2 &amp;= \frac{\sigma^2}{n} = \frac{157.5}{50} = 3.15 \\
\end{aligned} 
\]</span></p>
<p>We also show in Figure <a href="sampling-precision.html#fig:threedist">6.3</a> the difference that increasing the sample size makes. The larger the sample size the less sample means vary due to sampling error. A larger sample size means a more precise estimate of the population parameter.</p>
<div class="figure"><span id="fig:threedist"></span>
<img src="ch_samples_precision/images/sampling_mdist.png" alt="Two sampling distributions illustrating variability in sample means based on sample size. The top graph show the variance of individual's heights in the population. The graph is filled with X's to remind you it is a graph of individuals. There are more individuals than X's. The bottom two graphs show variability in sample means due to random sampling. Each of the lower two graphs is a sampling distribution for a given sample size. Each sampling distribution contains 50000 sample means. Each sample mean is the average of the heights of individuals in a sample. The sampling distributions are filled with $\bar{x}$'s to remind you that it is sample means being graphed. There are more means than $\bar{x}$'s. You can see that by using a larger sample size ($n = 50$, for 50000 samples) there is less variability in sample means than when using a smaller sample size ($n = 10$), for 50000 samples." width="80%" />
<p class="caption">
FIGURE 6.3: Two sampling distributions illustrating variability in sample means based on sample size. The top graph show the variance of individual’s heights in the population. The graph is filled with X’s to remind you it is a graph of individuals. There are more individuals than X’s. The bottom two graphs show variability in sample means due to random sampling. Each of the lower two graphs is a sampling distribution for a given sample size. Each sampling distribution contains 50000 sample means. Each sample mean is the average of the heights of individuals in a sample. The sampling distributions are filled with <span class="math inline">\(\bar{x}\)</span>’s to remind you that it is sample means being graphed. There are more means than <span class="math inline">\(\bar{x}\)</span>’s. You can see that by using a larger sample size (<span class="math inline">\(n = 50\)</span>, for 50000 samples) there is less variability in sample means than when using a smaller sample size (<span class="math inline">\(n = 10\)</span>), for 50000 samples.
</p>
</div>
<p>Additionally, a larger sample size makes the sample estimate (<span class="math inline">\(s^2\)</span>) of the population variance (<span class="math inline">\(\sigma^2\)</span>) more precise. Consequently, it makes the sample estimate (<span class="math inline">\(s_{\bar{x}}^2\)</span> or <span class="math inline">\(s_{\bar{x}}\)</span>) of the variance of sample means (<span class="math inline">\(\sigma_{\bar{x}}^2\)</span> or <span class="math inline">\(\sigma_{\bar{x}}\)</span>) more precise. Therefore, increasing the sample size increases the precision of a) sample means (<span class="math inline">\(\bar{x}\)</span>) and b) precision estimates (<span class="math inline">\(s_{\bar{x}}^2\)</span> or <span class="math inline">\(s_{\bar{x}}\)</span>).</p>
<div style="page-break-after: always;"></div>
</div>
<div id="precision-for-other-statistics" class="section level2">
<h2><span class="header-section-number">6.10</span> Precision for other statistics</h2>
<p>Whenever we use a statistic (e.g., <span class="math inline">\(\bar{x}\)</span>) to estimate a population-level parameter (e.g., <span class="math inline">\(\mu\)</span>) the statistic will differ from the parameter due to sampling error. This is true of all statistics. Therefore, it is possible to generate a sampling distribution for all statistics.</p>
<p>Consider the case of estimating the standardized mean difference (i.e., <span class="math inline">\(\delta\)</span>) between the heights of males and females, illustrated in Figure <a href="sampling-precision.html#fig:ddistributions">6.4</a>. The population-level height information is presented in Figure <a href="sampling-precision.html#fig:ddistributions">6.4</a>A. The sampling distribution for sample-level <span class="math inline">\(d_{unbiased}\)</span> values when you use 10 people per group (10 males, 10 females) is presented in Figure <a href="sampling-precision.html#fig:ddistributions">6.4</a>B. We could calculate the variance of <span class="math inline">\(d_{unbiased}\)</span> values or the standard error (i.e., standard deviation) of <span class="math inline">\(d_{unbiased}\)</span> values; just like we did for sample mean.</p>
<p>You can see in Figure <a href="sampling-precision.html#fig:ddistributions">6.4</a>B that even though the population-level standardized mean difference is 1.49 (<span class="math inline">\(\delta\)</span> = 1.49) there was considerably variability in sample-level <span class="math inline">\(d_{unbiased}\)</span> values. Indeed, inspecting the sample-level data reveals when the population difference is <span class="math inline">\(\delta\)</span> = 1.49, the sample level differences range from <span class="math inline">\(d_{unbiased}\)</span> = -0.38 to <span class="math inline">\(d_{unbiased}\)</span> = 5.50. That’s a considerable range. When <span class="math inline">\(d_{unbiased}\)</span> = -0.38 you would conclude, in your study, that the mean female height is .38 standard deviations higher than than the mean male height. Yet a colleague, conducting exactly the same study, could obtain a sample that leads him to observe <span class="math inline">\(d_{unbiased}\)</span> = 5.50. This would indicate to him that the mean male height is 5.50 standard deviations higher than the mean female height; an opposite conclusion. The results of both your study and the colleague’s study differ considerably from the truth that <span class="math inline">\(\delta\)</span> = 1.49 – which indicates the mean male height is 1.49 standard deviations higher than the mean female height.</p>
<p>We investigated the extent to which study-level <span class="math inline">\(d_{unbiased}\)</span> values differ from the population <span class="math inline">\(\delta\)</span> = 1.49 when using 100 people per group for the comparison (i.e., 100 males, 100 females).
You can see in Figure <a href="sampling-precision.html#fig:ddistributions">6.4</a>C that in this scenario the precision of the sample estimates (<span class="math inline">\(d_{unbiased}\)</span>) of the population parameter (<span class="math inline">\(\delta\)</span>) still vary considerably - but substantially less than they did when it was 10 per group. With a 100 people per group, the <span class="math inline">\(d_{unbiased}\)</span> values range from 0.91 to 2.21. For the lower end of this range, 0.91, a researcher would conclude that the mean for males is .91 standard deviations higher than the mean for females. At the upper end of this range, 2.21, a researcher would conclude that the mean for males is 2.21 standard deviations higher than the mean for females. The variability in <span class="math inline">\(d_{unbiased}\)</span> values is still large - but at least the conclusions are a) all in the same direction, and b) would all be considered large (i.e, above 0.80) according to Cohen’s standards.</p>
<p>These simulations illustrate a few important points. First, drawing any conclusion from a single study is problematic. The findings for a single study may differ substantially from the population parameter. Second, increasing sample size increases the precision with which a sample statistic estimates a population parameter. Third, drawing conclusions from small sample size studies (e.g., <span class="math inline">\(n\)</span> = 10 per group) is extraordinarily problematic. Finally, we note that single studies (even with small sample size) are useful because they serve as data points for a future meta-analysis.</p>
<div class="figure"><span id="fig:ddistributions"></span>
<img src="ch_samples_precision/images/d_distribs2.png" alt="Sampling distribution for $d_{unbiased}$" width="80%" />
<p class="caption">
FIGURE 6.4: Sampling distribution for <span class="math inline">\(d_{unbiased}\)</span>
</p>
</div>

</div>
</div>
<h3>References</h3>
<div id="refs" class="references">
<div id="ref-hays1994">
<p>Hays, William. 1994. <em>Statistics</em>. 5th ed. Cengage Learning.</p>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="sampling-accuracy.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="probability-of-a-sample-mean.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook/js/app.min.js"></script>
<script src="libs/gitbook/js/lunr.js"></script>
<script src="libs/gitbook/js/clipboard.min.js"></script>
<script src="libs/gitbook/js/plugin-search.js"></script>
<script src="libs/gitbook/js/plugin-sharing.js"></script>
<script src="libs/gitbook/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook/js/plugin-bookdown.js"></script>
<script src="libs/gitbook/js/jquery.highlight.js"></script>
<script src="libs/gitbook/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": true,
"facebook": false,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/yihui/bookdown-crc/edit/master/06-samples_precision.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["bookdown.pdf", "bookdown.epub"],
"toc": {
"collapse": "none"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
